/* =========================================================
   NO WAY! — banque d'anecdotes vraies et fausses
   Une seule banque alimente trois épreuves :
     · Le Détecteur  — vrai ou n'importe quoi ?
     · Le Duel       — une vraie contre une fausse, choisis
     · Lequel ment ? — trois vraies, une inventée
   Structure : {t, s, v, e}
     t = thème (mêmes clés que Q) · s = l'affirmation
     v = 1 si elle est vraie, 0 si elle est inventée
     e = l'explication, révélée après coup — et qui doit valoir
         plus que l'affirmation elle-même
   Les fausses ne sont jamais absurdes : ce sont des croyances
   répandues ou des inventions crédibles. C'est tout l'intérêt.
   Chargé avant index.html ; expose la globale `ANECDOTES`.
   ========================================================= */
const ANECDOTES=[

/* ---------- animaux ---------- */
{t:'animaux',v:1,s:"Les pieuvres ont trois cœurs.",
 e:"Deux poussent le sang vers les branchies, le troisième vers le reste du corps. Ce dernier s'arrête quand la pieuvre nage — d'où sa préférence marquée pour la marche sur le fond, moins épuisante."},
{t:'animaux',v:1,s:"Les flamants roses naissent gris.",
 e:"Le rose vient des crustacés qu'ils filtrent. En captivité, sans supplément, ils pâlissent. Un flamant terne est un flamant mal nourri — les zoos surveillent la couleur comme un bulletin de santé."},
{t:'animaux',v:1,s:"Les wombats font des crottes cubiques.",
 e:"Leur intestin a des parois d'élasticité inégale qui moulent les cubes. Le wombat les empile pour marquer son territoire : une crotte ronde roulerait, une crotte cubique reste où on l'a posée."},
{t:'animaux',v:1,s:"Les hippopotames fabriquent leur propre crème solaire.",
 e:"Ils sécrètent un liquide rouge, longtemps pris pour du sang, qui filtre les ultraviolets et fait aussi antibiotique. Leurs blessures s'infectent remarquablement peu pour un animal qui passe ses journées dans la vase."},
{t:'animaux',v:1,s:"Les koalas ont des empreintes digitales presque impossibles à distinguer des nôtres.",
 e:"Elles sont apparues séparément, des millions d'années après notre dernier ancêtre commun. Des experts en criminalistique ont admis qu'une empreinte de koala sur une scène de crime les tromperait."},
{t:'animaux',v:1,s:"Les dauphins se donnent des noms.",
 e:"Chacun invente jeune un sifflement signature et le garde à vie. Les autres l'imitent pour l'appeler à distance — et un dauphin répond au sien même diffusé par un haut-parleur."},
{t:'animaux',v:1,s:"Un tardigrade a survécu à un séjour dans le vide spatial.",
 e:"En 2007, des tardigrades exposés dix jours au vide et aux rayons cosmiques sont revenus vivants, et certains ont pondu. Ils se déshydratent totalement et suspendent leur métabolisme en attendant des jours meilleurs."},
{t:'animaux',v:1,s:"Les manchots offrent des cailloux pour séduire.",
 e:"Chez les manchots Adélie, le mâle cherche le plus beau galet du secteur et le dépose aux pieds de la femelle. Les bons cailloux étant rares, le vol entre voisins est constant."},
{t:'animaux',v:1,s:"La crevette-mante frappe si vite que l'eau bout autour de son poing.",
 e:"Son coup atteint la vitesse d'une balle de calibre 22. La dépression créée derrière son appendice fait bouillir l'eau une fraction de seconde, et l'implosion émet un éclair de lumière."},
{t:'animaux',v:1,s:"Les vaches ont des amies préférées.",
 e:"Séparez deux vaches liées et leur rythme cardiaque grimpe, leur production de lait chute. Remettez-les ensemble, tout rentre dans l'ordre. Certains élevages composent désormais les groupes selon ces affinités."},
{t:'animaux',v:1,s:"Un escargot peut dormir trois ans d'affilée.",
 e:"Face à la sécheresse, il se scelle derrière un opercule de mucus durci et attend. Des spécimens collés à des étiquettes de musée se sont réveillés après plusieurs années de vitrine."},
{t:'animaux',v:1,s:"Le rat-taupe nu ne développe pratiquement jamais de cancer.",
 e:"Ses cellules cessent de se diviser dès qu'elles se touchent, grâce à une molécule que nous ne fabriquons pas. Il vit trente ans, dix fois plus qu'une souris de taille comparable."},
{t:'animaux',v:0,s:"Les autruches enfouissent la tête dans le sable quand elles ont peur.",
 e:"Elles ne l'ont jamais fait. Elles retournent leurs œufs enfouis avec le bec, ce qui de loin en donne l'illusion. Face au danger, une autruche court à 70 km/h ou frappe — un coup de patte peut tuer un lion."},
{t:'animaux',v:0,s:"Les poissons rouges ont une mémoire de trois secondes.",
 e:"Ils retiennent plusieurs mois. On leur a appris à pousser un levier à une heure fixe pour obtenir leur nourriture, et à reconnaître les visages humains. Le mythe arrangeait surtout les vendeurs de bocaux."},
{t:'animaux',v:0,s:"Un chameau stocke de l'eau dans ses bosses.",
 e:"Les bosses sont de la graisse, pas de l'eau. C'est une réserve d'énergie rangée en un seul endroit pour ne pas isoler tout le corps sous la chaleur. L'eau, il la garde dans son sang et ses tissus."},
{t:'animaux',v:0,s:"Le caméléon change de couleur pour se camoufler.",
 e:"Il change surtout d'humeur et de température. Les couleurs vives signalent l'agressivité ou la séduction ; un caméléon calme reste vert parce que le vert est sa couleur de repos, pas sa cachette."},
{t:'animaux',v:0,s:"Les taureaux chargent parce qu'ils voient du rouge.",
 e:"Ils ne distinguent pas le rouge. C'est le mouvement de la cape qui les déclenche — un torero agitant un drap blanc obtiendrait le même résultat. La couleur est là pour le public, et pour masquer le sang."},
{t:'animaux',v:0,s:"Les lemmings se jettent des falaises par vagues entières.",
 e:"Une équipe de tournage les a poussés depuis un plateau tournant en 1958 pour filmer la scène. Les lemmings migrent en masse et certains se noient en traversant l'eau ; personne ne se suicide."},
{t:'animaux',v:0,s:"Un ver de terre coupé en deux donne deux vers.",
 e:"La moitié avant peut refaire une queue si la coupe est assez loin. La moitié arrière, elle, n'a ni bouche ni cerveau : elle meurt. On obtient un ver mutilé et un cadavre, pas des jumeaux."},
{t:'animaux',v:0,s:"Les chauves-souris sont aveugles.",
 e:"Toutes voient, et les grandes roussettes ont une vision excellente. L'écholocation sert la nuit, quand la vue ne suffit plus — c'est un instrument de plus, pas un remplacement."},
{t:'animaux',v:0,s:"Les mille-pattes ont bien mille pattes.",
 e:"La plupart en ont entre trente et quatre cents. Il a fallu attendre 2021 pour qu'une espèce australienne dépasse enfin le millier, avec 1 306 pattes — et elle vit à soixante mètres sous terre."},

/* ---------- espace ---------- */
{t:'espace',v:1,s:"Un jour sur Vénus dure plus longtemps qu'une année vénusienne.",
 e:"Vénus tourne sur elle-même en 243 jours terrestres et fait le tour du Soleil en 225. Elle tourne aussi à l'envers : là-bas, le Soleil se lève à l'ouest, deux fois par année."},
{t:'espace',v:1,s:"Saturne flotterait sur l'eau.",
 e:"Sa densité moyenne est inférieure à celle de l'eau — il faudrait juste une baignoire de 120 000 kilomètres. La planète est si peu dense qu'elle s'aplatit visiblement sous sa propre rotation."},
{t:'espace',v:1,s:"Il y a plus d'arbres sur Terre que d'étoiles dans la Voie lactée.",
 e:"Environ 3 000 milliards d'arbres, contre 100 à 400 milliards d'étoiles. Le comptage des arbres date de 2015 et a multiplié par huit l'estimation précédente — on connaissait mal notre propre planète."},
{t:'espace',v:1,s:"Le Soleil représente 99,8 % de la masse du système solaire.",
 e:"Tout le reste — les huit planètes, les lunes, les astéroïdes, les comètes — tient dans les 0,2 % restants. Et Jupiter à lui seul en occupe les deux tiers."},
{t:'espace',v:1,s:"Les astronautes décrivent l'odeur de l'espace comme celle de la poudre à canon.",
 e:"L'odeur s'accroche aux combinaisons rentrées dans le sas. Métal chaud, viande grillée, soudure : ce sont probablement des atomes d'oxygène qui se recombinent violemment au contact de l'air de la station."},
{t:'espace',v:1,s:"Une cuillère à café d'étoile à neutrons pèserait des milliards de tonnes.",
 e:"La matière y est comprimée au point que les électrons sont enfoncés dans les noyaux. Un dé à coudre de cette étoile pèse autant que toute l'humanité réunie."},
{t:'espace',v:1,s:"Il existe un nuage d'alcool au centre de la Galaxie.",
 e:"Sagittarius B2 contient des milliards de kilomètres cubes d'alcool éthylique, mêlé à des composés qui sentent la framboise et le rhum. Imbuvable : il est mille milliards de fois plus dilué que l'air."},
{t:'espace',v:1,s:"Les empreintes de pas laissées sur la Lune tiendront des millions d'années.",
 e:"Sans vent ni pluie, rien ne les efface. Seuls les micrométéorites les grignotent, très lentement. La trace de Neil Armstrong sera encore lisible quand notre espèce aura disparu."},
{t:'espace',v:0,s:"La Grande Muraille de Chine est visible à l'œil nu depuis la Lune.",
 e:"Elle est déjà difficile à repérer depuis l'orbite basse, à 400 km. Depuis la Lune, mille fois plus loin, il faudrait distinguer un cheveu à deux kilomètres. Aucun astronaute d'Apollo ne l'a vue."},
{t:'espace',v:0,s:"Sans combinaison, le corps humain explose dans le vide.",
 e:"La peau tient très bien. On gonfle, on perd connaissance en quinze secondes, l'eau des muqueuses bout. Un technicien de la NASA a survécu à une décompression accidentelle en 1966 — il se souvient d'avoir senti sa salive bouillir."},
{t:'espace',v:0,s:"La face cachée de la Lune est plongée dans une nuit permanente.",
 e:"Elle reçoit autant de soleil que l'autre. Elle est cachée, pas sombre : la Lune tourne sur elle-même exactement au rythme de son orbite, si bien qu'elle nous montre toujours le même côté."},
{t:'espace',v:0,s:"Mercure est la planète la plus chaude du système solaire.",
 e:"C'est Vénus, avec 465 °C constants, contre 430 °C au maximum sur Mercure — qui descend à −180 °C la nuit. Vénus est plus loin du Soleil mais son atmosphère de gaz carbonique ne laisse plus rien repartir."},
{t:'espace',v:0,s:"Il n'y a pas de gravité dans la Station spatiale internationale.",
 e:"Il y en a presque 90 % de celle du sol. Les astronautes ne flottent pas faute de gravité : ils tombent en permanence vers la Terre, et la station tombe avec eux, en manquant le sol à chaque tour."},
{t:'espace',v:0,s:"L'étoile Polaire est l'étoile la plus brillante du ciel.",
 e:"Elle n'est même pas dans les quarante premières. C'est Sirius. La Polaire ne doit sa réputation qu'à sa position : elle est presque pile dans l'axe de rotation de la Terre, donc immobile."},

/* ---------- géographie ---------- */
{t:'geo',v:1,s:"Une ville suédoise entière a été déplacée de plusieurs kilomètres.",
 e:"Kiruna s'effondrait au-dessus de sa propre mine de fer. Depuis 2014, on transporte les bâtiments un par un, dont l'église en bois de cent ans, vers un nouveau centre à trois kilomètres."},
{t:'geo',v:1,s:"La Russie et les États-Unis sont séparés par moins de quatre kilomètres.",
 e:"Entre la Grande et la Petite Diomède, dans le détroit de Béring. En hiver, la glace les relie. Elles sont aussi de part et d'autre de la ligne de changement de date : d'une île à l'autre, on saute un jour."},
{t:'geo',v:1,s:"Des maisons sont coupées en deux par une frontière entre deux pays, et la porte d'entrée décide du pays.",
 e:"Baarle, à la frontière belgo-néerlandaise, compte trente enclaves imbriquées et une frontière qui traverse des salons. Des familles ont déplacé leur porte d'entrée de quelques mètres pour changer de fiscalité."},
{t:'geo',v:1,s:"Le Sahara a été vert, avec des lacs et des hippopotames.",
 e:"Il y a 6 000 ans à peine. Les gravures rupestres du Tassili montrent des troupeaux et des nageurs. Un léger basculement de l'axe terrestre a suffi à couper les pluies — et le désert s'est installé en quelques siècles."},
{t:'geo',v:1,s:"D'est en ouest, l'Australie est plus large que le diamètre de la Lune.",
 e:"4 000 kilomètres d'est en ouest, contre 3 475 de diamètre lunaire. Ce qui n'empêche pas la Lune d'avoir une surface totale plus grande — elle est ronde dans toutes les directions."},
{t:'geo',v:1,s:"Il n'y a pas une seule rivière en Arabie saoudite.",
 e:"Pas un cours d'eau permanent sur deux millions de kilomètres carrés. Le pays vit du dessalement de la mer et de nappes fossiles vieilles de dizaines de milliers d'années, qu'on ne recharge plus."},
{t:'geo',v:1,s:"La mer Caspienne est le plus grand lac du monde.",
 e:"Salée, immense, sans issue vers l'océan : elle a tous les attributs d'une mer sauf la connexion. Son statut juridique — mer ou lac — a occupé cinq pays riverains pendant vingt ans, pétrole oblige."},
{t:'geo',v:1,s:"Le point le plus éloigné de toute terre émergée porte un nom.",
 e:"Le point Nemo, dans le Pacifique Sud. La terre la plus proche est à 2 700 kilomètres — les humains les plus proches sont souvent les astronautes en orbite. Les agences spatiales y font tomber leurs satellites."},
{t:'geo',v:0,s:"Le mont Everest est le point de la Terre le plus éloigné du centre du globe.",
 e:"C'est le Chimborazo, en Équateur. La Terre est renflée à l'équateur : ce volcan de 6 263 mètres part de plus haut et dépasse l'Everest de deux kilomètres en distance au centre."},
{t:'geo',v:0,s:"Le désert du Sahara est le plus grand désert du monde.",
 e:"C'est l'Antarctique. Un désert se définit par ses précipitations, pas par le sable : il tombe moins d'eau au pôle Sud que dans le Sahara, qui n'arrive qu'en deuxième position."},
{t:'geo',v:0,s:"Istanbul est la capitale de la Turquie.",
 e:"C'est Ankara depuis 1923. Atatürk a délibérément choisi une ville de l'intérieur, loin des convoitises et du passé ottoman. Istanbul reste la plus peuplée, ce qui entretient la confusion."},
{t:'geo',v:0,s:"L'Amazone est le plus long fleuve du monde.",
 e:"Le Nil garde le titre de peu, et le débat n'est pas clos — tout dépend de la source retenue. L'Amazone est en revanche sans rivale pour le débit : elle déverse plus d'eau que les six suivants réunis."},
{t:'geo',v:0,s:"Les continents dérivent d'environ un mètre par an.",
 e:"Plutôt deux à dix centimètres, la vitesse à laquelle poussent les ongles. Sur des centaines de millions d'années, cela suffit à ouvrir un océan — mais le GPS ne détecte le mouvement qu'après plusieurs années."},

/* ---------- histoire ---------- */
{t:'histo',v:1,s:"Cléopâtre a vécu plus près de nous que de la construction des pyramides.",
 e:"Les grandes pyramides datent de 2560 avant notre ère, Cléopâtre est morte en 30. Deux mille cinq cents ans la séparent des pyramides, deux mille de nous. Elles étaient déjà pour elle des antiquités."},
{t:'histo',v:1,s:"L'université d'Oxford est plus ancienne que l'empire aztèque.",
 e:"On y enseignait dès 1096. Tenochtitlan a été fondée en 1325. Quand les Aztèques posaient la première pierre de leur capitale, Oxford avait déjà deux siècles de querelles universitaires derrière elle."},
{t:'histo',v:1,s:"La guerre la plus courte de l'histoire a duré trente-huit minutes.",
 e:"Entre le Royaume-Uni et Zanzibar, en 1896. Le bombardement a commencé à 9 h 02 ; le palais s'est effondré et le drapeau est tombé à 9 h 40. Zanzibar a ensuite dû payer la facture des obus."},
{t:'histo',v:1,s:"Un roi de France est mort d'un coup de porte.",
 e:"Charles VIII, en 1498, s'est cogné le front contre le linteau d'une porte basse en allant voir une partie de jeu de paume. Il a suivi la partie, s'est effondré quelques heures plus tard, et n'a jamais repris connaissance."},
{t:'histo',v:1,s:"Le fax a été inventé avant le téléphone.",
 e:"Alexander Bain dépose le brevet du télécopieur en 1843, trente-trois ans avant le téléphone de Bell. Sa machine balayait un texte en relief avec un stylet et reproduisait le tracé à l'autre bout d'un fil."},
{t:'histo',v:1,s:"Napoléon a été attaqué par des lapins.",
 e:"Une chasse organisée en son honneur avait fait acheter des lapins d'élevage au lieu de lapins sauvages. Lâchés, les animaux ont pris l'Empereur pour le nourrisseur et ont chargé en masse. Il a battu en retraite jusqu'à sa voiture."},
{t:'histo',v:1,s:"Le dernier soldat japonais s'est rendu vingt-neuf ans après la guerre.",
 e:"Hiroo Onoda tenait la jungle philippine depuis 1945, convaincu que la reddition était une ruse. Il n'a déposé les armes qu'en 1974, quand son ancien commandant a fait le déplacement pour lui en donner l'ordre en personne."},
{t:'histo',v:1,s:"Les pyramides étaient blanches et brillantes.",
 e:"Un revêtement de calcaire poli les faisait luire au soleil, visible à des kilomètres. Un tremblement de terre l'a descellé au XIVᵉ siècle et les habitants du Caire l'ont récupéré pour bâtir mosquées et remparts."},
{t:'histo',v:0,s:"Les Vikings portaient des casques à cornes.",
 e:"Aucun casque à cornes n'a jamais été retrouvé dans une tombe viking. Le costumier d'un opéra de Wagner, en 1876, en a habillé ses chanteurs — et l'image a tenu bon depuis."},
{t:'histo',v:0,s:"Marie-Antoinette a lancé : « Qu'ils mangent de la brioche ! »",
 e:"La phrase circulait déjà dans les Confessions de Rousseau quand elle avait neuf ans et vivait encore à Vienne. On l'a attribuée à plusieurs princesses avant elle ; la Révolution lui a simplement trouvé la meilleure destinataire."},
{t:'histo',v:0,s:"Au Moyen Âge, on croyait la Terre plate.",
 e:"La rotondité était admise depuis l'Antiquité grecque et n'a jamais été sérieusement contestée par les savants médiévaux. Le mythe date du XIXᵉ siècle, forgé pour opposer science et religion."},
{t:'histo',v:0,s:"Einstein était mauvais en mathématiques à l'école.",
 e:"Il maîtrisait le calcul différentiel à quinze ans. La légende vient d'un système de notation suisse inversé : ses 6, les meilleures notes possibles, ont été lus comme des notes catastrophiques."},
{t:'histo',v:0,s:"Le Grand Incendie de Londres a été arrêté par la pluie.",
 e:"C'est la démolition volontaire de rangées entières de maisons qui a coupé la propagation, avec l'aide d'une baisse du vent. La pluie n'est arrivée qu'après. Le feu a détruit 13 000 maisons et fait très peu de morts."},
{t:'histo',v:0,s:"Les gladiateurs mouraient presque à chaque combat.",
 e:"Un gladiateur coûtait des années de formation : le laisser mourir ruinait son propriétaire. Les estimations donnent une mort pour cinq à dix combats, et beaucoup se retiraient vivants après une carrière complète."},

/* ---------- sciences ---------- */
{t:'sci',v:0,s:"Le verre est un liquide très lent : les vitraux médiévaux sont plus épais en bas parce qu'ils ont coulé.",
 e:"Les souffleurs posaient simplement le côté épais vers le bas, pour la stabilité. À température ambiante, le verre mettrait plus longtemps que l'âge de l'univers à couler d'une épaisseur visible. C'est un solide, désordonné mais solide."},
{t:'sci',v:1,s:"L'eau chaude peut geler plus vite que l'eau froide.",
 e:"L'effet Mpemba, redécouvert en 1963 par un lycéen tanzanien que ses professeurs ont ridiculisé. Les explications se disputent encore — évaporation, convection, liaisons hydrogène — mais l'effet s'observe."},
{t:'sci',v:1,s:"Il y a plus de bactéries dans votre bouche que d'humains sur Terre.",
 e:"Une bouche en héberge des dizaines de milliards, réparties en 700 espèces. Un simple baiser de dix secondes en transfère 80 millions d'un partenaire à l'autre."},
{t:'sci',v:1,s:"Le miel retrouvé dans des tombes égyptiennes était encore comestible.",
 e:"Trop sucré et trop acide pour les bactéries, presque sans eau : le miel ne se gâte pratiquement pas. Des pots de trois mille ans ouverts par des archéologues contenaient un miel parfaitement sain."},
{t:'sci',v:1,s:"Un éclair est cinq fois plus chaud que la surface du Soleil.",
 e:"Environ 30 000 °C, contre 5 500 pour le Soleil. La chaleur dilate l'air si brutalement qu'elle crée une onde de choc : le tonnerre n'est rien d'autre que le bruit de l'air qui se referme."},
{t:'sci',v:1,s:"Votre corps émet de la lumière, trop faible pour être vue.",
 e:"Une bioluminescence mille fois sous notre seuil de perception, mesurée par des caméras japonaises en 2009. Elle suit un cycle : le visage brille le plus en fin d'après-midi."},
{t:'sci',v:1,s:"L'hélium était connu sur le Soleil avant d'être trouvé sur Terre.",
 e:"Repéré en 1868 dans le spectre solaire pendant une éclipse, il portait déjà le nom du Soleil quand on l'a enfin isolé sur Terre, vingt-sept ans plus tard, dans un minerai d'uranium."},
{t:'sci',v:1,s:"Le matériau naturel le plus résistant à la traction jamais mesuré est une dent de coquillage.",
 e:"La dent de patelle bat les meilleures fibres de carbone. Ses nanofibres minérales lui servent à râper la roche pour en décoller les algues, sans s'user — un outil de chantier sur un animal de trois centimètres."},
{t:'sci',v:0,s:"On n'utilise que 10 % de notre cerveau.",
 e:"L'imagerie montre toutes les zones actives sur vingt-quatre heures. Un organe qui consomme 20 % de notre énergie pour ne rien faire à 90 % n'aurait pas survécu à l'évolution. Aucune lésion cérébrale n'est indolore."},
{t:'sci',v:0,s:"Les couleurs de la langue correspondent à des zones du goût.",
 e:"La fameuse carte vient d'une traduction ratée d'une thèse allemande de 1901. Chaque papille détecte les cinq saveurs. Posez du sucre n'importe où sur la langue : c'est sucré partout."},
{t:'sci',v:0,s:"Les cheveux et les ongles continuent de pousser après la mort.",
 e:"La peau se rétracte en se déshydratant et dégage ce qui était déjà sorti. Rien ne pousse : les cellules mortes ne se divisent pas. L'illusion est assez forte pour avoir nourri des siècles d'histoires de vampires."},
{t:'sci',v:0,s:"Un centime lâché du haut d'une tour peut tuer un passant.",
 e:"Sa forme le fait flotter et osciller : il plafonne autour de 40 km/h. On le reçoit comme une pichenette. Un stylo, plus lourd et mieux profilé, serait autrement inquiétant."},
{t:'sci',v:0,s:"Le sang est bleu dans les veines et devient rouge au contact de l'air.",
 e:"Il est rouge partout, plus sombre quand il a rendu son oxygène. Les veines paraissent bleues parce que la peau diffuse davantage les courtes longueurs d'onde — c'est un effet d'optique, pas de chimie."},
{t:'sci',v:0,s:"La foudre ne tombe jamais deux fois au même endroit.",
 e:"L'Empire State Building la reçoit une vingtaine de fois par an. Un point haut et conducteur est exactement ce que cherche la décharge : loin de l'éviter, elle y revient."},

/* ---------- WTF ---------- */
{t:'wtf',v:1,s:"Un homme a survécu à deux bombes atomiques.",
 e:"Tsutomu Yamaguchi était à Hiroshima en voyage d'affaires, blessé mais debout. Il est rentré chez lui à Nagasaki, où la seconde bombe est tombée trois jours plus tard. Il est mort en 2010, à 93 ans."},
{t:'wtf',v:1,s:"Un avion de ligne est tombé en panne sèche en plein vol à cause d'une conversion ratée entre livres et kilos.",
 e:"Le vol 143 d'Air Canada, en 1983, est tombé en panne sèche à 12 000 mètres. Le commandant, pilote de planeur, a posé l'appareil sur une ancienne piste militaire transformée en circuit automobile, en plein week-end de course."},
{t:'wtf',v:1,s:"Il existe une ville où l'on n'a plus le droit d'être enterré.",
 e:"Longyearbyen, au Svalbard. Le permafrost empêche les corps de se décomposer et conserve les virus intacts — on y a retrouvé la grippe de 1918 encore active. Les malades en fin de vie sont évacués vers le continent."},
{t:'wtf',v:1,s:"La Nouvelle-Zélande a reconnu un fleuve comme une personne.",
 e:"Le Whanganui a obtenu en 2017 les droits d'une personne morale, après cent quarante ans de démarches maories. Deux gardiens parlent en son nom, et on peut porter plainte au nom du fleuve."},
{t:'wtf',v:1,s:"Un homme a détourné un avion, sauté en parachute avec la rançon, et n'a jamais été retrouvé.",
 e:"D. B. Cooper, en 1971, avec 200 000 dollars. Le FBI a fermé le dossier en 2016 sans identification. Une partie des billets a refait surface sur une plage en 1980, ce qui n'a fait qu'épaissir le mystère."},
{t:'wtf',v:1,s:"Un incendie de mine brûle sous une ville américaine depuis 1962.",
 e:"À Centralia, en Pennsylvanie, un feu de veine de charbon a chassé mille habitants. Il reste assez de charbon pour deux cent cinquante ans de combustion. Le code postal a été supprimé en 2002."},
{t:'wtf',v:1,s:"Un pigeon a été décoré d'une médaille militaire.",
 e:"Cher Ami a livré son message en 1918 avec une balle dans la poitrine et une patte arrachée, sauvant près de deux cents soldats encerclés. Il est empaillé au Smithsonian, décoré de la Croix de guerre."},
{t:'wtf',v:1,s:"Le pays le plus plat du monde n'a aucun point à plus de trois mètres d'altitude.",
 e:"Les Maldives culminent à 2,4 mètres. Le gouvernement a tenu un conseil des ministres sous l'eau, en scaphandre, pour signer un appel sur le climat — et met de l'argent de côté pour acheter des terres ailleurs."},
{t:'wtf',v:0,s:"Un homme a vendu la tour Eiffel deux fois à des ferrailleurs.",
 e:"Victor Lustig l'a bien vendue en 1925, mais une seule fois. Sa victime, morte de honte, n'a jamais porté plainte — c'est pourquoi il a pu tenter un second coup, qui a échoué avant la vente."},
{t:'wtf',v:0,s:"Il pleut des poissons chaque année dans un village du Honduras.",
 e:"La Lluvia de Peces existe, mais aucune trompe d'eau n'a jamais été filmée en train de les larguer. Les biologistes penchent pour des poissons souterrains chassés à la surface par les crues — moins spectaculaire, plus solide."},
{t:'wtf',v:0,s:"Une loi anglaise autorise encore à tirer sur un Écossais à l'arc dans York.",
 e:"On cite cette loi partout ; elle n'existe dans aucun recueil. Le Parlement britannique a publiquement démenti. Les fausses lois pittoresques prospèrent parce que personne ne va vérifier les archives."},
{t:'wtf',v:0,s:"Un homme a passé toute sa vie dans un aéroport parce qu'il aimait ça.",
 e:"Mehran Karimi Nasseri a vécu dix-huit ans à Roissy, mais par blocage administratif, pas par goût. Quand ses papiers ont enfin été régularisés, il est parti. Il est revenu y mourir en 2022."},
{t:'wtf',v:0,s:"La NASA a dépensé des millions pour un stylo qui écrit dans l'espace, les Russes ont pris un crayon.",
 e:"L'histoire est fausse. Une entreprise privée a financé le stylo seule et l'a vendu aux deux agences. Le crayon était d'ailleurs proscrit : la mine casse, et des copeaux de graphite qui flottent dans une cabine à oxygène pur, c'est un incendie."},

/* ---------- cuisine ---------- */
{t:'cuisine',v:1,s:"Le ketchup était vendu comme médicament.",
 e:"Un médecin de l'Ohio l'a breveté en 1834 en pilules contre les troubles digestifs, en s'appuyant sur les vertus supposées de la tomate. Les contrefaçons ont ruiné le marché en dix ans."},
{t:'cuisine',v:1,s:"Les carottes étaient violettes avant d'être orange.",
 e:"Violettes, jaunes ou blanches en Asie centrale. L'orange s'est imposé aux Pays-Bas au XVIIᵉ siècle — sélection patiente d'une variété rare, dont la couleur tombait bien pour la maison d'Orange."},
{t:'cuisine',v:1,s:"La banane est techniquement une baie, la fraise non.",
 e:"Une baie vient d'un seul ovaire et contient ses graines : la banane coche tout. La fraise porte les siennes dehors — les petits points sont les vrais fruits, et la chair rouge n'est qu'un réceptacle gonflé."},
{t:'cuisine',v:1,s:"Le wasabi servi dans presque tous les restaurants n'est pas du wasabi.",
 e:"C'est du raifort coloré. La vraie plante pousse trois ans dans l'eau froide de montagne, se râpe à la peau de requin et perd son piquant en quinze minutes — invendable en tube."},
{t:'cuisine',v:1,s:"Le chocolat blanc ne contient pas de cacao.",
 e:"Il ne garde que le beurre de cacao, sans les solides qui donnent la couleur et le goût. C'est pourquoi plusieurs pays ont longtemps refusé de l'appeler chocolat."},
{t:'cuisine',v:1,s:"Les amandes amères contiennent du cyanure.",
 e:"Une cinquantaine suffirait à tuer un adulte. La variété douce que nous mangeons a perdu le gène responsable — une mutation unique, repérée et propagée par les cultivateurs il y a des millénaires."},
{t:'cuisine',v:1,s:"Le safran vaut plus cher que l'or au gramme, certaines années.",
 e:"Il faut 150 000 fleurs cueillies à la main, à l'aube, pour un kilo — et seulement trois stigmates par fleur. Tout se fait en deux semaines par an, ce qui interdit toute mécanisation."},
{t:'cuisine',v:0,s:"Les tomates sont des légumes.",
 e:"Botaniquement, ce sont des fruits. Mais la Cour suprême des États-Unis les a déclarées légumes en 1893 — non par science, mais parce que les légumes étaient taxés à l'importation et pas les fruits."},
{t:'cuisine',v:0,s:"Le café a été découvert par des moines qui observaient des chèvres.",
 e:"La légende de Kaldi et de ses chèvres surexcitées n'apparaît qu'en 1671, huit siècles après les faits supposés. Les premières traces sûres de consommation viennent des soufis du Yémen, qui s'en servaient pour tenir pendant les prières nocturnes."},
{t:'cuisine',v:0,s:"Le sucre rend les enfants hyperactifs.",
 e:"Une douzaine d'études en double aveugle n'ont rien trouvé. En revanche, les parents à qui l'on dit que leur enfant a reçu du sucre le jugent plus agité — même quand il a reçu un placebo."},
{t:'cuisine',v:0,s:"Le champagne a été inventé par dom Pérignon.",
 e:"Il passa au contraire sa vie à combattre les bulles, qu'il tenait pour un défaut faisant éclater les bouteilles. La méthode de seconde fermentation est décrite en Angleterre trente ans avant lui."},
{t:'cuisine',v:0,s:"Les épices servaient à masquer le goût de la viande avariée au Moyen Âge.",
 e:"Elles coûtaient une fortune : qui pouvait s'en offrir pouvait s'offrir de la viande fraîche. Les registres montrent une réglementation féroce des bouchers. On mettait des épices pour montrer qu'on en avait."},

/* ---------- corps et santé (sciences) ---------- */
{t:'sci',v:1,s:"L'estomac se refait une paroi tous les quelques jours.",
 e:"L'acide gastrique dissoudrait une lame de rasoir. La muqueuse se renouvelle en trois à cinq jours pour ne pas se digérer elle-même — c'est un des tissus les plus rapides du corps."},
{t:'sci',v:1,s:"Vous êtes plus grand le matin que le soir.",
 e:"Environ un centimètre. Les disques entre les vertèbres se compriment sous le poids du corps pendant la journée et se regonflent la nuit. Les astronautes en apesanteur gagnent jusqu'à cinq centimètres."},
{t:'sci',v:1,s:"Le cerveau ne ressent pas la douleur.",
 e:"Il n'a aucun récepteur de douleur. C'est ce qui permet d'opérer un patient éveillé, en lui faisant parler ou jouer de la musique pour vérifier qu'on ne touche pas une zone essentielle."},
{t:'sci',v:0,s:"Nous perdons la majeure partie de notre chaleur par la tête.",
 e:"Environ 10 %, proportionnellement à la surface exposée. Le chiffre vient d'une étude militaire où les sujets étaient habillés de partout sauf la tête. Un bonnet est utile, mais pas magique."},
{t:'sci',v:0,s:"Craquer ses doigts donne de l'arthrose.",
 e:"Un médecin a craqué les doigts d'une seule main pendant soixante ans et comparé : aucune différence. Le bruit vient d'une bulle de gaz qui s'effondre dans le liquide articulaire."},
{t:'sci',v:0,s:"Il faut attendre trois heures après le repas avant de se baigner.",
 e:"Aucune noyade documentée n'a été attribuée à la digestion. Le sang irrigue bien davantage les muscles, mais pas au point de vous couler. L'alcool, lui, est en cause dans la majorité des noyades adultes."},

/* ---------- langue ---------- */
{t:'langue',v:1,s:"Un mot a passé six ans dans un grand dictionnaire sans avoir jamais existé nulle part.",
 e:"« Dord » est né d'une fiche « D or d », pour « densité », mal recopiée dans le Webster américain. Personne ne l'a remarqué avant 1939. Le cas est si célèbre qu'on parle depuis de mots-fantômes."},
{t:'langue',v:1,s:"La langue avec le plus de locuteurs natifs n'est pas l'anglais.",
 e:"C'est le mandarin, loin devant, suivi de l'espagnol. L'anglais domine en revanche le nombre total de locuteurs, parce que la plupart de ceux qui le parlent l'ont appris."},
{t:'langue',v:1,s:"Certaines langues n'ont pas de mots pour la gauche et la droite.",
 e:"Le guugu yimithirr australien n'utilise que les points cardinaux : on a une jambe nord et une jambe sud, qui changent quand on se retourne. Ses locuteurs gardent le nord en tête en permanence, même les yeux bandés."},
{t:'langue',v:1,s:"Le mot « salaire » vient du sel.",
 e:"Les soldats romains recevaient une allocation, le salarium, liée à l'achat du sel — denrée stratégique et taxée. Le mot a survécu à l'empire, la solde est restée."},
{t:'langue',v:0,s:"Les Inuits ont cent mots pour la neige.",
 e:"Le chiffre enfle à chaque répétition depuis un article de 1911. Les langues inuit agglutinent : on construit des mots à la volée, exactement comme le français fabrique « poudreuse » ou « neige fondue »."},
{t:'langue',v:0,s:"Le mot « OK » vient du grec « ola kala ».",
 e:"Il vient d'une mode de la presse de Boston en 1839, qui abrégeait des fautes volontaires : « oll korrect ». La campagne présidentielle de Martin Van Buren, surnommé Old Kinderhook, a fait le reste."},
{t:'langue',v:0,s:"L'espéranto n'a jamais eu de locuteurs natifs.",
 e:"Il en compte plus d'un millier, enfants de couples qui se sont rencontrés dans le milieu espérantiste. Le financier George Soros est l'un d'eux."},

/* ---------- musique ---------- */
{t:'musique',v:1,s:"Le morceau le plus long du monde durera 639 ans.",
 e:"Organ²/ASLSP de John Cage est joué depuis 2001 dans une église allemande. Un changement d'accord attire des centaines de spectateurs ; le dernier a eu lieu en 2024, le prochain est prévu pour 2026."},
{t:'musique',v:1,s:"Un album de silence a rapporté de l'argent à ses auteurs.",
 e:"Le groupe américain Vulfpeck a publié en 2014 un album de dix pistes silencieuses, en demandant à ses auditeurs de le passer en boucle la nuit. Les 20 000 dollars de redevances ont financé une tournée gratuite, avant que la plateforme ne retire l'album."},
{t:'musique',v:1,s:"Le vinyle s'est revendu plus que le CD à partir de 2020.",
 e:"Pour la première fois depuis 1986, aux États-Unis. Un support qu'on avait déclaré mort trois fois a repris la tête, porté par des acheteurs qui, sondage après sondage, avouent ne pas posséder de platine."},
{t:'musique',v:0,s:"Mozart est mort pauvre et enterré dans une fosse commune anonyme.",
 e:"Il gagnait très bien sa vie et dépensait davantage. Sa sépulture suivait simplement le règlement viennois de l'époque, qui interdisait les monuments pour des raisons d'hygiène — comme pour la plupart des Viennois."},
{t:'musique',v:0,s:"Le solfège moderne a été inventé par les Grecs anciens.",
 e:"Les noms des notes viennent d'un hymne latin à saint Jean, découpé par le moine Guido d'Arezzo vers l'an mille : ut, ré, mi, fa, sol, la venaient chacun d'un début de vers."},

/* ---------- sport ---------- */
{t:'sport',v:1,s:"L'art a été une discipline olympique.",
 e:"De 1912 à 1948, on remettait des médailles en peinture, sculpture, architecture, littérature et musique. Les œuvres devaient s'inspirer du sport. Pierre de Coubertin lui-même a gagné l'or en littérature, sous pseudonyme."},
{t:'sport',v:1,s:"Un marathonien a gagné une médaille olympique en ayant fait la moitié du parcours en voiture.",
 e:"Fred Lorz, en 1904 : épuisé, il monte en voiture, l'auto tombe en panne, il termine à pied en tête. Il a reconnu la blague au moment de recevoir la couronne, devant la fille du président."},
{t:'sport',v:1,s:"Le tir à la corde a été un sport olympique.",
 e:"De 1900 à 1920. Une même équipe pouvait représenter deux pays, et en 1908 la police de Liverpool a battu les autres équipes britanniques avec ses bottes réglementaires, jugées trop lourdes par les perdants."},
{t:'sport',v:0,s:"Le football a été inventé en Angleterre.",
 e:"Les Anglais ont codifié le jeu en 1863, mais des jeux de balle au pied sont attestés en Chine dès le IIᵉ siècle avant notre ère. La FIFA reconnaît officiellement le cuju comme ancêtre."},
{t:'sport',v:0,s:"Un joueur de tennis a déjà servi à plus de 300 km/h.",
 e:"Le record homologué est de 263 km/h, par Sam Groth en 2012. Passé une certaine vitesse, la balle se déforme et perd tellement d'énergie que la limite physique n'est plus très loin."},

/* ---------- pop ---------- */
{t:'pop',v:1,s:"Le cri du T. rex de Jurassic Park est un bébé éléphant.",
 e:"Mélangé à un alligator et à un tigre. L'ingénieur du son a passé des mois dans des zoos ; le râle de la bête la plus terrifiante du cinéma est en grande partie un barrissement de bébé ralenti."},
{t:'pop',v:1,s:"Le studio Pixar a failli perdre Toy Story 2 à cause d'une commande effacée.",
 e:"Une commande de suppression lancée sur le mauvais répertoire a effacé 90 % du film, et les sauvegardes étaient défectueuses. Une employée en congé maternité avait une copie chez elle."},
{t:'pop',v:1,s:"De véritables membres de la pègre jouent dans Le Parrain.",
 e:"Lenny Montana, qui incarne Luca Brasi, était un exécuteur de la famille Colombo posté sur le tournage pour surveiller la production. Coppola l'a engagé sur place. Sa nervosité devant Marlon Brando est restée au montage."},
{t:'pop',v:0,s:"Walt Disney a fait congeler son corps.",
 e:"Il a été incinéré deux jours après sa mort en 1966, et sa tombe est publique à Glendale. La rumeur est née dans un fanzine l'année suivante, portée par le goût du personnage pour la technologie."},
{t:'pop',v:0,s:"Le personnage de Superman a toujours su voler.",
 e:"À ses débuts en 1938, il ne faisait que sauter — « plus haut qu'un immeuble d'un seul bond ». Le vol est venu des dessins animés des années 1940, parce qu'animer les sauts coûtait trop cher."},

/* ---------- techno ---------- */
{t:'techno',v:1,s:"Le premier bug informatique était un vrai insecte.",
 e:"Un papillon de nuit coincé dans un relais du Harvard Mark II, en 1947. L'équipe l'a scotché dans le journal de bord avec la mention « premier cas réel de bug trouvé ». La page est exposée au Smithsonian."},
{t:'techno',v:1,s:"Un téléphone d'aujourd'hui est plus puissant que tous les ordinateurs d'Apollo 11 réunis.",
 e:"L'ordinateur de bord tournait avec 4 kilo-octets de mémoire vive. Un téléphone courant en a un million de fois plus — et l'emploie surtout à faire défiler des images."},
{t:'techno',v:1,s:"Le premier site web est encore en ligne.",
 e:"Mis en ligne au CERN en 1991, il expliquait ce qu'était le World Wide Web à des gens qui n'en avaient jamais entendu parler. Le CERN l'a restauré à son adresse d'origine en 2013."},
{t:'techno',v:0,s:"Internet a été conçu pour survivre à une guerre nucléaire.",
 e:"Les concepteurs d'ARPANET visaient le partage de temps de calcul entre universités. L'idée nucléaire vient d'un rapport parallèle de la RAND sur les réseaux résistants, que la presse a fusionné avec le projet."},
{t:'techno',v:0,s:"La touche QWERTY a été conçue pour ralentir les dactylos.",
 e:"Elle sépare les paires de lettres les plus fréquentes pour éviter que les barres des machines à écrire se croisent — c'est-à-dire pour accélérer la frappe en évitant les blocages, pas pour la freiner."},

/* ---------- art et récits ---------- */
{t:'art',v:1,s:"La Joconde n'est devenue célèbre qu'après avoir été volée.",
 e:"En 1911, un employé du Louvre l'a sortie sous son manteau. Le cadre vide a fait la une pendant deux ans et attiré plus de visiteurs que le tableau. Kafka et Picasso sont venus voir le mur."},
{t:'art',v:1,s:"Van Gogh n'a vendu qu'un seul tableau de son vivant.",
 e:"La Vigne rouge, 400 francs, à une peintre belge. Son frère Théo, marchand d'art, ne parvenait pas à le placer. Aujourd'hui, ses toiles comptent parmi les plus chères jamais adjugées."},
{t:'art',v:1,s:"Les statues grecques étaient peintes de couleurs vives.",
 e:"Les ultraviolets révèlent les pigments encore présents dans la pierre : rouges, bleus, dorures. Le marbre blanc que nous admirons est un accident du temps, que la Renaissance a pris pour un idéal esthétique."},
{t:'art',v:0,s:"Van Gogh s'est coupé l'oreille entière.",
 e:"Le rapport du médecin décrit le lobe et un peu plus. Le peintre a ensuite posé pour deux autoportraits avec un pansement — sur l'oreille droite, alors que c'est la gauche qui était atteinte : il peignait devant un miroir."},
{t:'litt',v:1,s:"Un roman entier a été écrit sans la lettre e.",
 e:"La Disparition de Georges Perec, trois cents pages en 1969. Plusieurs critiques ne l'ont pas remarqué. Le traducteur anglais a fait de même, et l'espagnol a supprimé le a, plus fréquent dans sa langue."},
{t:'litt',v:1,s:"Le mot « robot » vient d'une pièce de théâtre tchèque.",
 e:"R.U.R., de Karel Čapek, en 1920. Le mot vient de robota, la corvée servile. La pièce se termine par une révolte des robots — le thème est né en même temps que le mot."},
{t:'litt',v:0,s:"Shakespeare a inventé plus de mille mots de la langue anglaise.",
 e:"On lui attribue les premières attestations écrites, ce qui n'est pas la même chose. La numérisation des textes de son époque a fait fondre la liste : il écrivait comme on parlait autour de lui."},
{t:'litt',v:0,s:"Les frères Grimm ont écrit leurs contes pour les enfants.",
 e:"Ils collectaient des récits populaires pour des philologues, avec des versions bien plus dures. Les éditions successives ont adouci les textes au fil du succès en librairie — c'est le public qui a fait des contes une littérature enfantine."},
];
