/* =========================================================
   NO WAY! — banque d'anecdotes vraies et fausses
   Une seule banque alimente trois épreuves :
     · Le Détecteur  — vrai ou n'importe quoi ?
     · Le Duel       — une vraie contre une fausse, choisis
     · Lequel ment ? — trois vraies, une inventée
   Structure : {t, s, v, e}
     t = thème (mêmes clés que Q) · s = l'affirmation
     v = 1 si elle est vraie, 0 si elle est inventée
     e = l'explication, révélée après coup — et qui doit valoir
         plus que l'affirmation elle-même
   Les fausses ne sont jamais absurdes : ce sont des croyances
   répandues ou des inventions crédibles. C'est tout l'intérêt.
   Chargé avant index.html ; expose la globale `ANECDOTES`.
   ========================================================= */
const ANECDOTES=[

/* ---------- animaux ---------- */
{t:'animaux',v:1,s:"Les pieuvres ont trois cœurs.",
 e:"Deux poussent le sang vers les branchies, le troisième vers le reste du corps. Ce dernier s'arrête quand la pieuvre nage — d'où sa préférence marquée pour la marche sur le fond, moins épuisante."},
{t:'animaux',v:1,s:"Les flamants roses naissent gris.",
 e:"Le rose vient des crustacés qu'ils filtrent. En captivité, sans supplément, ils pâlissent. Un flamant terne est un flamant mal nourri — les zoos surveillent la couleur comme un bulletin de santé."},
{t:'animaux',v:1,s:"Les wombats font des crottes cubiques.",
 e:"Leur intestin a des parois d'élasticité inégale qui moulent les cubes. Le wombat les empile pour marquer son territoire : une crotte ronde roulerait, une crotte cubique reste où on l'a posée."},
{t:'animaux',v:1,s:"Les hippopotames fabriquent leur propre crème solaire.",
 e:"Ils sécrètent un liquide rouge, longtemps pris pour du sang, qui filtre les ultraviolets et fait aussi antibiotique. Leurs blessures s'infectent remarquablement peu pour un animal qui passe ses journées dans la vase."},
{t:'animaux',v:1,s:"Les koalas ont des empreintes digitales presque impossibles à distinguer des nôtres.",
 e:"Elles sont apparues séparément, des millions d'années après notre dernier ancêtre commun. Des experts en criminalistique ont admis qu'une empreinte de koala sur une scène de crime les tromperait."},
{t:'animaux',v:1,s:"Les dauphins se donnent des noms.",
 e:"Chacun invente jeune un sifflement signature et le garde à vie. Les autres l'imitent pour l'appeler à distance — et un dauphin répond au sien même diffusé par un haut-parleur."},
{t:'animaux',v:1,s:"Un tardigrade a survécu à un séjour dans le vide spatial.",
 e:"En 2007, des tardigrades exposés dix jours au vide et aux rayons cosmiques sont revenus vivants, et certains ont pondu. Ils se déshydratent totalement et suspendent leur métabolisme en attendant des jours meilleurs."},
{t:'animaux',v:1,s:"Les manchots offrent des cailloux pour séduire.",
 e:"Chez les manchots Adélie, le mâle cherche le plus beau galet du secteur et le dépose aux pieds de la femelle. Les bons cailloux étant rares, le vol entre voisins est constant."},
{t:'animaux',v:1,s:"La crevette-mante frappe si vite que l'eau bout autour de son poing.",
 e:"Son coup atteint la vitesse d'une balle de calibre 22. La dépression créée derrière son appendice fait bouillir l'eau une fraction de seconde, et l'implosion émet un éclair de lumière."},
{t:'animaux',v:1,s:"Les vaches ont des amies préférées.",
 e:"Séparez deux vaches liées et leur rythme cardiaque grimpe, leur production de lait chute. Remettez-les ensemble, tout rentre dans l'ordre. Certains élevages composent désormais les groupes selon ces affinités."},
{t:'animaux',v:1,s:"Un escargot peut dormir trois ans d'affilée.",
 e:"Face à la sécheresse, il se scelle derrière un opercule de mucus durci et attend. Des spécimens collés à des étiquettes de musée se sont réveillés après plusieurs années de vitrine."},
{t:'animaux',v:1,s:"Le rat-taupe nu ne développe pratiquement jamais de cancer.",
 e:"Ses cellules cessent de se diviser dès qu'elles se touchent, grâce à une molécule que nous ne fabriquons pas. Il vit trente ans, dix fois plus qu'une souris de taille comparable."},
{t:'animaux',v:0,s:"Les autruches enfouissent la tête dans le sable quand elles ont peur.",
 e:"Elles ne l'ont jamais fait. Elles retournent leurs œufs enfouis avec le bec, ce qui de loin en donne l'illusion. Face au danger, une autruche court à 70 km/h ou frappe — un coup de patte peut tuer un lion."},
{t:'animaux',v:0,s:"Les poissons rouges ont une mémoire de trois secondes.",
 e:"Ils retiennent plusieurs mois. On leur a appris à pousser un levier à une heure fixe pour obtenir leur nourriture, et à reconnaître les visages humains. Le mythe arrangeait surtout les vendeurs de bocaux."},
{t:'animaux',v:0,s:"Un chameau stocke de l'eau dans ses bosses.",
 e:"Les bosses sont de la graisse, pas de l'eau. C'est une réserve d'énergie rangée en un seul endroit pour ne pas isoler tout le corps sous la chaleur. L'eau, il la garde dans son sang et ses tissus."},
{t:'animaux',v:0,s:"Le caméléon change de couleur pour se camoufler.",
 e:"Il change surtout d'humeur et de température. Les couleurs vives signalent l'agressivité ou la séduction ; un caméléon calme reste vert parce que le vert est sa couleur de repos, pas sa cachette."},
{t:'animaux',v:0,s:"Les taureaux chargent parce qu'ils voient du rouge.",
 e:"Ils ne distinguent pas le rouge. C'est le mouvement de la cape qui les déclenche — un torero agitant un drap blanc obtiendrait le même résultat. La couleur est là pour le public, et pour masquer le sang."},
{t:'animaux',v:0,s:"Les lemmings se jettent des falaises par vagues entières.",
 e:"Une équipe de tournage les a poussés depuis un plateau tournant en 1958 pour filmer la scène. Les lemmings migrent en masse et certains se noient en traversant l'eau ; personne ne se suicide."},
{t:'animaux',v:0,s:"Un ver de terre coupé en deux donne deux vers.",
 e:"La moitié avant peut refaire une queue si la coupe est assez loin. La moitié arrière, elle, n'a ni bouche ni cerveau : elle meurt. On obtient un ver mutilé et un cadavre, pas des jumeaux."},
{t:'animaux',v:0,s:"Les chauves-souris sont aveugles.",
 e:"Toutes voient, et les grandes roussettes ont une vision excellente. L'écholocation sert la nuit, quand la vue ne suffit plus — c'est un instrument de plus, pas un remplacement."},
{t:'animaux',v:0,s:"Les mille-pattes ont bien mille pattes.",
 e:"La plupart en ont entre trente et quatre cents. Il a fallu attendre 2021 pour qu'une espèce australienne dépasse enfin le millier, avec 1 306 pattes — et elle vit à soixante mètres sous terre."},

/* ---------- espace ---------- */
{t:'espace',v:1,s:"Un jour sur Vénus dure plus longtemps qu'une année vénusienne.",
 e:"Vénus tourne sur elle-même en 243 jours terrestres et fait le tour du Soleil en 225. Elle tourne aussi à l'envers : là-bas, le Soleil se lève à l'ouest, deux fois par année."},
{t:'espace',v:1,s:"Saturne flotterait sur l'eau.",
 e:"Sa densité moyenne est inférieure à celle de l'eau — il faudrait juste une baignoire de 120 000 kilomètres. La planète est si peu dense qu'elle s'aplatit visiblement sous sa propre rotation."},
{t:'espace',v:1,s:"Il y a plus d'arbres sur Terre que d'étoiles dans la Voie lactée.",
 e:"Environ 3 000 milliards d'arbres, contre 100 à 400 milliards d'étoiles. Le comptage des arbres date de 2015 et a multiplié par huit l'estimation précédente — on connaissait mal notre propre planète."},
{t:'espace',v:1,s:"Le Soleil représente 99,8 % de la masse du système solaire.",
 e:"Tout le reste — les huit planètes, les lunes, les astéroïdes, les comètes — tient dans les 0,2 % restants. Et Jupiter à lui seul en occupe les deux tiers."},
{t:'espace',v:1,s:"Les astronautes décrivent l'odeur de l'espace comme celle de la poudre à canon.",
 e:"L'odeur s'accroche aux combinaisons rentrées dans le sas. Métal chaud, viande grillée, soudure : ce sont probablement des atomes d'oxygène qui se recombinent violemment au contact de l'air de la station."},
{t:'espace',v:1,s:"Une cuillère à café d'étoile à neutrons pèserait des milliards de tonnes.",
 e:"La matière y est comprimée au point que les électrons sont enfoncés dans les noyaux. Un dé à coudre de cette étoile pèse autant que toute l'humanité réunie."},
{t:'espace',v:1,s:"Il existe un nuage d'alcool au centre de la Galaxie.",
 e:"Sagittarius B2 contient des milliards de kilomètres cubes d'alcool éthylique, mêlé à des composés qui sentent la framboise et le rhum. Imbuvable : il est mille milliards de fois plus dilué que l'air."},
{t:'espace',v:1,s:"Les empreintes de pas laissées sur la Lune tiendront des millions d'années.",
 e:"Sans vent ni pluie, rien ne les efface. Seuls les micrométéorites les grignotent, très lentement. La trace de Neil Armstrong sera encore lisible quand notre espèce aura disparu."},
{t:'espace',v:0,s:"La Grande Muraille de Chine est visible à l'œil nu depuis la Lune.",
 e:"Elle est déjà difficile à repérer depuis l'orbite basse, à 400 km. Depuis la Lune, mille fois plus loin, il faudrait distinguer un cheveu à deux kilomètres. Aucun astronaute d'Apollo ne l'a vue."},
{t:'espace',v:0,s:"Sans combinaison, le corps humain explose dans le vide.",
 e:"La peau tient très bien. On gonfle, on perd connaissance en quinze secondes, l'eau des muqueuses bout. Un technicien de la NASA a survécu à une décompression accidentelle en 1966 — il se souvient d'avoir senti sa salive bouillir."},
{t:'espace',v:0,s:"La face cachée de la Lune est plongée dans une nuit permanente.",
 e:"Elle reçoit autant de soleil que l'autre. Elle est cachée, pas sombre : la Lune tourne sur elle-même exactement au rythme de son orbite, si bien qu'elle nous montre toujours le même côté."},
{t:'espace',v:0,s:"Mercure est la planète la plus chaude du système solaire.",
 e:"C'est Vénus, avec 465 °C constants, contre 430 °C au maximum sur Mercure — qui descend à −180 °C la nuit. Vénus est plus loin du Soleil mais son atmosphère de gaz carbonique ne laisse plus rien repartir."},
{t:'espace',v:0,s:"Il n'y a pas de gravité dans la Station spatiale internationale.",
 e:"Il y en a presque 90 % de celle du sol. Les astronautes ne flottent pas faute de gravité : ils tombent en permanence vers la Terre, et la station tombe avec eux, en manquant le sol à chaque tour."},
{t:'espace',v:0,s:"L'étoile Polaire est l'étoile la plus brillante du ciel.",
 e:"Elle n'est même pas dans les quarante premières. C'est Sirius. La Polaire ne doit sa réputation qu'à sa position : elle est presque pile dans l'axe de rotation de la Terre, donc immobile."},

/* ---------- géographie ---------- */
{t:'geo',v:1,s:"Une ville suédoise entière a été déplacée de plusieurs kilomètres.",
 e:"Kiruna s'effondrait au-dessus de sa propre mine de fer. Depuis 2014, on transporte les bâtiments un par un, dont l'église en bois de cent ans, vers un nouveau centre à trois kilomètres."},
{t:'geo',v:1,s:"La Russie et les États-Unis sont séparés par moins de quatre kilomètres.",
 e:"Entre la Grande et la Petite Diomède, dans le détroit de Béring. En hiver, la glace les relie. Elles sont aussi de part et d'autre de la ligne de changement de date : d'une île à l'autre, on saute un jour."},
{t:'geo',v:1,s:"Des maisons sont coupées en deux par une frontière entre deux pays, et la porte d'entrée décide du pays.",
 e:"Baarle, à la frontière belgo-néerlandaise, compte trente enclaves imbriquées et une frontière qui traverse des salons. Des familles ont déplacé leur porte d'entrée de quelques mètres pour changer de fiscalité."},
{t:'geo',v:1,s:"Le Sahara a été vert, avec des lacs et des hippopotames.",
 e:"Il y a 6 000 ans à peine. Les gravures rupestres du Tassili montrent des troupeaux et des nageurs. Un léger basculement de l'axe terrestre a suffi à couper les pluies — et le désert s'est installé en quelques siècles."},
{t:'geo',v:1,s:"D'est en ouest, l'Australie est plus large que le diamètre de la Lune.",
 e:"4 000 kilomètres d'est en ouest, contre 3 475 de diamètre lunaire. Ce qui n'empêche pas la Lune d'avoir une surface totale plus grande — elle est ronde dans toutes les directions."},
{t:'geo',v:1,s:"Il n'y a pas une seule rivière en Arabie saoudite.",
 e:"Pas un cours d'eau permanent sur deux millions de kilomètres carrés. Le pays vit du dessalement de la mer et de nappes fossiles vieilles de dizaines de milliers d'années, qu'on ne recharge plus."},
{t:'geo',v:1,s:"La mer Caspienne est le plus grand lac du monde.",
 e:"Salée, immense, sans issue vers l'océan : elle a tous les attributs d'une mer sauf la connexion. Son statut juridique — mer ou lac — a occupé cinq pays riverains pendant vingt ans, pétrole oblige."},
{t:'geo',v:1,s:"Le point le plus éloigné de toute terre émergée porte un nom.",
 e:"Le point Nemo, dans le Pacifique Sud. La terre la plus proche est à 2 700 kilomètres — les humains les plus proches sont souvent les astronautes en orbite. Les agences spatiales y font tomber leurs satellites."},
{t:'geo',v:0,s:"Le mont Everest est le point de la Terre le plus éloigné du centre du globe.",
 e:"C'est le Chimborazo, en Équateur. La Terre est renflée à l'équateur : ce volcan de 6 263 mètres part de plus haut et dépasse l'Everest de deux kilomètres en distance au centre."},
{t:'geo',v:0,s:"Le désert du Sahara est le plus grand désert du monde.",
 e:"C'est l'Antarctique. Un désert se définit par ses précipitations, pas par le sable : il tombe moins d'eau au pôle Sud que dans le Sahara, qui n'arrive qu'en deuxième position."},
{t:'geo',v:0,s:"Istanbul est la capitale de la Turquie.",
 e:"C'est Ankara depuis 1923. Atatürk a délibérément choisi une ville de l'intérieur, loin des convoitises et du passé ottoman. Istanbul reste la plus peuplée, ce qui entretient la confusion."},
{t:'geo',v:0,s:"L'Amazone est le plus long fleuve du monde.",
 e:"Le Nil garde le titre de peu, et le débat n'est pas clos — tout dépend de la source retenue. L'Amazone est en revanche sans rivale pour le débit : elle déverse plus d'eau que les six suivants réunis."},
{t:'geo',v:0,s:"Les continents dérivent d'environ un mètre par an.",
 e:"Plutôt deux à dix centimètres, la vitesse à laquelle poussent les ongles. Sur des centaines de millions d'années, cela suffit à ouvrir un océan — mais le GPS ne détecte le mouvement qu'après plusieurs années."},

/* ---------- histoire ---------- */
{t:'histo',v:1,s:"Cléopâtre a vécu plus près de nous que de la construction des pyramides.",
 e:"Les grandes pyramides datent de 2560 avant notre ère, Cléopâtre est morte en 30. Deux mille cinq cents ans la séparent des pyramides, deux mille de nous. Elles étaient déjà pour elle des antiquités."},
{t:'histo',v:1,s:"L'université d'Oxford est plus ancienne que l'empire aztèque.",
 e:"On y enseignait dès 1096. Tenochtitlan a été fondée en 1325. Quand les Aztèques posaient la première pierre de leur capitale, Oxford avait déjà deux siècles de querelles universitaires derrière elle."},
{t:'histo',v:1,s:"La guerre la plus courte de l'histoire a duré trente-huit minutes.",
 e:"Entre le Royaume-Uni et Zanzibar, en 1896. Le bombardement a commencé à 9 h 02 ; le palais s'est effondré et le drapeau est tombé à 9 h 40. Zanzibar a ensuite dû payer la facture des obus."},
{t:'histo',v:1,s:"Un roi de France est mort d'un coup de porte.",
 e:"Charles VIII, en 1498, s'est cogné le front contre le linteau d'une porte basse en allant voir une partie de jeu de paume. Il a suivi la partie, s'est effondré quelques heures plus tard, et n'a jamais repris connaissance."},
{t:'histo',v:1,s:"Le fax a été inventé avant le téléphone.",
 e:"Alexander Bain dépose le brevet du télécopieur en 1843, trente-trois ans avant le téléphone de Bell. Sa machine balayait un texte en relief avec un stylet et reproduisait le tracé à l'autre bout d'un fil."},
{t:'histo',v:1,s:"Napoléon a été attaqué par des lapins.",
 e:"Une chasse organisée en son honneur avait fait acheter des lapins d'élevage au lieu de lapins sauvages. Lâchés, les animaux ont pris l'Empereur pour le nourrisseur et ont chargé en masse. Il a battu en retraite jusqu'à sa voiture."},
{t:'histo',v:1,s:"Le dernier soldat japonais s'est rendu vingt-neuf ans après la guerre.",
 e:"Hiroo Onoda tenait la jungle philippine depuis 1945, convaincu que la reddition était une ruse. Il n'a déposé les armes qu'en 1974, quand son ancien commandant a fait le déplacement pour lui en donner l'ordre en personne."},
{t:'histo',v:1,s:"Les pyramides étaient blanches et brillantes.",
 e:"Un revêtement de calcaire poli les faisait luire au soleil, visible à des kilomètres. Un tremblement de terre l'a descellé au XIVᵉ siècle et les habitants du Caire l'ont récupéré pour bâtir mosquées et remparts."},
{t:'histo',v:0,s:"Les Vikings portaient des casques à cornes.",
 e:"Aucun casque à cornes n'a jamais été retrouvé dans une tombe viking. Le costumier d'un opéra de Wagner, en 1876, en a habillé ses chanteurs — et l'image a tenu bon depuis."},
{t:'histo',v:0,s:"Marie-Antoinette a lancé : « Qu'ils mangent de la brioche ! »",
 e:"La phrase circulait déjà dans les Confessions de Rousseau quand elle avait neuf ans et vivait encore à Vienne. On l'a attribuée à plusieurs princesses avant elle ; la Révolution lui a simplement trouvé la meilleure destinataire."},
{t:'histo',v:0,s:"Au Moyen Âge, on croyait la Terre plate.",
 e:"La rotondité était admise depuis l'Antiquité grecque et n'a jamais été sérieusement contestée par les savants médiévaux. Le mythe date du XIXᵉ siècle, forgé pour opposer science et religion."},
{t:'histo',v:0,s:"Einstein était mauvais en mathématiques à l'école.",
 e:"Il maîtrisait le calcul différentiel à quinze ans. La légende vient d'un système de notation suisse inversé : ses 6, les meilleures notes possibles, ont été lus comme des notes catastrophiques."},
{t:'histo',v:0,s:"Le Grand Incendie de Londres a été arrêté par la pluie.",
 e:"C'est la démolition volontaire de rangées entières de maisons qui a coupé la propagation, avec l'aide d'une baisse du vent. La pluie n'est arrivée qu'après. Le feu a détruit 13 000 maisons et fait très peu de morts."},
{t:'histo',v:0,s:"Les gladiateurs mouraient presque à chaque combat.",
 e:"Un gladiateur coûtait des années de formation : le laisser mourir ruinait son propriétaire. Les estimations donnent une mort pour cinq à dix combats, et beaucoup se retiraient vivants après une carrière complète."},

/* ---------- sciences ---------- */
{t:'sci',v:0,s:"Le verre est un liquide très lent : les vitraux médiévaux sont plus épais en bas parce qu'ils ont coulé.",
 e:"Les souffleurs posaient simplement le côté épais vers le bas, pour la stabilité. À température ambiante, le verre mettrait plus longtemps que l'âge de l'univers à couler d'une épaisseur visible. C'est un solide, désordonné mais solide."},
{t:'sci',v:1,s:"L'eau chaude peut geler plus vite que l'eau froide.",
 e:"L'effet Mpemba, redécouvert en 1963 par un lycéen tanzanien que ses professeurs ont ridiculisé. Les explications se disputent encore — évaporation, convection, liaisons hydrogène — mais l'effet s'observe."},
{t:'sci',v:1,s:"Il y a plus de bactéries dans votre bouche que d'humains sur Terre.",
 e:"Une bouche en héberge des dizaines de milliards, réparties en 700 espèces. Un simple baiser de dix secondes en transfère 80 millions d'un partenaire à l'autre."},
{t:'sci',v:1,s:"Le miel retrouvé dans des tombes égyptiennes était encore comestible.",
 e:"Trop sucré et trop acide pour les bactéries, presque sans eau : le miel ne se gâte pratiquement pas. Des pots de trois mille ans ouverts par des archéologues contenaient un miel parfaitement sain."},
{t:'sci',v:1,s:"Un éclair est cinq fois plus chaud que la surface du Soleil.",
 e:"Environ 30 000 °C, contre 5 500 pour le Soleil. La chaleur dilate l'air si brutalement qu'elle crée une onde de choc : le tonnerre n'est rien d'autre que le bruit de l'air qui se referme."},
{t:'sci',v:1,s:"Votre corps émet de la lumière, trop faible pour être vue.",
 e:"Une bioluminescence mille fois sous notre seuil de perception, mesurée par des caméras japonaises en 2009. Elle suit un cycle : le visage brille le plus en fin d'après-midi."},
{t:'sci',v:1,s:"L'hélium était connu sur le Soleil avant d'être trouvé sur Terre.",
 e:"Repéré en 1868 dans le spectre solaire pendant une éclipse, il portait déjà le nom du Soleil quand on l'a enfin isolé sur Terre, vingt-sept ans plus tard, dans un minerai d'uranium."},
{t:'sci',v:1,s:"Le matériau naturel le plus résistant à la traction jamais mesuré est une dent de coquillage.",
 e:"La dent de patelle bat les meilleures fibres de carbone. Ses nanofibres minérales lui servent à râper la roche pour en décoller les algues, sans s'user — un outil de chantier sur un animal de trois centimètres."},
{t:'sci',v:0,s:"On n'utilise que 10 % de notre cerveau.",
 e:"L'imagerie montre toutes les zones actives sur vingt-quatre heures. Un organe qui consomme 20 % de notre énergie pour ne rien faire à 90 % n'aurait pas survécu à l'évolution. Aucune lésion cérébrale n'est indolore."},
{t:'sci',v:0,s:"Les couleurs de la langue correspondent à des zones du goût.",
 e:"La fameuse carte vient d'une traduction ratée d'une thèse allemande de 1901. Chaque papille détecte les cinq saveurs. Posez du sucre n'importe où sur la langue : c'est sucré partout."},
{t:'sci',v:0,s:"Les cheveux et les ongles continuent de pousser après la mort.",
 e:"La peau se rétracte en se déshydratant et dégage ce qui était déjà sorti. Rien ne pousse : les cellules mortes ne se divisent pas. L'illusion est assez forte pour avoir nourri des siècles d'histoires de vampires."},
{t:'sci',v:0,s:"Un centime lâché du haut d'une tour peut tuer un passant.",
 e:"Sa forme le fait flotter et osciller : il plafonne autour de 40 km/h. On le reçoit comme une pichenette. Un stylo, plus lourd et mieux profilé, serait autrement inquiétant."},
{t:'sci',v:0,s:"Le sang est bleu dans les veines et devient rouge au contact de l'air.",
 e:"Il est rouge partout, plus sombre quand il a rendu son oxygène. Les veines paraissent bleues parce que la peau diffuse davantage les courtes longueurs d'onde — c'est un effet d'optique, pas de chimie."},
{t:'sci',v:0,s:"La foudre ne tombe jamais deux fois au même endroit.",
 e:"L'Empire State Building la reçoit une vingtaine de fois par an. Un point haut et conducteur est exactement ce que cherche la décharge : loin de l'éviter, elle y revient."},

/* ---------- WTF ---------- */
{t:'wtf',v:1,s:"Un homme a survécu à deux bombes atomiques.",
 e:"Tsutomu Yamaguchi était à Hiroshima en voyage d'affaires, blessé mais debout. Il est rentré chez lui à Nagasaki, où la seconde bombe est tombée trois jours plus tard. Il est mort en 2010, à 93 ans."},
{t:'wtf',v:1,s:"Un avion de ligne est tombé en panne sèche en plein vol à cause d'une conversion ratée entre livres et kilos.",
 e:"Le vol 143 d'Air Canada, en 1983, est tombé en panne sèche à 12 000 mètres. Le commandant, pilote de planeur, a posé l'appareil sur une ancienne piste militaire transformée en circuit automobile, en plein week-end de course."},
{t:'wtf',v:1,s:"Il existe une ville où l'on n'a plus le droit d'être enterré.",
 e:"Longyearbyen, au Svalbard. Le permafrost empêche les corps de se décomposer et conserve les virus intacts — on y a retrouvé la grippe de 1918 encore active. Les malades en fin de vie sont évacués vers le continent."},
{t:'wtf',v:1,s:"La Nouvelle-Zélande a reconnu un fleuve comme une personne.",
 e:"Le Whanganui a obtenu en 2017 les droits d'une personne morale, après cent quarante ans de démarches maories. Deux gardiens parlent en son nom, et on peut porter plainte au nom du fleuve."},
{t:'wtf',v:1,s:"Un homme a détourné un avion, sauté en parachute avec la rançon, et n'a jamais été retrouvé.",
 e:"D. B. Cooper, en 1971, avec 200 000 dollars. Le FBI a fermé le dossier en 2016 sans identification. Une partie des billets a refait surface sur une plage en 1980, ce qui n'a fait qu'épaissir le mystère."},
{t:'wtf',v:1,s:"Un incendie de mine brûle sous une ville américaine depuis 1962.",
 e:"À Centralia, en Pennsylvanie, un feu de veine de charbon a chassé mille habitants. Il reste assez de charbon pour deux cent cinquante ans de combustion. Le code postal a été supprimé en 2002."},
{t:'wtf',v:1,s:"Un pigeon a été décoré d'une médaille militaire.",
 e:"Cher Ami a livré son message en 1918 avec une balle dans la poitrine et une patte arrachée, sauvant près de deux cents soldats encerclés. Il est empaillé au Smithsonian, décoré de la Croix de guerre."},
{t:'wtf',v:1,s:"Le pays le plus plat du monde n'a aucun point à plus de trois mètres d'altitude.",
 e:"Les Maldives culminent à 2,4 mètres. Le gouvernement a tenu un conseil des ministres sous l'eau, en scaphandre, pour signer un appel sur le climat — et met de l'argent de côté pour acheter des terres ailleurs."},
{t:'wtf',v:0,s:"Un homme a vendu la tour Eiffel deux fois à des ferrailleurs.",
 e:"Victor Lustig l'a bien vendue en 1925, mais une seule fois. Sa victime, morte de honte, n'a jamais porté plainte — c'est pourquoi il a pu tenter un second coup, qui a échoué avant la vente."},
{t:'wtf',v:0,s:"Il pleut des poissons chaque année dans un village du Honduras.",
 e:"La Lluvia de Peces existe, mais aucune trompe d'eau n'a jamais été filmée en train de les larguer. Les biologistes penchent pour des poissons souterrains chassés à la surface par les crues — moins spectaculaire, plus solide."},
{t:'wtf',v:0,s:"Une loi anglaise autorise encore à tirer sur un Écossais à l'arc dans York.",
 e:"On cite cette loi partout ; elle n'existe dans aucun recueil. Le Parlement britannique a publiquement démenti. Les fausses lois pittoresques prospèrent parce que personne ne va vérifier les archives."},
{t:'wtf',v:0,s:"Un homme a passé toute sa vie dans un aéroport parce qu'il aimait ça.",
 e:"Mehran Karimi Nasseri a vécu dix-huit ans à Roissy, mais par blocage administratif, pas par goût. Quand ses papiers ont enfin été régularisés, il est parti. Il est revenu y mourir en 2022."},
{t:'wtf',v:0,s:"La NASA a dépensé des millions pour un stylo qui écrit dans l'espace, les Russes ont pris un crayon.",
 e:"L'histoire est fausse. Une entreprise privée a financé le stylo seule et l'a vendu aux deux agences. Le crayon était d'ailleurs proscrit : la mine casse, et des copeaux de graphite qui flottent dans une cabine à oxygène pur, c'est un incendie."},

/* ---------- cuisine ---------- */
{t:'cuisine',v:1,s:"Le ketchup était vendu comme médicament.",
 e:"Un médecin de l'Ohio l'a breveté en 1834 en pilules contre les troubles digestifs, en s'appuyant sur les vertus supposées de la tomate. Les contrefaçons ont ruiné le marché en dix ans."},
{t:'cuisine',v:1,s:"Les carottes étaient violettes avant d'être orange.",
 e:"Violettes, jaunes ou blanches en Asie centrale. L'orange s'est imposé aux Pays-Bas au XVIIᵉ siècle — sélection patiente d'une variété rare, dont la couleur tombait bien pour la maison d'Orange."},
{t:'cuisine',v:1,s:"La banane est techniquement une baie, la fraise non.",
 e:"Une baie vient d'un seul ovaire et contient ses graines : la banane coche tout. La fraise porte les siennes dehors — les petits points sont les vrais fruits, et la chair rouge n'est qu'un réceptacle gonflé."},
{t:'cuisine',v:1,s:"Le wasabi servi dans presque tous les restaurants n'est pas du wasabi.",
 e:"C'est du raifort coloré. La vraie plante pousse trois ans dans l'eau froide de montagne, se râpe à la peau de requin et perd son piquant en quinze minutes — invendable en tube."},
{t:'cuisine',v:1,s:"Le chocolat blanc ne contient pas de cacao.",
 e:"Il ne garde que le beurre de cacao, sans les solides qui donnent la couleur et le goût. C'est pourquoi plusieurs pays ont longtemps refusé de l'appeler chocolat."},
{t:'cuisine',v:1,s:"Les amandes amères contiennent du cyanure.",
 e:"Une cinquantaine suffirait à tuer un adulte. La variété douce que nous mangeons a perdu le gène responsable — une mutation unique, repérée et propagée par les cultivateurs il y a des millénaires."},
{t:'cuisine',v:1,s:"Le safran vaut plus cher que l'or au gramme, certaines années.",
 e:"Il faut 150 000 fleurs cueillies à la main, à l'aube, pour un kilo — et seulement trois stigmates par fleur. Tout se fait en deux semaines par an, ce qui interdit toute mécanisation."},
{t:'cuisine',v:0,s:"Les tomates sont des légumes.",
 e:"Botaniquement, ce sont des fruits. Mais la Cour suprême des États-Unis les a déclarées légumes en 1893 — non par science, mais parce que les légumes étaient taxés à l'importation et pas les fruits."},
{t:'cuisine',v:0,s:"Le café a été découvert par des moines qui observaient des chèvres.",
 e:"La légende de Kaldi et de ses chèvres surexcitées n'apparaît qu'en 1671, huit siècles après les faits supposés. Les premières traces sûres de consommation viennent des soufis du Yémen, qui s'en servaient pour tenir pendant les prières nocturnes."},
{t:'cuisine',v:0,s:"Le sucre rend les enfants hyperactifs.",
 e:"Une douzaine d'études en double aveugle n'ont rien trouvé. En revanche, les parents à qui l'on dit que leur enfant a reçu du sucre le jugent plus agité — même quand il a reçu un placebo."},
{t:'cuisine',v:0,s:"Le champagne a été inventé par dom Pérignon.",
 e:"Il passa au contraire sa vie à combattre les bulles, qu'il tenait pour un défaut faisant éclater les bouteilles. La méthode de seconde fermentation est décrite en Angleterre trente ans avant lui."},
{t:'cuisine',v:0,s:"Les épices servaient à masquer le goût de la viande avariée au Moyen Âge.",
 e:"Elles coûtaient une fortune : qui pouvait s'en offrir pouvait s'offrir de la viande fraîche. Les registres montrent une réglementation féroce des bouchers. On mettait des épices pour montrer qu'on en avait."},

/* ---------- corps et santé (sciences) ---------- */
{t:'sci',v:1,s:"L'estomac se refait une paroi tous les quelques jours.",
 e:"L'acide gastrique dissoudrait une lame de rasoir. La muqueuse se renouvelle en trois à cinq jours pour ne pas se digérer elle-même — c'est un des tissus les plus rapides du corps."},
{t:'sci',v:1,s:"Vous êtes plus grand le matin que le soir.",
 e:"Environ un centimètre. Les disques entre les vertèbres se compriment sous le poids du corps pendant la journée et se regonflent la nuit. Les astronautes en apesanteur gagnent jusqu'à cinq centimètres."},
{t:'sci',v:1,s:"Le cerveau ne ressent pas la douleur.",
 e:"Il n'a aucun récepteur de douleur. C'est ce qui permet d'opérer un patient éveillé, en lui faisant parler ou jouer de la musique pour vérifier qu'on ne touche pas une zone essentielle."},
{t:'sci',v:0,s:"Nous perdons la majeure partie de notre chaleur par la tête.",
 e:"Environ 10 %, proportionnellement à la surface exposée. Le chiffre vient d'une étude militaire où les sujets étaient habillés de partout sauf la tête. Un bonnet est utile, mais pas magique."},
{t:'sci',v:0,s:"Craquer ses doigts donne de l'arthrose.",
 e:"Un médecin a craqué les doigts d'une seule main pendant soixante ans et comparé : aucune différence. Le bruit vient d'une bulle de gaz qui s'effondre dans le liquide articulaire."},
{t:'sci',v:0,s:"Il faut attendre trois heures après le repas avant de se baigner.",
 e:"Aucune noyade documentée n'a été attribuée à la digestion. Le sang irrigue bien davantage les muscles, mais pas au point de vous couler. L'alcool, lui, est en cause dans la majorité des noyades adultes."},

/* ---------- langue ---------- */
{t:'langue',v:1,s:"Un mot a passé six ans dans un grand dictionnaire sans avoir jamais existé nulle part.",
 e:"« Dord » est né d'une fiche « D or d », pour « densité », mal recopiée dans le Webster américain. Personne ne l'a remarqué avant 1939. Le cas est si célèbre qu'on parle depuis de mots-fantômes."},
{t:'langue',v:1,s:"La langue avec le plus de locuteurs natifs n'est pas l'anglais.",
 e:"C'est le mandarin, loin devant, suivi de l'espagnol. L'anglais domine en revanche le nombre total de locuteurs, parce que la plupart de ceux qui le parlent l'ont appris."},
{t:'langue',v:1,s:"Certaines langues n'ont pas de mots pour la gauche et la droite.",
 e:"Le guugu yimithirr australien n'utilise que les points cardinaux : on a une jambe nord et une jambe sud, qui changent quand on se retourne. Ses locuteurs gardent le nord en tête en permanence, même les yeux bandés."},
{t:'langue',v:1,s:"Le mot « salaire » vient du sel.",
 e:"Les soldats romains recevaient une allocation, le salarium, liée à l'achat du sel — denrée stratégique et taxée. Le mot a survécu à l'empire, la solde est restée."},
{t:'langue',v:0,s:"Les Inuits ont cent mots pour la neige.",
 e:"Le chiffre enfle à chaque répétition depuis un article de 1911. Les langues inuit agglutinent : on construit des mots à la volée, exactement comme le français fabrique « poudreuse » ou « neige fondue »."},
{t:'langue',v:0,s:"Le mot « OK » vient du grec « ola kala ».",
 e:"Il vient d'une mode de la presse de Boston en 1839, qui abrégeait des fautes volontaires : « oll korrect ». La campagne présidentielle de Martin Van Buren, surnommé Old Kinderhook, a fait le reste."},
{t:'langue',v:0,s:"L'espéranto n'a jamais eu de locuteurs natifs.",
 e:"Il en compte plus d'un millier, enfants de couples qui se sont rencontrés dans le milieu espérantiste. Le financier George Soros est l'un d'eux."},

/* ---------- musique ---------- */
{t:'musique',v:1,s:"Le morceau le plus long du monde durera 639 ans.",
 e:"Organ²/ASLSP de John Cage est joué depuis 2001 dans une église allemande. Un changement d'accord attire des centaines de spectateurs ; le dernier a eu lieu en 2024, le prochain est prévu pour 2026."},
{t:'musique',v:1,s:"Un album de silence a rapporté de l'argent à ses auteurs.",
 e:"Le groupe américain Vulfpeck a publié en 2014 un album de dix pistes silencieuses, en demandant à ses auditeurs de le passer en boucle la nuit. Les 20 000 dollars de redevances ont financé une tournée gratuite, avant que la plateforme ne retire l'album."},
{t:'musique',v:1,s:"Le vinyle s'est revendu plus que le CD à partir de 2020.",
 e:"Pour la première fois depuis 1986, aux États-Unis. Un support qu'on avait déclaré mort trois fois a repris la tête, porté par des acheteurs qui, sondage après sondage, avouent ne pas posséder de platine."},
{t:'musique',v:0,s:"Mozart est mort pauvre et enterré dans une fosse commune anonyme.",
 e:"Il gagnait très bien sa vie et dépensait davantage. Sa sépulture suivait simplement le règlement viennois de l'époque, qui interdisait les monuments pour des raisons d'hygiène — comme pour la plupart des Viennois."},
{t:'musique',v:0,s:"Le solfège moderne a été inventé par les Grecs anciens.",
 e:"Les noms des notes viennent d'un hymne latin à saint Jean, découpé par le moine Guido d'Arezzo vers l'an mille : ut, ré, mi, fa, sol, la venaient chacun d'un début de vers."},

/* ---------- sport ---------- */
{t:'sport',v:1,s:"L'art a été une discipline olympique.",
 e:"De 1912 à 1948, on remettait des médailles en peinture, sculpture, architecture, littérature et musique. Les œuvres devaient s'inspirer du sport. Pierre de Coubertin lui-même a gagné l'or en littérature, sous pseudonyme."},
{t:'sport',v:1,s:"Un marathonien a gagné une médaille olympique en ayant fait la moitié du parcours en voiture.",
 e:"Fred Lorz, en 1904 : épuisé, il monte en voiture, l'auto tombe en panne, il termine à pied en tête. Il a reconnu la blague au moment de recevoir la couronne, devant la fille du président."},
{t:'sport',v:1,s:"Le tir à la corde a été un sport olympique.",
 e:"De 1900 à 1920. Une même équipe pouvait représenter deux pays, et en 1908 la police de Liverpool a battu les autres équipes britanniques avec ses bottes réglementaires, jugées trop lourdes par les perdants."},
{t:'sport',v:0,s:"Le football a été inventé en Angleterre.",
 e:"Les Anglais ont codifié le jeu en 1863, mais des jeux de balle au pied sont attestés en Chine dès le IIᵉ siècle avant notre ère. La FIFA reconnaît officiellement le cuju comme ancêtre."},
{t:'sport',v:0,s:"Un joueur de tennis a déjà servi à plus de 300 km/h.",
 e:"Le record homologué est de 263 km/h, par Sam Groth en 2012. Passé une certaine vitesse, la balle se déforme et perd tellement d'énergie que la limite physique n'est plus très loin."},

/* ---------- pop ---------- */
{t:'pop',v:1,s:"Le cri du T. rex de Jurassic Park est un bébé éléphant.",
 e:"Mélangé à un alligator et à un tigre. L'ingénieur du son a passé des mois dans des zoos ; le râle de la bête la plus terrifiante du cinéma est en grande partie un barrissement de bébé ralenti."},
{t:'pop',v:1,s:"Le studio Pixar a failli perdre Toy Story 2 à cause d'une commande effacée.",
 e:"Une commande de suppression lancée sur le mauvais répertoire a effacé 90 % du film, et les sauvegardes étaient défectueuses. Une employée en congé maternité avait une copie chez elle."},
{t:'pop',v:1,s:"De véritables membres de la pègre jouent dans Le Parrain.",
 e:"Lenny Montana, qui incarne Luca Brasi, était un exécuteur de la famille Colombo posté sur le tournage pour surveiller la production. Coppola l'a engagé sur place. Sa nervosité devant Marlon Brando est restée au montage."},
{t:'pop',v:0,s:"Walt Disney a fait congeler son corps.",
 e:"Il a été incinéré deux jours après sa mort en 1966, et sa tombe est publique à Glendale. La rumeur est née dans un fanzine l'année suivante, portée par le goût du personnage pour la technologie."},
{t:'pop',v:0,s:"Le personnage de Superman a toujours su voler.",
 e:"À ses débuts en 1938, il ne faisait que sauter — « plus haut qu'un immeuble d'un seul bond ». Le vol est venu des dessins animés des années 1940, parce qu'animer les sauts coûtait trop cher."},

/* ---------- techno ---------- */
{t:'techno',v:1,s:"Le premier bug informatique était un vrai insecte.",
 e:"Un papillon de nuit coincé dans un relais du Harvard Mark II, en 1947. L'équipe l'a scotché dans le journal de bord avec la mention « premier cas réel de bug trouvé ». La page est exposée au Smithsonian."},
{t:'techno',v:1,s:"Un téléphone d'aujourd'hui est plus puissant que tous les ordinateurs d'Apollo 11 réunis.",
 e:"L'ordinateur de bord tournait avec 4 kilo-octets de mémoire vive. Un téléphone courant en a un million de fois plus — et l'emploie surtout à faire défiler des images."},
{t:'techno',v:1,s:"Le premier site web est encore en ligne.",
 e:"Mis en ligne au CERN en 1991, il expliquait ce qu'était le World Wide Web à des gens qui n'en avaient jamais entendu parler. Le CERN l'a restauré à son adresse d'origine en 2013."},
{t:'techno',v:0,s:"Internet a été conçu pour survivre à une guerre nucléaire.",
 e:"Les concepteurs d'ARPANET visaient le partage de temps de calcul entre universités. L'idée nucléaire vient d'un rapport parallèle de la RAND sur les réseaux résistants, que la presse a fusionné avec le projet."},
{t:'techno',v:0,s:"La touche QWERTY a été conçue pour ralentir les dactylos.",
 e:"Elle sépare les paires de lettres les plus fréquentes pour éviter que les barres des machines à écrire se croisent — c'est-à-dire pour accélérer la frappe en évitant les blocages, pas pour la freiner."},

/* ---------- art et récits ---------- */
{t:'art',v:1,s:"La Joconde n'est devenue célèbre qu'après avoir été volée.",
 e:"En 1911, un employé du Louvre l'a sortie sous son manteau. Le cadre vide a fait la une pendant deux ans et attiré plus de visiteurs que le tableau. Kafka et Picasso sont venus voir le mur."},
{t:'art',v:1,s:"Van Gogh n'a vendu qu'un seul tableau de son vivant.",
 e:"La Vigne rouge, 400 francs, à une peintre belge. Son frère Théo, marchand d'art, ne parvenait pas à le placer. Aujourd'hui, ses toiles comptent parmi les plus chères jamais adjugées."},
{t:'art',v:1,s:"Les statues grecques étaient peintes de couleurs vives.",
 e:"Les ultraviolets révèlent les pigments encore présents dans la pierre : rouges, bleus, dorures. Le marbre blanc que nous admirons est un accident du temps, que la Renaissance a pris pour un idéal esthétique."},
{t:'art',v:0,s:"Van Gogh s'est coupé l'oreille entière.",
 e:"Le rapport du médecin décrit le lobe et un peu plus. Le peintre a ensuite posé pour deux autoportraits avec un pansement — sur l'oreille droite, alors que c'est la gauche qui était atteinte : il peignait devant un miroir."},
{t:'litt',v:1,s:"Un roman entier a été écrit sans la lettre e.",
 e:"La Disparition de Georges Perec, trois cents pages en 1969. Plusieurs critiques ne l'ont pas remarqué. Le traducteur anglais a fait de même, et l'espagnol a supprimé le a, plus fréquent dans sa langue."},
{t:'litt',v:1,s:"Le mot « robot » vient d'une pièce de théâtre tchèque.",
 e:"R.U.R., de Karel Čapek, en 1920. Le mot vient de robota, la corvée servile. La pièce se termine par une révolte des robots — le thème est né en même temps que le mot."},
{t:'litt',v:0,s:"Shakespeare a inventé plus de mille mots de la langue anglaise.",
 e:"On lui attribue les premières attestations écrites, ce qui n'est pas la même chose. La numérisation des textes de son époque a fait fondre la liste : il écrivait comme on parlait autour de lui."},
{t:'litt',v:0,s:"Les frères Grimm ont écrit leurs contes pour les enfants.",
 e:"Ils collectaient des récits populaires pour des philologues, avec des versions bien plus dures. Les éditions successives ont adouci les textes au fil du succès en librairie — c'est le public qui a fait des contes une littérature enfantine."},
/* ---------- vague 2 ---------- */
{t:'animaux',v:1,s:"Les loutres de mer se tiennent par la patte en dormant.",
 e:"Pour ne pas dériver pendant la nuit. Quand elles sont seules, elles s'enroulent dans une algue et s'y amarrent. Chacune garde aussi un caillou fétiche dans une poche sous l'aisselle."},
{t:'animaux',v:1,s:"Un ver plat peut apprendre quelque chose, être découpé, et sa queue s'en souvient.",
 e:"Des planaires entraînées puis sectionnées ont vu leur moitié arrière régénérer une tête — qui gardait l'apprentissage. La mémoire ne tient donc pas seulement dans le cerveau, et personne ne sait exactement où."},
{t:'animaux',v:1,s:"Les corbeaux gardent rancune et se transmettent les visages.",
 e:"Des chercheurs masqués ayant capturé des corbeaux se sont fait houspiller cinq ans plus tard, y compris par des oiseaux jamais capturés. L'information circule dans le groupe et passe aux générations suivantes."},
{t:'animaux',v:1,s:"Les girafes n'ont que sept vertèbres cervicales, autant que nous.",
 e:"Chacune mesure une trentaine de centimètres. Presque tous les mammifères en ont sept, du dauphin à la souris — un verrou du développement que même deux mètres de cou n'ont pas fait sauter."},
{t:'animaux',v:1,s:"Un poulpe peut goûter ce qu'il touche.",
 e:"Ses ventouses portent des récepteurs chimiques : il « goûte » une pierre en la palpant, sans la porter à sa bouche. Chaque bras traite l'information localement, ce qui revient à huit demi-cerveaux."},
{t:'animaux',v:1,s:"Les fourmis coupeuses de feuilles cultivent des champignons depuis des millions d'années.",
 e:"Elles ne mangent pas les feuilles : elles s'en servent de compost pour une seule espèce de champignon qu'elles désherbent, fertilisent et traitent avec une bactérie antibiotique. L'agriculture a cinquante millions d'années de plus que nous."},
{t:'animaux',v:1,s:"Le cri d'un cochon peut dépasser le bruit d'un décollage d'avion.",
 e:"Jusqu'à 115 décibels, contre 113 pour un réacteur au décollage mesuré à distance équivalente. Un porc contrarié est l'un des animaux de ferme les plus bruyants du monde."},
{t:'animaux',v:1,s:"Les éléphants se reconnaissent dans un miroir.",
 e:"Un test que très peu d'espèces passent : grands singes, dauphins, pies. Marqués d'une croix sur le front, ils la touchent avec leur trompe en se regardant, preuve qu'ils comprennent voir leur propre reflet."},
{t:'animaux',v:1,s:"Les guêpes ont inventé le papier bien avant nous.",
 e:"Elles mâchent du bois mort et le mêlent à leur salive pour obtenir une pâte de cellulose qu'elles étalent en fines couches. C'est exactement le procédé du papier, découvert par les humains cent millions d'années plus tard."},
{t:'animaux',v:1,s:"Un colibri doit manger toutes les quinze minutes pour ne pas mourir.",
 e:"Son métabolisme est le plus rapide de tous les vertébrés. La nuit, faute de pouvoir se nourrir, il entre en torpeur : sa température chute de vingt degrés et son cœur passe de 1 200 à 50 battements."},
{t:'animaux',v:0,s:"Un poisson rouge grandit selon la taille de son bocal.",
 e:"Il grandit selon la qualité de l'eau. Dans un petit volume, les déchets s'accumulent et freinent sa croissance en l'intoxiquant lentement. En bassin propre, il atteint trente centimètres."},
{t:'animaux',v:0,s:"Les araignées se glissent dans notre bouche pendant notre sommeil.",
 e:"Le chiffre de « huit araignées par an » a été inventé en 1993 pour montrer qu'une statistique absurde pouvait circuler. Une bouche qui respire et vibre est exactement ce qu'une araignée évite."},
{t:'animaux',v:0,s:"Les chiens voient en noir et blanc.",
 e:"Ils voient le bleu et le jaune, mais confondent le rouge et le vert — comme un humain daltonien. La balle rouge sur une pelouse verte, très populaire, est pour eux la pire couleur possible."},
{t:'animaux',v:0,s:"Un cheval qui se casse une jambe doit obligatoirement être euthanasié.",
 e:"C'est fréquent mais pas obligatoire. Le problème est le poids : un cheval qui reporte tout sur trois membres développe une fourbure mortelle. Les chirurgies existent, coûtent très cher, et réussissent parfois."},
{t:'animaux',v:0,s:"Les grenouilles attrapent des verrues et peuvent nous en donner.",
 e:"Les verrues sont dues à un virus humain. Les bosses des crapauds sont des glandes à venin. Le rapprochement vient de la ressemblance, et il a valu aux crapauds des siècles de mauvaise réputation."},
{t:'animaux',v:0,s:"Les requins doivent nager en permanence, sinon ils meurent.",
 e:"C'est vrai pour une minorité, dont le grand blanc. La plupart des espèces pompent l'eau par la bouche et dorment posées sur le fond — le requin nourrice passe ses journées empilé avec ses congénères."},
{t:'animaux',v:0,s:"Un canard n'a pas d'écho quand il cancane.",
 e:"Une équipe de l'université de Salford l'a testé dans une chambre d'écho : le canard résonne parfaitement. Le son est simplement trop doux et trop progressif pour qu'on distingue l'écho de l'original."},

{t:'espace',v:1,s:"Il pleut des diamants sur Neptune et Uranus.",
 e:"La pression y écrase le méthane et libère le carbone, qui cristallise et coule vers le centre. Des laboratoires ont reproduit le phénomène au laser en 2017 : les diamants se forment en quelques nanosecondes."},
{t:'espace',v:1,s:"Un objet lâché sur la Lune tombe aussi vite qu'une plume.",
 e:"L'astronaute David Scott l'a filmé en 1971 avec un marteau et une plume de faucon. Sans air pour freiner, ils ont touché le sol ensemble — l'expérience de Galilée, enfin faite dans les bonnes conditions."},
{t:'espace',v:1,s:"La Lune s'éloigne de la Terre un peu plus chaque année.",
 e:"De 3,8 centimètres par an, mesurés au laser sur les réflecteurs posés par Apollo. Nos journées s'allongent en conséquence : à l'époque des dinosaures, elles duraient vingt-trois heures."},
{t:'espace',v:1,s:"Il existe une planète entièrement recouverte de lave en fusion.",
 e:"K2-141b tourne si près de son étoile qu'un côté fond en permanence. Elle a des océans de roche liquide profonds de cent kilomètres, des vents supersoniques, et il y pleut des cailloux."},
{t:'espace',v:1,s:"Deux astronautes ont laissé une photo de famille sur la Lune.",
 e:"Charles Duke a posé en 1972 un cliché de sa femme et de ses fils, plastifié, avec un mot au dos. La photo est toujours là — mais le rayonnement l'a probablement effacée depuis longtemps."},
{t:'espace',v:1,s:"Il y a plus d'étoiles dans l'univers que de grains de sable sur Terre.",
 e:"Environ mille milliards de milliards d'étoiles contre sept mille milliards de milliards de grains — l'estimation dépend de ce qu'on appelle du sable. Les deux nombres sont du même ordre, ce qui n'est déjà pas rien."},
{t:'espace',v:1,s:"Un astronaute a joué au golf sur la Lune.",
 e:"Alan Shepard, en 1971, avec une tête de club fixée à un manche d'outil et deux balles cachées dans sa chaussette. Gêné par sa combinaison, il a frappé d'une seule main ; l'analyse d'images donne 36 mètres."},
{t:'espace',v:0,s:"Il y a un côté de la Lune que le Soleil n'atteint jamais.",
 e:"Toute la surface est éclairée à tour de rôle. Seuls quelques cratères du pôle sud, dont le fond ne voit jamais le jour, méritent ce titre — et c'est justement là qu'on cherche de la glace."},
{t:'espace',v:0,s:"Les astronautes flottent parce qu'il n'y a pas de gravité si haut.",
 e:"À 400 kilomètres, la gravité vaut encore 90 % de celle du sol. Ils tombent en permanence vers la Terre, à 28 000 km/h, en la manquant à chaque tour. C'est une chute perpétuelle, pas une absence de poids."},
{t:'espace',v:0,s:"Le Soleil est une boule de feu.",
 e:"Le feu est une combustion, qui exige de l'oxygène. Le Soleil est un plasma où des noyaux d'hydrogène fusionnent — un processus qui n'a rien à voir, et qui libère un million de fois plus d'énergie."},
{t:'espace',v:0,s:"On a retrouvé les traces de Neil Armstrong grâce à un télescope depuis la Terre.",
 e:"Aucun télescope terrestre n'a la résolution nécessaire : il faudrait un miroir de plusieurs centaines de mètres. Ce sont des sondes en orbite lunaire qui ont photographié les sites d'alunissage, en 2009."},
{t:'espace',v:0,s:"Une année-lumière est une durée.",
 e:"C'est une distance : celle que la lumière parcourt en un an, environ 9 500 milliards de kilomètres. Le mot « année » désigne le temps mis, pas la mesure elle-même."},

{t:'geo',v:1,s:"Il existe un pays dont la capitale change de camp tous les six mois.",
 e:"La Bolivie a deux capitales : Sucre pour la justice, La Paz pour le gouvernement. Mais c'est l'île des Faisans, entre France et Espagne, qui change vraiment de souveraineté deux fois par an, depuis 1659."},
{t:'geo',v:1,s:"Le Vatican compte plus de crimes par habitant que n'importe quel pays.",
 e:"Avec huit cents résidents et des millions de visiteurs, chaque vol à la tire commis par un touriste sur un autre touriste gonfle un taux calculé sur une population minuscule. La statistique est vraie et ne veut rien dire."},
{t:'geo',v:1,s:"Une partie de la France est en Amérique du Sud.",
 e:"La Guyane est un département français : l'Union européenne a donc une frontière terrestre avec le Brésil, la plus longue de toutes ses frontières extérieures. On y lance aussi les fusées européennes."},
{t:'geo',v:1,s:"L'Alaska est à la fois l'État le plus à l'ouest et le plus à l'est des États-Unis.",
 e:"Les îles Aléoutiennes franchissent le 180ᵉ méridien : leur extrémité repasse dans l'hémisphère est. Le même État détient donc les records ouest, est et nord du pays."},
{t:'geo',v:1,s:"La mer Morte descend d'environ un mètre par an.",
 e:"Le Jourdain qui l'alimente est détourné pour l'irrigation, et l'industrie pompe sa saumure. Sa surface a perdu un tiers en cinquante ans, et le sol qui s'effondre autour ouvre des milliers de gouffres."},
{t:'geo',v:1,s:"Il existe une frontière que l'on franchit en traversant une bibliothèque.",
 e:"La Haskell Free Library est à cheval sur la frontière entre le Québec et le Vermont ; une ligne noire traverse la salle de lecture. On peut y entrer d'un pays et emprunter un livre dans l'autre."},
{t:'geo',v:1,s:"Le point le plus haut du Danemark ne dépasse pas la hauteur d'un immeuble de cinquante étages.",
 e:"Le Møllehøj culmine à 170,86 mètres. Le titre s'est joué à quelques centimètres entre trois collines voisines, et n'a été tranché qu'en 2005 après une campagne de mesures au laser."},
{t:'geo',v:0,s:"Le Groenland est plus grand que l'Afrique.",
 e:"L'Afrique est quatorze fois plus vaste. C'est la projection de Mercator qui étire tout ce qui approche des pôles : sur une carte plate, le Groenland gonfle, et la plupart des gens gardent cette image en tête."},
{t:'geo',v:0,s:"Le Nil est le seul fleuve à couler vers le nord.",
 e:"Des dizaines de fleuves coulent vers le nord, dont le Rhône jusqu'à Lyon, l'Ob en Sibérie ou le Mackenzie au Canada. Un fleuve descend, voilà tout ; le nord n'est pas « en haut » ailleurs que sur nos cartes."},
{t:'geo',v:0,s:"L'équateur traverse plus de pays que n'importe quelle autre ligne.",
 e:"Il en traverse onze. Le méridien de Greenwich en traverse huit, mais c'est le 30ᵉ parallèle nord qui bat tout le monde en longueur de terres franchies."},
{t:'geo',v:0,s:"Toutes les grandes villes sont bâties près d'un fleuve.",
 e:"Beaucoup, pas toutes. Madrid, Pékin, Riyad, Los Angeles n'ont jamais dépendu d'un cours d'eau utilisable. Elles se sont bâties sur des routes commerciales, du pétrole ou une simple décision politique."},

{t:'histo',v:1,s:"Un Français a inventé le mètre en mesurant la Terre pendant la Révolution.",
 e:"Deux astronomes ont arpenté sept ans la méridienne de Dunkerque à Barcelone, sous les guerres et les arrestations, pour définir le mètre comme un dix-millionième du quart du méridien. Ils se sont trompés de 0,2 millimètre."},
{t:'histo',v:1,s:"Le premier ordinateur a été programmé par une femme, un siècle avant qu'il n'existe.",
 e:"Ada Lovelace a écrit en 1843 l'algorithme de la machine analytique de Babbage, jamais construite. Elle a aussi vu la première que la machine pourrait manipuler autre chose que des nombres — de la musique, par exemple."},
{t:'histo',v:1,s:"Une guerre a éclaté à cause d'un seau.",
 e:"En 1325, des soldats de Modène ont volé un seau de puits à Bologne. La bataille qui a suivi a fait deux mille morts. Le seau est toujours exposé à Modène — ou plutôt sa copie, l'original étant à l'abri."},
{t:'histo',v:1,s:"Un pape a fait juger le cadavre de son prédécesseur.",
 e:"En 897, Étienne VI a fait déterrer Formose, l'a assis sur un trône en habits pontificaux et lui a fait un procès. Le cadavre, condamné, a été jeté dans le Tibre. Le concile suivant a annulé le jugement."},
{t:'histo',v:1,s:"Un homme a traversé le mur de Berlin en montgolfière avec toute sa famille.",
 e:"Deux familles est-allemandes ont construit un ballon de vingt-huit mètres avec du tissu de rideaux acheté par petits lots pour ne pas éveiller les soupçons. Ils ont passé la frontière en 1979, à huit personnes."},
{t:'histo',v:1,s:"Un employé de bureau soviétique a probablement évité une guerre nucléaire en désobéissant.",
 e:"En 1983, le système d'alerte de Stanislav Petrov annonce cinq missiles américains. Le règlement imposait de transmettre. Il a jugé qu'une vraie attaque n'en compterait pas cinq et a signalé une panne. C'en était une."},
{t:'histo',v:1,s:"La Tour Eiffel devait être démontée après vingt ans.",
 e:"Le permis de Gustave Eiffel courait jusqu'en 1909. Il a sauvé sa tour en y installant une antenne de télégraphie sans fil, devenue indispensable à l'armée. La science a gardé ce que l'esthétique voulait abattre."},
{t:'histo',v:1,s:"On a organisé des courses de chars à Constantinople pendant mille ans.",
 e:"L'hippodrome fonctionnait encore au XIIᵉ siècle. Les factions des Bleus et des Verts étaient de véritables partis : leur rivalité a déclenché en 532 une émeute qui a rasé la moitié de la ville et fait trente mille morts."},
{t:'histo',v:0,s:"Christophe Colomb voulait prouver que la Terre était ronde.",
 e:"Tout le monde le savait déjà. Son désaccord portait sur la taille : il la croyait beaucoup plus petite, ce qui rendait l'Asie atteignable par l'ouest. Ses détracteurs avaient raison, et il a eu de la chance qu'un continent se trouve sur la route."},
{t:'histo',v:0,s:"Les esclaves ont bâti les pyramides.",
 e:"Les fouilles des villages d'ouvriers montrent des travailleurs nourris à la viande, soignés — on a retrouvé des fractures réduites — et enterrés avec honneur près du chantier. C'était un chantier d'État, pas un bagne."},
{t:'histo',v:0,s:"La guillotine a été inventée par le docteur Guillotin.",
 e:"Il l'a proposée par humanité, pour égaliser les exécutions, mais la machine a été conçue par le chirurgien Antoine Louis. Sa famille, gênée du nom, a demandé sans succès qu'il soit changé, puis a changé le sien."},
{t:'histo',v:0,s:"Napoléon était petit.",
 e:"Il mesurait 1,68 m, au-dessus de la moyenne française de son temps. La confusion vient du pouce français, plus long que l'anglais : ses cinq pieds deux pouces ont été lus à l'anglaise par la propagande britannique."},
{t:'histo',v:0,s:"Le peuple a pris la Bastille pour libérer des centaines de prisonniers.",
 e:"Il y en avait sept, dont quatre faussaires. C'est la poudre et les armes stockées qui intéressaient les assaillants. La prison, presque vide, devait d'ailleurs être démolie pour raisons budgétaires."},

{t:'sci',v:1,s:"Il existe un métal qui fond dans la main.",
 e:"Le gallium fond à 29,8 °C. On en fait des cuillères farceuses qui disparaissent dans le thé. Il ronge aussi l'aluminium en s'infiltrant entre ses cristaux, ce qui le fait interdire en cabine d'avion."},
{t:'sci',v:1,s:"Le vide n'est pas vide.",
 e:"Des paires de particules y apparaissent et s'annihilent en permanence. On le mesure : deux plaques très rapprochées dans le vide se poussent l'une vers l'autre parce qu'il y a moins de fluctuations entre elles qu'autour."},
{t:'sci',v:1,s:"Un objet chauffé pèse plus lourd.",
 e:"L'énergie a une masse. Chauffer un kilo de fer de mille degrés lui ajoute environ cinq milliardièmes de gramme — indétectable, mais parfaitement réel, et c'est la même équation qui fait fonctionner les étoiles."},
{t:'sci',v:1,s:"Le verre laisse passer la lumière visible mais bloque les ultraviolets.",
 e:"C'est pourquoi on ne bronze pas derrière une fenêtre alors qu'on a chaud. Le verre ordinaire absorbe les UVB ; les serres tropicales utilisent des vitrages spéciaux pour que les plantes reçoivent le spectre complet."},
{t:'sci',v:1,s:"Le corps humain contient assez de carbone pour faire neuf mille mines de crayon.",
 e:"Environ seize kilos de carbone chez un adulte. On y trouve aussi de quoi fabriquer une petite quantité de savon avec les graisses, et assez de fer pour un clou de sept centimètres."},
{t:'sci',v:1,s:"L'eau peut bouillir et geler en même temps.",
 e:"Au point triple, à 0,01 °C et sous très basse pression, l'eau existe simultanément en glace, liquide et vapeur. Le spectacle est saisissant : le liquide bout tandis que des cristaux s'y forment."},
{t:'sci',v:1,s:"Il faut plus d'énergie pour digérer du céleri qu'il n'en apporte.",
 e:"C'est l'un des rares aliments à bilan calorique négatif : cent grammes apportent seize calories, et la mastication plus la digestion en consomment davantage. Manger du céleri fait donc littéralement maigrir, très lentement."},
{t:'sci',v:0,s:"Un verre d'eau tourne dans l'autre sens dans l'hémisphère sud.",
 e:"La force de Coriolis existe mais est mille fois trop faible à cette échelle. Ce qui décide, c'est la forme du lavabo et le mouvement initial de l'eau. Les démonstrations vues à l'équateur sont des tours de main."},
{t:'sci',v:0,s:"On peut voir la Terre tourner depuis un avion.",
 e:"L'avion tourne avec elle, comme l'atmosphère. Voler vers l'ouest ne fait pas gagner de temps sur la rotation : les différences de durée entre allers et retours viennent uniquement des vents d'altitude."},
{t:'sci',v:0,s:"L'or est le métal le plus rare sur Terre.",
 e:"Le rhodium, le platine et l'iridium sont bien plus rares. L'or doit son statut à sa résistance à la corrosion, à sa couleur et au fait qu'on l'ait trouvé pur en surface — pas à sa rareté."},
{t:'sci',v:0,s:"On ne peut pas plier une feuille de papier plus de sept fois.",
 e:"Une lycéenne américaine a atteint douze plis en 2002 avec un rouleau de papier hygiénique de 1 200 mètres. La limite n'est pas magique : elle dépend uniquement du rapport entre longueur et épaisseur."},
{t:'sci',v:0,s:"Le tétanos s'attrape avec la rouille.",
 e:"C'est une bactérie du sol, qui prospère sans oxygène. Un clou rouillé traîne dehors, voilà tout le lien. Une écharde propre plantée profondément est plus dangereuse qu'une coupure superficielle sur du métal oxydé."},

{t:'wtf',v:1,s:"Un pays a déclaré la guerre à l'Allemagne pendant les deux guerres mondiales sans jamais envoyer un soldat.",
 e:"Le Liberia, entre autres. Mais le cas extrême est le Monténégro, resté techniquement en guerre avec le Japon de 1904 à 2006, faute d'avoir été mentionné dans un traité de paix."},
{t:'wtf',v:1,s:"Une femme a survécu à une chute de dix mille mètres sans parachute.",
 e:"Vesna Vulović, hôtesse de l'air, a chuté en 1972 dans un morceau de fuselage tombé sur une pente enneigée. Un bûcheron l'a trouvée et a su la maintenir en vie. Elle a repris le travail — au sol."},
{t:'wtf',v:1,s:"Un homme a été frappé par la foudre sept fois et en est mort d'autre chose.",
 e:"Roy Sullivan, garde forestier en Virginie, entre 1942 et 1977. Il en a perdu un ongle de pied, ses sourcils et ses cheveux à plusieurs reprises. Il est mort à 71 ans, pour une raison sans rapport."},
{t:'wtf',v:1,s:"Une compagnie a vendu à ses clients le droit de nommer une tempête.",
 e:"Un institut météorologique berlinois vend les parrainages de dépressions et d'anticyclones depuis 2002. Les noms sont ensuite repris tels quels par les bulletins allemands, y compris quand ce sont des prénoms d'animaux domestiques."},
{t:'wtf',v:1,s:"Un pays a interdit le sel dans les restaurants.",
 e:"New York n'est pas un pays, mais le Pérou a bien imposé en 2018 l'octogone noir sur les produits salés, et la ville de New York a interdit les salières sur les tables de ses cantines scolaires. Le sel est un vrai sujet politique."},
{t:'wtf',v:1,s:"Une bibliothèque prête des gens au lieu de livres.",
 e:"La Human Library, née à Copenhague en 2000, prête des personnes pour une conversation de trente minutes : un réfugié, un ancien sans-abri, une personne bipolaire. Le catalogue liste des préjugés, pas des titres."},
{t:'wtf',v:1,s:"Il existe une bourse où l'on échange des droits à polluer.",
 e:"Le marché européen du carbone échange des quotas d'émission comme des actions. Une tonne de CO₂ y a un prix qui monte et descend, et des fonds spéculatifs en achètent sans avoir la moindre usine."},
{t:'wtf',v:0,s:"Un homme a vécu deux ans sans manger.",
 e:"Angus Barbieri a jeûné 382 jours en 1965, sous surveillance médicale, avec vitamines et thé. Un an et dix-sept jours, pas deux ans. Il a perdu 125 kilos et n'en a repris que sept."},
{t:'wtf',v:0,s:"Il est interdit de mourir au Parlement britannique.",
 e:"Cette « loi » arrive en tête des sondages sur les lois absurdes, et n'existe dans aucun texte. Elle vient d'une confusion avec le statut de palais royal du bâtiment, qui donnerait droit à des funérailles nationales."},
{t:'wtf',v:0,s:"Une ville américaine a élu un chien comme maire.",
 e:"Plusieurs villages ont eu des maires animaux honorifiques — un chat à Talkeetna, une chèvre au Vermont — mais toujours sans aucun pouvoir, et souvent au profit d'une association. Aucune élection légale n'a jamais désigné un animal."},
{t:'wtf',v:0,s:"Le premier distributeur automatique date des années 1900.",
 e:"Héron d'Alexandrie en décrit un au Iᵉʳ siècle : on introduisait une pièce dans une fente, son poids soulevait un levier, et de l'eau bénite s'écoulait. Le mécanisme n'a rien à envier aux nôtres."},

{t:'cuisine',v:1,s:"Le poivron et le piment sont la même espèce.",
 e:"Capsicum annuum couvre le poivron doux, le jalapeño et le piment de Cayenne. Une seule mutation débranche la production de capsaïcine — c'est cette panne qui a donné le poivron, sélectionné pendant des siècles."},
{t:'cuisine',v:1,s:"Les cacahuètes ne sont pas des noix.",
 e:"Ce sont des légumineuses, cousines des pois et des lentilles, et elles poussent sous terre. C'est pourquoi une allergie à l'arachide et une allergie aux fruits à coque sont deux choses différentes."},
{t:'cuisine',v:1,s:"Le pain de mie industriel contient souvent du sucre.",
 e:"Le sucre nourrit la levure, accélère la coloration et retarde le rassissement. Certaines mies anglo-saxonnes en contiennent assez pour être classées pâtisseries par les autorités irlandaises — le tribunal l'a confirmé en 2020."},
{t:'cuisine',v:1,s:"On a longtemps utilisé le safran pour teindre les vêtements avant de le manger.",
 e:"Les robes des moines bouddhistes lui doivent leur couleur, et la Crète en peignait ses fresques il y a 3 500 ans. L'usage culinaire est venu ensuite, quand le prix a rendu la teinture déraisonnable."},
{t:'cuisine',v:1,s:"Le lait de vache n'a jamais été destiné aux adultes de notre espèce.",
 e:"La plupart des humains perdent l'enzyme qui digère le lactose après l'enfance. La mutation qui la conserve est apparue il y a huit mille ans en Europe et en Afrique de l'Est, et s'est répandue à toute vitesse."},
{t:'cuisine',v:0,s:"L'alcool réchauffe.",
 e:"Il dilate les vaisseaux de la peau : on a chaud en surface pendant qu'on perd de la chaleur plus vite. C'est exactement l'inverse de ce qu'il faut faire en montagne, et cela a coûté beaucoup de vies."},
{t:'cuisine',v:0,s:"Il faut boire deux litres d'eau par jour.",
 e:"Le chiffre vient d'un rapport américain de 1945 qui précisait, dans la phrase suivante, que la nourriture en apporte l'essentiel. La moitié a été retenue, l'autre oubliée. La soif reste le meilleur indicateur."},
{t:'cuisine',v:0,s:"Le chocolat noir contient plus de caféine que le café.",
 e:"Cent grammes de chocolat noir en contiennent 80 milligrammes, une tasse de café 95 — pour dix fois moins de matière. Le chocolat contient surtout de la théobromine, une molécule voisine mais bien plus douce."},

{t:'techno',v:1,s:"Le premier appel depuis un téléphone portable a servi à narguer un concurrent.",
 e:"En 1973, Martin Cooper de Motorola a appelé son rival de Bell Labs depuis un trottoir de New York pour lui annoncer qu'il l'appelait d'un téléphone sans fil. L'appareil pesait un kilo et se rechargeait en dix heures."},
{t:'techno',v:1,s:"Le courriel est plus vieux qu'Internet.",
 e:"Ray Tomlinson envoie le premier message entre deux machines en 1971, sur ARPANET, et choisit l'arobase parce qu'aucun nom ne pouvait la contenir. Internet, au sens du protocole IP, ne date que de 1983."},
{t:'techno',v:1,s:"Une part du trafic mondial passe encore par des câbles posés au fond des océans.",
 e:"Plus de 99 %. Les satellites ne servent qu'à la marge. Quatre cents câbles de la grosseur d'un tuyau d'arrosage relient les continents, et les principales pannes sont dues aux ancres et aux chaluts."},
{t:'techno',v:1,s:"Un mot de passe très long en lettres simples bat un mot de passe court et compliqué.",
 e:"Ce qui compte, c'est le nombre de combinaisons possibles. Quatre mots ordinaires tirés au hasard résistent des siècles, là où huit caractères avec symboles tombent en heures — et personne ne les retient."},
{t:'techno',v:0,s:"Naviguer en navigation privée rend anonyme.",
 e:"Le mode privé n'efface que l'historique local. Le fournisseur d'accès, l'employeur et les sites visités voient exactement la même chose qu'avant. Il protège d'une personne qui reprendrait l'ordinateur, pas d'un réseau."},
{t:'techno',v:0,s:"Vider la corbeille supprime définitivement un fichier.",
 e:"L'espace est simplement marqué comme réutilisable. Tant que rien n'a réécrit dessus, un logiciel courant retrouve le fichier. C'est la raison pour laquelle l'effacement sécurisé consiste à écrire du bruit par-dessus."},
{t:'techno',v:0,s:"Recharger son téléphone toute la nuit abîme la batterie.",
 e:"La charge s'arrête d'elle-même à 100 %. Ce qui use vraiment une batterie lithium, c'est la chaleur et le fait de la maintenir longtemps pleine ou complètement vide — pas le simple fait d'être branchée."},

{t:'sport',v:1,s:"Le marathon ne mesurait pas 42,195 kilomètres à l'origine.",
 e:"Il faisait environ 40 kilomètres. La distance actuelle vient des Jeux de Londres en 1908 : on a rallongé le départ jusqu'au château de Windsor pour que les enfants royaux voient la course de leurs fenêtres."},
{t:'sport',v:1,s:"Un homme a gagné une médaille olympique en tirant à la carabine à 72 ans.",
 e:"Oscar Swahn a été médaillé en 1920, à 72 ans et 280 jours — le plus vieux médaillé de l'histoire. Il s'était qualifié pour 1924 mais est tombé malade avant les Jeux."},
{t:'sport',v:1,s:"Le tennis se comptait autrefois avec une horloge.",
 e:"L'hypothèse la plus solide pour 15, 30, 40 : une aiguille avancée d'un quart de tour à chaque point, le 45 ayant été raccourci en 40 pour laisser la place à l'avantage. Le zéro se dit « love », déformation de l'œuf, pour sa forme."},
{t:'sport',v:0,s:"Le ballon de football a toujours eu des hexagones noirs et blancs.",
 e:"Ce motif date de 1970 : il a été conçu pour que le ballon reste visible sur les téléviseurs en noir et blanc. Avant, les ballons étaient en cuir brun, à lanières, et devenaient de plus en plus lourds sous la pluie."},
{t:'sport',v:0,s:"Un boxeur professionnel ne peut pas frapper sans être poursuivi, ses poings étant enregistrés comme des armes.",
 e:"Aucune législation au monde n'enregistre des poings comme armes. Un juge tient compte de l'entraînement pour apprécier l'intention, ce qui est très différent — et vaut aussi pour un judoka ou un rugbyman."},

{t:'pop',v:1,s:"Le générique de Game of Thrones changeait à chaque épisode.",
 e:"La carte animée ne montrait que les lieux visités dans l'épisode à venir. Certains spectateurs y cherchaient des indices — et en trouvaient : l'apparition d'une nouvelle ville annonçait où l'action allait basculer."},
{t:'pop',v:1,s:"Le studio qui a produit Le Seigneur des anneaux a fait pousser de vrais jardins deux ans avant le tournage.",
 e:"Les haies et les potagers de la Comté ont été plantés dans une ferme néo-zélandaise longtemps à l'avance pour paraître installés depuis toujours. Une équipe est venue arracher les mauvaises herbes chaque semaine."},
{t:'pop',v:0,s:"Le film Titanic a coûté plus cher que le vrai paquebot.",
 e:"C'est vrai en dollars courants, faux en dollars constants. Le navire a coûté 7,5 millions de 1912, soit près de 250 millions d'aujourd'hui, contre 200 millions pour le film. La comparaison qui circule oublie l'inflation."},
{t:'pop',v:0,s:"Mickey Mouse a été le premier personnage de dessin animé sonore.",
 e:"Steamboat Willie est le premier grand succès sonore, mais plusieurs courts métrages parlants l'avaient précédé, dont ceux de la série Song Car-Tunes dès 1924. Disney a surtout été le premier à en faire un événement."},

{t:'langue',v:1,s:"Le point d'exclamation n'avait pas de touche sur les premières machines à écrire.",
 e:"On le composait en trois gestes : un point, un retour arrière, une apostrophe. Il a fallu attendre les années 1970 pour qu'il obtienne sa propre touche sur les claviers courants."},
{t:'langue',v:1,s:"Certaines langues comptent en base vingt.",
 e:"Le français en garde la trace avec « quatre-vingts », héritée du gaulois. Le basque, le danois et le maya comptent encore par vingtaines — le maya avait aussi le zéro, des siècles avant son arrivée en Europe."},
{t:'langue',v:0,s:"Le mot « bonjour » existe dans toutes les langues.",
 e:"Beaucoup de langues n'ont pas de salutation neutre. En japonais, la formule dépend de l'heure et du rang ; certaines langues d'Amazonie n'ont aucun équivalent et l'on entre chez quelqu'un en annonçant ce qu'on vient faire."},
{t:'langue',v:0,s:"L'Académie française décide de l'orthographe officielle.",
 e:"Elle publie un dictionnaire, dont l'usage n'est pas obligatoire — même dans l'administration. Ses avis ont l'autorité morale d'une institution ancienne, pas la force d'une loi, et l'usage lui a souvent donné tort."},

{t:'musique',v:1,s:"Il existe un accord de guitare que personne n'a le droit de jouer sans payer.",
 e:"Faux pour un accord, vrai pour un enregistrement : la ligne de basse de six notes réutilisée en boucle par le hip-hop, le fameux « Amen break », n'a jamais rapporté un centime à son batteur, mort sans savoir sa célébrité."},
{t:'musique',v:1,s:"Un morceau de quatre minutes trente-trois secondes ne contient aucune note.",
 e:"4′33″ de John Cage se joue en silence, en trois mouvements. L'œuvre est faite des bruits de la salle : les toux, les sièges, la pluie sur le toit. Sa première, en 1952, a provoqué un scandale."},
{t:'musique',v:0,s:"Le violon Stradivarius sonne mieux grâce à un vernis secret.",
 e:"Des tests en aveugle avec des solistes internationaux ne les distinguent pas des bons violons modernes, et les préfèrent parfois moins. Le vernis analysé n'a rien d'extraordinaire : la légende fait une partie du son."},

{t:'art',v:1,s:"Un artiste a vendu une banane scotchée à un mur pour cent vingt mille dollars.",
 e:"Comedian, de Maurizio Cattelan, en 2019. L'acheteur repart avec un certificat et le droit de remplacer la banane quand elle noircit. Un performeur l'a mangée pendant la foire ; la galerie en a recollé une autre."},
{t:'art',v:1,s:"Un tableau s'est autodétruit juste après avoir été vendu aux enchères.",
 e:"En 2018, une toile de Banksy a glissé dans une broyeuse cachée dans son cadre au coup de marteau. Le mécanisme s'est enrayé à mi-parcours. L'œuvre à demi déchiquetée a été revendue trois ans plus tard dix-huit fois son prix."},
{t:'art',v:0,s:"Les impressionnistes ont choisi eux-mêmes leur nom.",
 e:"C'est une raillerie d'un critique devant Impression, soleil levant de Monet, en 1874. Le groupe s'est approprié l'insulte, comme les fauves et les cubistes après lui — l'histoire de l'art avance beaucoup par moqueries retournées."},

{t:'litt',v:1,s:"Un écrivain a publié un roman policier dont le coupable était le narrateur.",
 e:"Agatha Christie, en 1926, avec Le Meurtre de Roger Ackroyd. Le procédé a été jugé déloyal et a fait scandale ; on a voulu l'exclure du club des auteurs de romans policiers. Le livre est aujourd'hui considéré comme son chef-d'œuvre."},
{t:'litt',v:0,s:"Les livres de la Bibliothèque nationale sont tous consultables par le public.",
 e:"Une partie est en réserve, dont l'ancien Enfer, où l'on rangeait les ouvrages jugés licencieux. L'accès y est soumis à justification, et certains fonds légués restent scellés pendant des décennies à la demande du donateur."},
/* ---------- vague 3 ---------- */
{t:'animaux',v:1,s:"Les rats rient quand on les chatouille.",
 e:"Ils émettent des ultrasons à 50 kHz, inaudibles pour nous, et reviennent réclamer la main qui les chatouille. Le rire ne serait donc pas une invention de primates."},
{t:'animaux',v:1,s:"Une méduse est capable de rajeunir indéfiniment.",
 e:"Turritopsis dohrnii, blessée ou affamée, retourne à l'état de polype et recommence son cycle. En laboratoire, des individus l'ont fait des dizaines de fois. Dans la nature, les prédateurs finissent quand même par gagner."},
{t:'animaux',v:1,s:"Les abeilles savent compter jusqu'à quatre, et comprennent le zéro.",
 e:"Entraînées à choisir l'image avec le moins de formes, elles préfèrent une image vide quand on la leur propose. Comprendre qu'aucun objet est une quantité a demandé des siècles aux mathématiciens humains."},
{t:'animaux',v:1,s:"Un pigeon distingue un Monet d'un Picasso.",
 e:"Des pigeons entraînés sur une série de toiles ont ensuite trié correctement des tableaux jamais vus. Ils généralisent le style, pas l'image — ce que fait aussi un étudiant en histoire de l'art."},
{t:'animaux',v:1,s:"Les chats domestiques ne miaulent qu'aux humains.",
 e:"Entre adultes, ils communiquent par postures et odeurs. Le miaulement est un cri de chaton, conservé et modulé pour s'adresser à nous. Chaque chat met au point un répertoire propre à son foyer."},
{t:'animaux',v:1,s:"Une chauve-souris mange l'équivalent de son poids en insectes chaque nuit.",
 e:"Jusqu'à trois mille moustiques. Une colonie moyenne débarrasse une commune de plusieurs tonnes d'insectes par été — un service que personne ne facture et que personne ne remplace."},
{t:'animaux',v:1,s:"Le cerveau d'une autruche est plus petit que son œil.",
 e:"Son globe oculaire fait cinq centimètres, le plus gros de tous les animaux terrestres. Son cerveau est plus léger. Ce qui n'empêche pas l'autruche de courir à 70 km/h en évitant les obstacles."},
{t:'animaux',v:1,s:"Certaines fourmis explosent volontairement pour défendre leur colonie.",
 e:"Colobopsis explodens contracte son abdomen jusqu'à le rompre, projetant une colle toxique jaune sur l'assaillant. L'ouvrière meurt ; la colonie tient. Le comportement a été décrit officiellement en 2018."},
{t:'animaux',v:1,s:"Un ours polaire est noir sous sa fourrure.",
 e:"Sa peau est noire pour absorber la chaleur, et ses poils sont creux et translucides — pas blancs. Ils diffusent la lumière comme la neige. En captivité sous les tropiques, des algues les font virer au vert."},
{t:'animaux',v:0,s:"Les éléphants sont les seuls animaux incapables de sauter.",
 e:"Beaucoup ne sautent pas : les rhinocéros, les hippopotames, les paresseux, les escargots. L'éléphant a en plus des os de patte trop massifs et une masse qui rend le retour au sol impossible sans casse."},
{t:'animaux',v:0,s:"Le paresseux est l'animal le plus lent du monde.",
 e:"Il avance à 0,24 km/h, mais l'escargot de jardin fait 0,05 et l'étoile de mer 0,03. Le paresseux détient en revanche un vrai record : sa digestion peut prendre un mois."},
{t:'animaux',v:0,s:"Les serpents sont attirés par la musique du charmeur.",
 e:"Ils n'ont pas d'oreille externe et perçoivent surtout les vibrations du sol. Le cobra suit le mouvement de la flûte, qu'il prend pour une menace. Beaucoup ont les crochets arrachés avant le spectacle."},
{t:'animaux',v:0,s:"Les hérissons peuvent tirer des fruits avec leurs piquants.",
 e:"L'image vient d'un texte de Pline l'Ancien, recopié pendant quinze siècles. Aucun hérisson observé ne l'a jamais fait — et il ne mange d'ailleurs pas de fruits, mais des insectes."},
{t:'animaux',v:0,s:"Un chat retombe toujours sur ses pattes.",
 e:"Il se retourne en une fraction de seconde grâce à son oreille interne, mais il lui faut de la hauteur : sous un mètre, il n'a pas le temps. Les vétérinaires voient surtout des chats blessés lors de chutes courtes."},
{t:'espace',v:1,s:"Le noyau de la Terre est aussi chaud que la surface du Soleil.",
 e:"Environ 5 200 °C, contre 5 500 pour la photosphère solaire. Il reste solide malgré cela, écrasé par une pression de trois millions et demi d'atmosphères qui empêche le fer de fondre."},
{t:'espace',v:1,s:"Une tempête fait rage sur Jupiter depuis au moins trois siècles.",
 e:"La Grande Tache rouge est observée sans interruption depuis 1830, et probablement décrite dès 1665. Elle a longtemps fait trois fois la Terre ; elle rétrécit depuis quarante ans sans qu'on sache pourquoi."},
{t:'espace',v:1,s:"Il existe un endroit de l'espace où l'on peut garer un satellite sans effort.",
 e:"Les points de Lagrange, où les gravités de deux corps s'équilibrent. Le télescope James-Webb est installé au point L2, à un million et demi de kilomètres, et n'a qu'à corriger sa position de temps en temps."},
{t:'espace',v:1,s:"Le premier être vivant envoyé en orbite n'en est jamais revenu, et c'était prévu.",
 e:"Laïka, en 1957. La capsule n'avait aucun système de retour. L'Union soviétique a longtemps affirmé qu'elle avait vécu une semaine ; on a appris en 2002 qu'elle était morte de surchauffe en quelques heures."},
{t:'espace',v:1,s:"On a envoyé un disque de musique vers les étoiles.",
 e:"Les sondes Voyager emportent un disque doré : des salutations en cinquante-cinq langues, des bruits de la Terre, et de Bach à Chuck Berry. Il faudra 40 000 ans pour approcher une autre étoile."},
{t:'espace',v:0,s:"On peut voir les étoiles en plein jour depuis le fond d'un puits.",
 e:"Aristote le croyait, et l'idée a traversé les siècles. Le ciel diurne reste plus lumineux que les étoiles, quel que soit l'angle de vue. Un puits n'y change rien, il ne fait que réduire l'éblouissement."},
{t:'espace',v:0,s:"Une comète a une queue qui la suit dans son mouvement.",
 e:"La queue est toujours à l'opposé du Soleil, poussée par le vent solaire. Quand la comète repart, sa queue la précède donc. Ce détail a longtemps intrigué les astronomes avant qu'on comprenne le mécanisme."},
{t:'espace',v:0,s:"La ceinture d'astéroïdes est un champ de rochers qu'il faut slalomer.",
 e:"Ses objets sont séparés en moyenne d'un million de kilomètres. Toutes les sondes l'ont traversée sans manœuvre particulière. Le risque de collision est d'environ un sur un milliard."},
{t:'geo',v:1,s:"Le fleuve Amazone n'a aucun pont sur tout son cours principal.",
 e:"Plus de six mille kilomètres sans un seul pont routier. Les rives sont marécageuses, les crues déplacent le lit de plusieurs kilomètres, et la population circule de toute façon en bateau."},
{t:'geo',v:1,s:"L'Islande crée régulièrement de nouvelles îles.",
 e:"Surtsey a émergé en 1963 sous les yeux d'un équipage de pêche, et grandi pendant quatre ans. Elle est interdite au public depuis : les biologistes y observent la colonisation d'une terre vierge, en direct."},
{t:'geo',v:1,s:"Une ville russe reçoit du jour vingt-quatre heures sur vingt-quatre pendant deux mois.",
 e:"Mourmansk, au-delà du cercle polaire. En contrepartie, le Soleil ne se lève plus du tout du 2 décembre au 11 janvier — un événement local suffisamment attendu pour qu'on le fête."},
{t:'geo',v:1,s:"Le plus grand organisme vivant du monde est un champignon.",
 e:"Une armillaire de l'Oregon s'étend sur neuf kilomètres carrés et pèse peut-être 35 000 tonnes. Elle a entre deux et huit mille ans et tue lentement la forêt qui la recouvre."},
{t:'geo',v:1,s:"Certaines frontières suivent une ligne tracée à la règle sur une carte.",
 e:"La frontière entre les États-Unis et le Canada suit le 49ᵉ parallèle sur 2 030 kilomètres. En Afrique, ces lignes droites héritées des découpages coloniaux traversent des peuples entiers."},
{t:'geo',v:0,s:"La Mer Morte est la mer la plus salée du monde.",
 e:"Le lac Don Juan, en Antarctique, est trois fois plus salé et ne gèle pas à moins cinquante degrés. La Mer Morte reste la plus salée des grandes étendues d'eau accessibles."},
{t:'geo',v:0,s:"Le mont Everest grandit d'un mètre par an.",
 e:"Il gagne environ quatre millimètres par an, poussé par la collision entre l'Inde et l'Asie. Les séismes peuvent le faire varier brutalement : celui de 2015 lui a fait perdre quelques centimètres."},
{t:'geo',v:0,s:"L'Australie est le plus grand pays de l'hémisphère sud.",
 e:"Le Brésil est plus vaste de 800 000 kilomètres carrés. L'Australie est en revanche le seul pays à occuper un continent entier, ce qui trouble souvent la comparaison."},
{t:'histo',v:1,s:"Un cimetière anglais a été déplacé pour construire une gare, par un jeune écrivain.",
 e:"Thomas Hardy, avant d'être romancier, était apprenti architecte. Il a supervisé l'exhumation d'un cimetière londonien en 1865 et empilé les pierres tombales autour d'un frêne — l'arbre est toujours là."},
{t:'histo',v:1,s:"On a peint des paysages sur les avions de la Seconde Guerre mondiale pour les cacher depuis le sol.",
 e:"Le camouflage dazzle allait plus loin : les navires étaient peints de bandes contrastées non pour disparaître, mais pour rendre impossible l'estimation de leur cap et de leur vitesse au périscope."},
{t:'histo',v:1,s:"Le président américain le plus court en fonction est mort d'un discours trop long.",
 e:"William Henry Harrison a parlé deux heures sous la pluie glacée en 1841, sans manteau. Il est mort trente et un jours plus tard. Les historiens penchent aujourd'hui pour une eau contaminée à la Maison-Blanche."},
{t:'histo',v:1,s:"Les Romains se lavaient les dents avec de l'urine.",
 e:"L'urine portugaise, réputée la plus forte, se vendait cher. L'ammoniac qu'elle libère est un excellent détartrant — c'est le même principe que dans nos produits ménagers, avec un parfum discutable."},
{t:'histo',v:1,s:"Un empereur romain a nommé son cheval sénateur.",
 e:"L'histoire vient de Suétone, écrite quatre-vingts ans après. Caligula a bien couvert Incitatus de privilèges, mais l'anecdote du sénat était peut-être une provocation calculée : montrer que la fonction ne valait plus rien."},
{t:'histo',v:0,s:"Les chevaliers étaient si lourdement armés qu'il fallait une grue pour les hisser à cheval.",
 e:"Une armure complète pèse vingt-cinq kilos, répartis sur tout le corps — moins que le barda d'un soldat moderne. Des reconstitutions montrent des chevaliers courant, sautant et se relevant seuls."},
{t:'histo',v:0,s:"Les gens du Moyen Âge ne se lavaient jamais.",
 e:"Les bains publics étaient partout, et Paris en comptait des dizaines au XIIIᵉ siècle. C'est la peur de la contagion, après les épidémies de peste, qui les a fermés — la saleté est plutôt une invention de la Renaissance."},
{t:'histo',v:0,s:"Les pyramides ont été construites en trois cents ans.",
 e:"Celle de Khéops a demandé une vingtaine d'années. C'est l'ensemble des pyramides d'Égypte, sur mille ans de dynasties, qui donne cette impression de chantier interminable."},
{t:'sci',v:1,s:"Le corps humain remplace la quasi-totalité de ses atomes en quelques années.",
 e:"Les tissus se renouvellent à des rythmes très différents : quelques jours pour l'intestin, dix ans pour l'os. Certains neurones et le cristallin de l'œil, eux, vous accompagnent depuis la naissance."},
{t:'sci',v:1,s:"Il existe une couleur que l'on ne peut pas voir en peinture.",
 e:"Le magenta n'a pas de longueur d'onde : le cerveau l'invente quand l'œil reçoit du rouge et du bleu sans vert. C'est une couleur entièrement fabriquée, une convention du cerveau pour boucler le cercle chromatique."},
{t:'sci',v:1,s:"Les bébés naissent avec plus d'os que les adultes.",
 e:"Environ trois cents à la naissance, contre deux cent six ensuite. Le crâne est en plusieurs morceaux pour franchir le bassin, et de nombreux os fusionnent jusqu'à vingt-cinq ans."},
{t:'sci',v:1,s:"Le fer de votre sang vient de l'explosion d'une étoile.",
 e:"Tout élément plus lourd que le fer est né dans une supernova ou une collision d'étoiles à neutrons. Le calcium de vos os et le fer de votre sang ont voyagé des milliards d'années avant de vous constituer."},
{t:'sci',v:1,s:"On peut fabriquer du verre avec un éclair et du sable.",
 e:"Les fulgurites sont des tubes de verre créés quand la foudre frappe une dune : le sable fond instantanément autour du canal de décharge. On en trouve de plusieurs mètres de long."},
{t:'sci',v:0,s:"Le cerveau gauche est logique et le droit créatif.",
 e:"L'imagerie montre les deux hémisphères actifs pour presque toute tâche. Certaines fonctions sont bien latéralisées — le langage surtout — mais aucune personnalité ne se range dans un côté du crâne."},
{t:'sci',v:0,s:"Les vaccins contiennent du mercure dangereux.",
 e:"Certains ont contenu du thiomersal, un composé d'éthylmercure éliminé en quelques jours, sans rapport avec le méthylmercure qui s'accumule. Il a été retiré par précaution, et rien n'a changé dans les statistiques."},
{t:'sci',v:0,s:"On perd de la chaleur plus vite dans l'eau que dans l'air à cause de la température.",
 e:"C'est la conductivité qui décide : l'eau évacue la chaleur vingt-cinq fois plus vite que l'air à température identique. On grelotte à 20 °C dans l'eau et on est bien à 20 °C dehors."},
{t:'sci',v:0,s:"Le sucre nourrit les cellules cancéreuses, il faut donc l'éviter absolument.",
 e:"Toutes les cellules consomment du glucose, et le corps en fabrique même sans sucre alimentaire. Priver un patient de sucre affame surtout le patient — c'est un des conseils les plus dangereux qui circulent."},
{t:'wtf',v:1,s:"Une pieuvre s'est évadée d'un aquarium par un tuyau d'évacuation pour rejoindre la mer.",
 e:"Inky, en Nouvelle-Zélande, en 2016. Il a soulevé le couvercle mal fermé, traversé quatre mètres de sol et s'est glissé dans un conduit de quinze centimètres menant à l'océan. Personne ne l'a revu."},
{t:'wtf',v:1,s:"Un homme a construit une réplique de la tour Eiffel avec des allumettes pendant huit ans.",
 e:"Le record homologué en 2024 dépasse sept mètres et sept millions d'allumettes. Le premier essai avait été refusé parce que le constructeur avait gratté les têtes — le règlement exigeait des allumettes entières."},
{t:'wtf',v:1,s:"Un pays a offert un million de dollars à qui résoudrait un problème de mathématiques.",
 e:"Sept problèmes, un million chacun, par l'institut Clay depuis 2000. Un seul a été résolu ; Grigori Perelman a refusé l'argent et la médaille Fields, et s'est retiré de la vie mathématique."},
{t:'wtf',v:1,s:"Une entreprise a déposé un brevet sur une méthode pour se balancer sur une balançoire.",
 e:"L'office américain l'a accordé en 2002 à un enfant de cinq ans, dont le père était examinateur de brevets et voulait montrer les failles du système. Le brevet a été annulé après le scandale."},
{t:'wtf',v:1,s:"Un train a été construit pour un seul passager, et roule encore.",
 e:"Au Japon, la gare de Kyū-Shirataki est restée ouverte trois ans pour une lycéenne, jusqu'à son diplôme en 2016. Le train s'arrêtait deux fois par jour, uniquement à ses horaires de cours."},
{t:'wtf',v:0,s:"Un homme a fait le tour du monde à pied sans jamais prendre de bateau.",
 e:"Aucun itinéraire terrestre ne permet de boucler le globe : il faut franchir des océans. Les marcheurs homologués prennent des cargos, ce que le règlement autorise à condition de ne pas gagner de distance."},
{t:'wtf',v:0,s:"Les Jeux olympiques n'ont jamais été annulés depuis leur création moderne.",
 e:"Ils l'ont été trois fois pour cause de guerre : 1916, 1940 et 1944. Ceux de 2020 ont été reportés d'un an, une première — et ont conservé leur nom malgré la date."},
{t:'wtf',v:0,s:"Il existe un pays sans aucun impôt.",
 e:"Plusieurs se passent d'impôt sur le revenu — Monaco, les Émirats — mais tous prélèvent autrement : taxes sur les entreprises, droits de douane, rentes pétrolières. Un État sans aucune recette n'existe pas."},
{t:'cuisine',v:1,s:"Le maïs actuel n'existe pas à l'état sauvage.",
 e:"Il descend de la téosinte, une herbe à cinq grains durs par épi. Neuf mille ans de sélection ont produit une plante incapable de se ressemer seule : sans les humains, le maïs disparaîtrait en une génération."},
{t:'cuisine',v:1,s:"La vanille était autrefois impossible à cultiver hors du Mexique.",
 e:"Seule une abeille mexicaine la pollinisait. En 1841, un esclave de douze ans de La Réunion, Edmond Albius, a trouvé le geste manuel qu'on utilise encore aujourd'hui, sur toutes les plantations du monde."},
{t:'cuisine',v:1,s:"Le fromage le plus cher du monde est fait avec du lait d'âne.",
 e:"Le pule serbe demande vingt-cinq litres de lait d'ânesse pour un kilo, et l'ânesse doit être trait à la main trois fois par jour. Il se vend autour de mille euros le kilo."},
{t:'cuisine',v:1,s:"Le pain complet a longtemps été le pain des pauvres.",
 e:"Le blanc, débarrassé du son par un blutage coûteux, marquait le rang social. L'inversion est récente : c'est la nutrition du XXᵉ siècle qui a fait du son une valeur, et du pain blanc un produit ordinaire."},
{t:'cuisine',v:0,s:"Le champagne se conserve mieux avec une cuillère dans le goulot.",
 e:"Des tests en aveugle n'ont montré aucune différence : la cuillère ne bloque rien. Ce qui ralentit la perte de bulles, c'est le froid — une bouteille au réfrigérateur tient mieux qu'une bouteille cuillérée à température."},
{t:'cuisine',v:0,s:"Le micro-ondes cuit les aliments de l'intérieur vers l'extérieur.",
 e:"Les ondes pénètrent d'un à deux centimètres et agitent les molécules d'eau en surface ; le reste chauffe par conduction, comme dans une poêle. Un gros morceau reste froid au centre pour cette raison exacte."},
{t:'techno',v:1,s:"Le premier nom de domaine enregistré appartient à une entreprise disparue.",
 e:"symbolics.com, en mars 1985. La société fabriquait des machines pour le langage Lisp et a fermé ; le domaine a été racheté en 2009 par un investisseur qui en a fait un musée de lui-même."},
{t:'techno',v:1,s:"Un bug logiciel a fait exploser une fusée européenne en quarante secondes.",
 e:"Ariane 5, en 1996. Un nombre trop grand pour la variable qui l'accueillait, dans un module recopié d'Ariane 4 sans être testé. Le vol inaugural et ses quatre satellites, 370 millions de dollars, ont été perdus."},
{t:'techno',v:1,s:"Une image peut contenir un texte invisible sans qu'on le voie.",
 e:"La stéganographie modifie le dernier bit de chaque pixel : la couleur change d'un ton imperceptible et le fichier transporte un message. Une photo ordinaire peut ainsi cacher plusieurs pages de texte."},
{t:'techno',v:0,s:"Le wifi est dangereux pour la santé à cause de ses ondes.",
 e:"Ce sont des ondes non ionisantes, mille fois moins puissantes qu'un téléphone collé à l'oreille et incapables de casser une liaison chimique. Les études de grande ampleur n'ont rien trouvé, ce qui n'interdit pas de continuer à mesurer."},
{t:'techno',v:0,s:"Les ordinateurs quantiques sont simplement des ordinateurs plus rapides.",
 e:"Ils sont plus lents pour presque tout. Leur intérêt tient à une poignée de problèmes — factorisation, simulation moléculaire — où ils changent la nature du calcul. Sur un tableur, un ordinateur ordinaire les bat largement."},
{t:'sport',v:1,s:"Un pays a gagné une médaille olympique sans jamais avoir de piscine.",
 e:"Éric Moussambani, nageur de Guinée équatoriale, s'était entraîné dans un hôtel. Il n'a pas eu de médaille en 2000, mais son 100 mètres nagé seul, en plus du double du temps des autres, reste l'un des moments les plus applaudis des Jeux."},
{t:'sport',v:1,s:"Le premier vainqueur du Tour de France a été disqualifié l'année suivante pour avoir pris le train.",
 e:"Maurice Garin, vainqueur en 1903, a été déclassé en 1904 avec les trois suivants au classement. La tricherie était générale : raccourcis en voiture, clous semés, spectateurs qui bloquaient les rivaux."},
{t:'sport',v:0,s:"Le record du monde du 100 mètres a toujours été battu par un sprinteur américain ou jamaïcain.",
 e:"Le Canadien Donovan Bailey, l'Allemand Armin Hary et le Français Christophe Lemaitre ont tous marqué l'histoire du sprint. La domination actuelle est réelle mais récente, pas éternelle."},
{t:'pop',v:1,s:"Le rôle principal d'un film à succès a été refusé par presque tous les acteurs pressentis.",
 e:"Le rôle de Neo dans Matrix a été proposé à Will Smith, qui a tourné Wild Wild West à la place, puis à Nicolas Cage et Brad Pitt. Will Smith a reconnu plus tard qu'il aurait gâché le film."},
{t:'pop',v:0,s:"Les acteurs des films muets étaient tous doublés par des musiciens en salle.",
 e:"La musique était live, jouée au piano ou par un orchestre, mais elle accompagnait — elle ne doublait personne. Les dialogues passaient par des cartons, et les acteurs disaient souvent n'importe quoi devant la caméra."},
{t:'art',v:1,s:"Un musée a exposé pendant quarante-sept jours un tableau à l'envers sans que personne ne le remarque.",
 e:"Le Bateau de Matisse, au Musée d'art moderne de New York en 1961. Une visiteuse habituée a fini par signaler l'erreur. Cent seize mille personnes étaient passées devant."},
{t:'art',v:0,s:"Les peintres de la Renaissance utilisaient déjà la peinture à l'huile depuis l'Antiquité.",
 e:"L'huile s'impose au XVᵉ siècle avec les Flamands, qui découvrent qu'elle sèche assez lentement pour permettre les retouches et les glacis. Avant, on peignait a tempera, à l'œuf, et il fallait décider vite."},
{t:'langue',v:1,s:"Le mot « bug » informatique existait avant l'informatique.",
 e:"Edison l'employait déjà en 1878 pour les défauts de ses appareils. Le papillon collé dans le journal du Harvard Mark II en 1947 n'a pas créé le mot : la note précise « premier cas réel de bug », ce qui suppose que le terme circulait."},
{t:'langue',v:0,s:"Le français est la langue la plus précise du monde, c'est pourquoi la diplomatie l'utilise.",
 e:"Aucune langue n'est mesurablement plus précise qu'une autre. Le français doit son statut diplomatique à la puissance de la France aux XVIIᵉ et XVIIIᵉ siècles, et l'a largement perdu depuis 1919."},
{t:'musique',v:1,s:"Un enregistrement de Bach voyage actuellement hors du système solaire.",
 e:"Trois morceaux de Bach figurent sur le disque des sondes Voyager. Le biologiste Lewis Thomas avait suggéré de n'envoyer que du Bach, en ajoutant que ce serait se vanter."},
{t:'musique',v:0,s:"Le diable a été interdit en musique : le triton était puni par l'Église.",
 e:"Aucun texte n'interdit l'intervalle. Les traités de contrepoint le déconseillent parce qu'il est difficile à chanter juste. Le surnom de diabolus in musica est un raccourci pédagogique devenu légende."},
{t:'litt',v:1,s:"Un auteur a écrit un roman entier sur une machine à écrire louée à l'heure.",
 e:"Jack Kerouac a tapé Sur la route en trois semaines sur un rouleau de papier long de trente-six mètres, collé bout à bout pour ne pas avoir à changer de feuille. Le rouleau original a été vendu 2,4 millions de dollars."},
{t:'litt',v:0,s:"Les auteurs classiques écrivaient sans jamais corriger leurs manuscrits.",
 e:"Les manuscrits de Flaubert sont noirs de ratures : il pouvait passer une semaine sur une page. Proust ajoutait des béquets de papier collés qui déplient certaines pages sur un mètre."},
];
