/* =========================================================
   NO WAY! — banque de « Classe-les »
   Le joueur remet quatre éléments dans le bon ordre.
   Structure : {t, c, mes, u, i:[{l, v}], rev}
     t   = thème
     c   = la consigne, qui doit se suffire à elle-même
     mes = ce qu'on compare exactement, affiché SOUS la consigne,
           avant de répondre. « Le plus d'eau » ne veut rien dire
           tant qu'on n'a pas dit « en part du poids » ou « en litres ».
     u   = l'unité, affichée avec les valeurs à la révélation
     i   = les quatre éléments, dans un ordre quelconque
     rev = 1 quand l'ordre attendu va du PLUS PETIT au plus grand
           (par défaut : du plus grand au plus petit)
   Les écarts sont choisis pour qu'au moins une paire soit
   contre-intuitive — sans quoi il n'y a rien à jouer.
   Chargé avant index.html ; expose la globale `CLASSEMENTS`.
   ========================================================= */
const CLASSEMENTS=[

/* ---------- animaux ---------- */
{t:'animaux',c:"Du plus rapide au plus lent",mes:"pointe de vitesse en course",u:"km/h",
 i:[{l:"Guépard",v:110},{l:"Cheval de course",v:70},{l:"Crocodile marin",v:17},{l:"Ours brun",v:48}]},
{t:'animaux',c:"Du plus lourd au plus léger",mes:"masse d'un adulte",u:"kg",
 i:[{l:"Baleine bleue",v:150000},{l:"Éléphant d'Afrique",v:6000},{l:"Girafe",v:1200},{l:"Ours polaire",v:500}]},
{t:'animaux',c:"De la plus longue vie à la plus courte",mes:"espérance de vie",u:"ans",
 i:[{l:"Tortue des Galápagos",v:150},{l:"Éléphant",v:70},{l:"Chat",v:15},{l:"Souris",v:2}]},
{t:'animaux',c:"Du plus de cœurs au moins de cœurs",mes:"nombre de cœurs dans le corps",u:"cœurs",
 i:[{l:"Ver de terre",v:5},{l:"Pieuvre",v:3},{l:"Humain",v:1},{l:"Éponge de mer",v:0}]},
{t:'animaux',c:"De la gestation la plus longue à la plus courte",mes:"durée de la grossesse",u:"jours",
 i:[{l:"Éléphant",v:645},{l:"Baleine bleue",v:340},{l:"Chien",v:63},{l:"Hamster",v:16}]},
{t:'animaux',c:"Du meilleur sauteur au moins bon",mes:"hauteur du saut, en multiples de sa propre taille",u:"× sa taille",
 i:[{l:"Puce",v:100},{l:"Sauterelle",v:20},{l:"Kangourou",v:2},{l:"Humain",v:1}]},
{t:'animaux',c:"Du cerveau le plus lourd au plus léger",mes:"masse du cerveau seul",u:"g",
 i:[{l:"Cachalot",v:7800},{l:"Éléphant",v:5000},{l:"Humain",v:1400},{l:"Chat",v:30}]},
{t:'animaux',c:"Du plus grand au plus petit",mes:"taille d'un adulte, du sol au sommet",u:"m",
 i:[{l:"Girafe",v:5.5},{l:"Éléphant d'Afrique",v:3.3},{l:"Ours polaire debout",v:2.6},{l:"Autruche",v:2.4}]},

/* ---------- géographie ---------- */
{t:'geo',c:"Du pays le plus peuplé au moins peuplé",mes:"nombre d'habitants",u:"millions d'habitants",
 i:[{l:"Inde",v:1430},{l:"États-Unis",v:340},{l:"Brésil",v:216},{l:"France",v:68}]},
{t:'geo',c:"Du pays le plus vaste au moins vaste",mes:"superficie totale",u:"millions de km²",
 i:[{l:"Russie",v:17.1},{l:"Canada",v:10},{l:"Brésil",v:8.5},{l:"Inde",v:3.3}]},
{t:'geo',c:"Du sommet le plus haut au moins haut",mes:"altitude au-dessus du niveau de la mer",u:"m",
 i:[{l:"Everest",v:8849},{l:"Kilimandjaro",v:5895},{l:"Mont Blanc",v:4806},{l:"Fuji",v:3776}]},
{t:'geo',c:"Du fleuve le plus long au plus court",mes:"longueur du cours d'eau",u:"km",
 i:[{l:"Nil",v:6650},{l:"Amazone",v:6400},{l:"Mississippi",v:3766},{l:"Danube",v:2850}]},
{t:'geo',c:"De la plus grande profondeur d'eau à la plus faible",mes:"point le plus profond sous la surface",u:"m",
 i:[{l:"Fosse des Mariannes",v:10935},{l:"Mer Méditerranée",v:5267},{l:"Lac Baïkal",v:1642},{l:"Mer Baltique",v:459}]},
{t:'geo',c:"De la ville la plus au nord à la plus au sud",mes:"latitude",u:"° nord",
 i:[{l:"Oslo",v:59.9},{l:"Paris",v:48.9},{l:"New York",v:40.7},{l:"Le Caire",v:30}]},
{t:'geo',c:"Du désert le plus vaste au plus petit",mes:"superficie",u:"millions de km²",
 i:[{l:"Antarctique",v:14},{l:"Sahara",v:9.2},{l:"Désert d'Arabie",v:2.3},{l:"Gobi",v:1.3}]},
{t:'geo',c:"Du pays au plus de fuseaux horaires au moins",mes:"fuseaux horaires, outre-mer compris",u:"fuseaux",
 i:[{l:"France",v:12},{l:"Russie",v:11},{l:"États-Unis",v:6},{l:"Brésil",v:4}]},
{t:'geo',c:"De l'île la plus vaste à la moins vaste",mes:"superficie de l'île",u:"km²",
 i:[{l:"Groenland",v:2166000},{l:"Madagascar",v:587000},{l:"Grande-Bretagne",v:209000},{l:"Islande",v:103000}]},

/* ---------- espace ---------- */
{t:'espace',c:"De la planète la plus grosse à la plus petite",mes:"diamètre à l'équateur",u:"km",
 i:[{l:"Jupiter",v:139820},{l:"Saturne",v:116460},{l:"Terre",v:12742},{l:"Mars",v:6779}]},
{t:'espace',c:"De la plus chaude à la plus froide",mes:"température moyenne au sol",u:"°C",
 i:[{l:"Vénus",v:465},{l:"Mercure, côté jour",v:430},{l:"Terre",v:15},{l:"Mars",v:-63}]},
{t:'espace',c:"Du plus loin du Soleil au plus proche",mes:"distance moyenne au Soleil",u:"millions de km",
 i:[{l:"Neptune",v:4500},{l:"Jupiter",v:778},{l:"Mars",v:228},{l:"Vénus",v:108}]},
{t:'espace',c:"Du tour sur soi-même le plus lent au plus rapide",mes:"durée d'une rotation de la planète sur elle-même",u:"heures terrestres",
 i:[{l:"Vénus",v:5832},{l:"Mercure",v:1408},{l:"Mars",v:24.6},{l:"Jupiter",v:9.9}]},
{t:'espace',c:"Du plus ancien au plus récent",mes:"année de l'événement",u:"",rev:1,
 i:[{l:"Spoutnik",v:1957},{l:"Premier homme dans l'espace",v:1961},{l:"Apollo 11",v:1969},{l:"Station spatiale internationale",v:1998}]},
{t:'espace',c:"Du plus massif au moins massif",mes:"masse, comparée à celle de la Terre",u:"× la Terre",
 i:[{l:"Soleil",v:333000},{l:"Jupiter",v:318},{l:"Neptune",v:17},{l:"Lune",v:0.012}]},

/* ---------- sciences ---------- */
{t:'sci',c:"Du plus chaud au plus froid",mes:"température",u:"°C",
 i:[{l:"Éclair",v:30000},{l:"Surface du Soleil",v:5500},{l:"Lave",v:1200},{l:"Four de cuisine",v:250}]},
{t:'sci',c:"Du plus rapide au plus lent",mes:"vitesse de déplacement",u:"km/h",
 i:[{l:"Lumière",v:1080000000},{l:"Son dans l'air",v:1235},{l:"Avion de ligne",v:900},{l:"Guépard",v:110}]},
{t:'sci',c:"Du plus dense au moins dense",mes:"masse d'un centimètre cube",u:"g/cm³",
 i:[{l:"Or",v:19.3},{l:"Fer",v:7.9},{l:"Eau",v:1},{l:"Liège",v:0.24}]},
{t:'sci',c:"De la cellule qui vit le plus longtemps à celle qui vit le moins",mes:"durée de vie d'une cellule avant renouvellement",u:"jours",
 i:[{l:"Globule rouge",v:120},{l:"Cellule de peau",v:35},{l:"Cellule d'estomac",v:4},{l:"Globule blanc",v:1}]},
{t:'sci',c:"Du plus petit au plus grand",mes:"taille de l'objet",u:"nanomètres",rev:1,
 i:[{l:"Atome",v:0.1},{l:"Molécule d'ADN, en largeur",v:2},{l:"Virus",v:100},{l:"Bactérie",v:2000}]},
{t:'sci',c:"Du plus riche en eau au moins riche",mes:"part d'eau dans le poids total, en pourcentage",u:"% du poids",
 i:[{l:"Méduse",v:97},{l:"Concombre",v:96},{l:"Nouveau-né",v:78},{l:"Adulte",v:60}]},
{t:'sci',c:"Du plus bruyant au moins bruyant",mes:"niveau sonore mesuré à courte distance",u:"décibels",
 i:[{l:"Décollage d'avion",v:140},{l:"Marteau-piqueur",v:110},{l:"Aspirateur",v:70},{l:"Conversation",v:60}]},

/* ---------- histoire ---------- */
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de construction",u:"",rev:1,
 i:[{l:"Pyramide de Khéops",v:-2560},{l:"Grande Muraille, premiers tronçons",v:-220},{l:"Colisée",v:80},{l:"Tour Eiffel",v:1889}]},
{t:'histo',c:"Du règne le plus long au plus court",mes:"durée passée sur le trône",u:"ans de règne",
 i:[{l:"Louis XIV",v:72},{l:"Élisabeth II",v:70},{l:"Victoria",v:63},{l:"Napoléon Iᵉʳ",v:10}]},
{t:'histo',c:"De la plus ancienne invention à la plus récente",mes:"année de l'invention",u:"",rev:1,
 i:[{l:"Imprimerie",v:1450},{l:"Machine à vapeur",v:1712},{l:"Téléphone",v:1876},{l:"Internet",v:1969}]},
{t:'histo',c:"De la guerre la plus longue à la plus courte",mes:"durée du conflit",u:"années",
 i:[{l:"Guerre de Cent Ans",v:116},{l:"Guerre de Trente Ans",v:30},{l:"Seconde Guerre mondiale",v:6},{l:"Guerre des Six Jours",v:0.02}]},
{t:'histo',c:"De la civilisation la plus ancienne à la plus récente",mes:"année où elle apparaît",u:"",rev:1,
 i:[{l:"Sumer",v:-4000},{l:"Égypte pharaonique",v:-3100},{l:"Rome",v:-753},{l:"Empire aztèque",v:1325}]},

/* ---------- techno ---------- */
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de la première mise en service",u:"",rev:1,
 i:[{l:"Premier courriel",v:1971},{l:"Premier site web",v:1991},{l:"Premier iPhone",v:2007},{l:"ChatGPT",v:2022}]},
{t:'techno',c:"De la plus grande capacité de mémoire à la plus petite",mes:"quantité de données stockables",u:"octets",
 i:[{l:"Téléphone courant",v:256000000000},{l:"Disquette",v:1440000},{l:"Ordinateur d'Apollo 11",v:4096},{l:"Carte perforée",v:80}]},
{t:'techno',c:"Du réseau social au plus d'utilisateurs au moins",mes:"utilisateurs actifs par mois",u:"millions d'utilisateurs",
 i:[{l:"Facebook",v:3000},{l:"Instagram",v:2000},{l:"TikTok",v:1500},{l:"X",v:550}]},

/* ---------- cuisine ---------- */
{t:'cuisine',c:"Du plus calorique au moins calorique",mes:"calories pour 100 grammes",u:"kcal / 100 g",
 i:[{l:"Huile d'olive",v:900},{l:"Chocolat noir",v:550},{l:"Pain",v:265},{l:"Pomme",v:52}]},
{t:'cuisine',c:"Du plus piquant au plus doux",mes:"force du piment sur l'échelle de Scoville",u:"unités Scoville",
 i:[{l:"Carolina Reaper",v:2200000},{l:"Piment habanero",v:350000},{l:"Piment de Cayenne",v:40000},{l:"Piment d'Espelette",v:4000}]},
{t:'cuisine',c:"Du plus cher au moins cher",mes:"prix au kilo",u:"€ / kg",
 i:[{l:"Safran",v:15000},{l:"Truffe blanche",v:4000},{l:"Caviar",v:2500},{l:"Vanille",v:500}]},
{t:'cuisine',c:"Du plus sucré au moins sucré",mes:"sucre pour 100 grammes",u:"g / 100 g",
 i:[{l:"Miel",v:82},{l:"Confiture",v:60},{l:"Soda",v:11},{l:"Lait",v:5}]},

/* ---------- sport ---------- */
{t:'sport',c:"De la balle la plus rapide à la plus lente",mes:"vitesse record jamais mesurée pour cette balle",u:"km/h",
 i:[{l:"Volant de badminton",v:493},{l:"Balle de golf",v:340},{l:"Balle de tennis",v:263},{l:"Ballon de football",v:210}]},
{t:'sport',c:"Du terrain le plus long au plus court",mes:"longueur du terrain",u:"m",
 i:[{l:"Football",v:105},{l:"Rugby",v:100},{l:"Basket",v:28},{l:"Tennis",v:24}]},
{t:'sport',c:"Du plus de joueurs au moins de joueurs",mes:"joueurs d'une équipe sur le terrain",u:"joueurs",
 i:[{l:"Rugby à XV",v:15},{l:"Football",v:11},{l:"Handball",v:7},{l:"Basket",v:5}]},

/* ---------- pop, art, musique ---------- */
{t:'pop',c:"Du film le plus long au plus court",mes:"durée de projection",u:"minutes",
 i:[{l:"Autant en emporte le vent",v:238},{l:"Titanic",v:194},{l:"Le Parrain",v:175},{l:"Le Roi Lion",v:88}]},
{t:'art',c:"Du tableau le plus large au moins large",mes:"largeur de la toile",u:"cm",
 i:[{l:"Les Noces de Cana",v:990},{l:"Le Radeau de la Méduse",v:716},{l:"La Nuit étoilée",v:92},{l:"La Joconde",v:53}]},
{t:'musique',c:"De l'instrument le plus grave au plus aigu",mes:"fréquence de la note la plus basse qu'il peut jouer",u:"Hz",rev:1,
 i:[{l:"Piccolo",v:587},{l:"Violon",v:196},{l:"Violoncelle",v:65},{l:"Contrebasse",v:41}]},
{t:'musique',c:"De l'album le plus vendu au moins vendu",mes:"exemplaires vendus dans le monde",u:"millions d'exemplaires",
 i:[{l:"Thriller",v:70},{l:"Back in Black",v:50},{l:"The Dark Side of the Moon",v:45},{l:"Rumours",v:40}]},

/* ---------- langue et récits ---------- */
{t:'langue',c:"De la langue au plus de locuteurs natifs au moins",mes:"personnes dont c'est la langue maternelle",u:"millions de locuteurs",
 i:[{l:"Mandarin",v:940},{l:"Espagnol",v:485},{l:"Anglais",v:380},{l:"Français",v:80}]},
{t:'langue',c:"De l'alphabet au plus de lettres au moins",mes:"lettres dans l'alphabet",u:"lettres",
 i:[{l:"Khmer",v:74},{l:"Russe",v:33},{l:"Français",v:26},{l:"Hawaïen",v:13}]},
{t:'litt',c:"Du livre le plus vendu au moins vendu",mes:"exemplaires vendus depuis la parution",u:"millions d'exemplaires",
 i:[{l:"Don Quichotte",v:500},{l:"Le Seigneur des anneaux",v:150},{l:"Le Petit Prince",v:140},{l:"Harry Potter à l'école des sorciers",v:120}]},
{t:'litt',c:"Du plus ancien au plus récent",mes:"année de parution",u:"",rev:1,
 i:[{l:"L'Odyssée",v:-750},{l:"Don Quichotte",v:1605},{l:"Les Misérables",v:1862},{l:"1984, le roman",v:1949}]},
/* ---------- animaux ---------- */
{t:'animaux',c:"Du plus rapide au plus lent à la nage",mes:"vitesse de pointe dans l'eau",u:"km/h",
 i:[{l:"Espadon",v:100},{l:"Dauphin",v:60},{l:"Requin blanc",v:40},{l:"Manchot papou",v:36}]},
{t:'animaux',c:"Du plus rapide au plus lent en vol",mes:"vitesse de pointe en vol horizontal",u:"km/h",
 i:[{l:"Martinet à gorge blanche",v:169},{l:"Canard colvert",v:105},{l:"Frégate",v:95},{l:"Colibri",v:54}]},
{t:'animaux',c:"Du plus grand au plus petit",mes:"envergure des ailes déployées",u:"m",
 i:[{l:"Albatros hurleur",v:3.5},{l:"Condor des Andes",v:3.2},{l:"Pélican",v:2.8},{l:"Aigle royal",v:2.2}]},
{t:'animaux',c:"Du plus lourd au plus léger à la naissance",mes:"poids du petit à la naissance",u:"kg",
 i:[{l:"Baleine bleue",v:2700},{l:"Éléphant",v:100},{l:"Humain",v:3.3},{l:"Kangourou",v:0.001}]},
{t:'animaux',c:"Du plus grand nombre d'œufs au plus petit",mes:"œufs pondus en une fois",u:"œufs",
 i:[{l:"Poisson-lune",v:300000000},{l:"Grenouille rousse",v:2000},{l:"Tortue marine",v:110},{l:"Manchot empereur",v:1}]},
{t:'animaux',c:"Du plus long sommeil au plus court",mes:"heures de sommeil par jour",u:"h / jour",
 i:[{l:"Koala",v:20},{l:"Chat",v:15},{l:"Humain",v:8},{l:"Girafe",v:2}]},
{t:'animaux',c:"De la plus longue migration à la plus courte",mes:"distance parcourue en un aller-retour annuel",u:"km",
 i:[{l:"Sterne arctique",v:70000},{l:"Baleine à bosse",v:16000},{l:"Papillon monarque",v:4800},{l:"Cigogne blanche",v:4000}]},
{t:'animaux',c:"De la plus grande longévité à la plus courte",mes:"âge du plus vieux spécimen connu",u:"ans",
 i:[{l:"Éponge des abysses",v:11000},{l:"Requin du Groenland",v:400},{l:"Tortue géante",v:190},{l:"Perroquet gris",v:80}]},
{t:'animaux',c:"Du plus venimeux au moins venimeux",mes:"dose mortelle pour un humain, du plus petit volume au plus grand",u:"mg de venin nécessaire",rev:1,
 i:[{l:"Méduse-boîte",v:0.04},{l:"Cobra royal",v:15},{l:"Vipère aspic",v:60},{l:"Abeille",v:500}]},
{t:'animaux',c:"Du plus gros cœur au plus petit",mes:"masse du cœur",u:"kg",
 i:[{l:"Baleine bleue",v:180},{l:"Éléphant",v:20},{l:"Cheval",v:4},{l:"Humain",v:0.3}]},
{t:'animaux',c:"Du battement de cœur le plus rapide au plus lent",mes:"battements par minute au repos",u:"battements / min",
 i:[{l:"Colibri",v:1200},{l:"Souris",v:600},{l:"Humain",v:70},{l:"Baleine bleue",v:8}]},
{t:'animaux',c:"De la plus grande morsure à la plus faible",mes:"force de la mâchoire",u:"kg de pression",
 i:[{l:"Crocodile marin",v:1700},{l:"Hippopotame",v:1300},{l:"Lion",v:290},{l:"Humain",v:75}]},
{t:'animaux',c:"Du plus gros œuf au plus petit",mes:"masse de l'œuf",u:"g",
 i:[{l:"Autruche",v:1400},{l:"Émeu",v:600},{l:"Poule",v:60},{l:"Colibri",v:0.5}]},
{t:'animaux',c:"Du plus profond plongeur au moins profond",mes:"profondeur maximale atteinte",u:"m",
 i:[{l:"Cachalot",v:2250},{l:"Éléphant de mer",v:1500},{l:"Manchot empereur",v:565},{l:"Tortue verte",v:110}]},
{t:'animaux',c:"Du plus d'espèces au moins d'espèces",mes:"espèces décrites dans le groupe",u:"espèces",
 i:[{l:"Coléoptères",v:400000},{l:"Poissons",v:34000},{l:"Oiseaux",v:11000},{l:"Mammifères",v:6400}]},
{t:'animaux',c:"Du plus grand territoire au plus petit",mes:"surface parcourue par un individu",u:"km²",
 i:[{l:"Ours polaire",v:250000},{l:"Loup gris",v:1000},{l:"Lion",v:200},{l:"Renard roux",v:5}]},
{t:'animaux',c:"Du meilleur odorat au moins bon",mes:"récepteurs olfactifs dans le nez",u:"millions de récepteurs",
 i:[{l:"Chien de sang",v:300},{l:"Chien courant",v:220},{l:"Chat",v:80},{l:"Humain",v:6}]},
{t:'animaux',c:"Du plus grand groupe au plus petit",mes:"individus dans une colonie ou un troupeau typique",u:"individus",
 i:[{l:"Fourmilière",v:500000},{l:"Colonie de chauves-souris",v:20000},{l:"Troupeau de gnous",v:1500},{l:"Meute de loups",v:8}]},
{t:'animaux',c:"De la plus longue langue à la plus courte",mes:"longueur de la langue déployée",u:"cm",
 i:[{l:"Baleine bleue",v:550},{l:"Girafe",v:50},{l:"Fourmilier",v:45},{l:"Caméléon",v:30}]},
{t:'animaux',c:"Du plus de chromosomes au moins",mes:"nombre de chromosomes par cellule",u:"chromosomes",
 i:[{l:"Fougère Ophioglossum",v:1260},{l:"Chien",v:78},{l:"Humain",v:46},{l:"Moustique",v:6}]},

/* ---------- géographie ---------- */
{t:'geo',c:"De la ville la plus peuplée à la moins peuplée",mes:"habitants de l'agglomération",u:"millions d'habitants",
 i:[{l:"Tokyo",v:37},{l:"Le Caire",v:22},{l:"Paris",v:11},{l:"Berlin",v:3.6}]},
{t:'geo',c:"Du pays le plus densément peuplé au moins",mes:"habitants au kilomètre carré",u:"hab. / km²",
 i:[{l:"Bangladesh",v:1265},{l:"Pays-Bas",v:520},{l:"France",v:119},{l:"Australie",v:3}]},
{t:'geo',c:"Du plus long littoral au plus court",mes:"longueur des côtes",u:"km",
 i:[{l:"Canada",v:202080},{l:"Indonésie",v:54716},{l:"Australie",v:25760},{l:"France",v:4853}]},
{t:'geo',c:"Du lac le plus vaste au plus petit",mes:"superficie du plan d'eau",u:"km²",
 i:[{l:"Mer Caspienne",v:371000},{l:"Lac Supérieur",v:82100},{l:"Lac Victoria",v:68870},{l:"Lac Baïkal",v:31722}]},
{t:'geo',c:"De la chute d'eau la plus haute à la plus basse",mes:"hauteur de chute",u:"m",
 i:[{l:"Salto Ángel",v:979},{l:"Chutes Tugela",v:948},{l:"Chutes Victoria",v:108},{l:"Chutes du Niagara",v:51}]},
{t:'geo',c:"Du pays au plus de voisins au moins",mes:"pays frontaliers",u:"voisins",
 i:[{l:"Chine",v:14},{l:"Brésil",v:10},{l:"Allemagne",v:9},{l:"France",v:8}]},
{t:'geo',c:"De la plus forte chaleur au plus grand froid",mes:"température record enregistrée",u:"°C",
 i:[{l:"Vallée de la Mort",v:56.7},{l:"Kebili, Tunisie",v:55},{l:"Séville",v:47},{l:"Vostok, Antarctique",v:-89}]},
{t:'geo',c:"Du plus vieux pays au plus jeune",mes:"année d'indépendance ou de fondation",u:"",rev:1,
 i:[{l:"Saint-Marin",v:301},{l:"France",v:843},{l:"États-Unis",v:1776},{l:"Soudan du Sud",v:2011}]},
{t:'geo',c:"De l'aéroport le plus fréquenté au moins",mes:"passagers par an",u:"millions de passagers",
 i:[{l:"Atlanta",v:104},{l:"Dubaï",v:87},{l:"Paris-Charles-de-Gaulle",v:67},{l:"Genève",v:16}]},
{t:'geo',c:"Du plus vaste océan au plus petit",mes:"superficie",u:"millions de km²",
 i:[{l:"Pacifique",v:165},{l:"Atlantique",v:106},{l:"Indien",v:70},{l:"Arctique",v:14}]},
{t:'geo',c:"Du plus grand nombre de langues au plus petit",mes:"langues vivantes parlées dans le pays",u:"langues",
 i:[{l:"Papouasie-Nouvelle-Guinée",v:840},{l:"Indonésie",v:710},{l:"Inde",v:450},{l:"France",v:25}]},
{t:'geo',c:"De la plus grande forêt à la plus petite",mes:"superficie boisée",u:"millions de km²",
 i:[{l:"Taïga russe",v:12},{l:"Amazonie",v:5.5},{l:"Bassin du Congo",v:3.4},{l:"Forêt de Bornéo",v:0.4}]},
{t:'geo',c:"Du volcan le plus haut au plus bas",mes:"altitude du sommet",u:"m",
 i:[{l:"Ojos del Salado",v:6893},{l:"Kilimandjaro",v:5895},{l:"Etna",v:3357},{l:"Stromboli",v:924}]},
{t:'geo',c:"Du pont le plus long au plus court",mes:"longueur totale de l'ouvrage",u:"km",
 i:[{l:"Grand pont Danyang-Kunshan",v:164},{l:"Pont de la baie de Hangzhou",v:36},{l:"Pont de l'Øresund",v:16},{l:"Golden Gate",v:2.7}]},
{t:'geo',c:"Du métro le plus long au plus court",mes:"longueur totale du réseau",u:"km",
 i:[{l:"Shanghai",v:831},{l:"Pékin",v:807},{l:"Londres",v:402},{l:"Paris",v:226}]},
{t:'geo',c:"Du pays le plus arrosé au plus sec",mes:"précipitations moyennes par an",u:"mm / an",
 i:[{l:"Colombie",v:3240},{l:"Indonésie",v:2700},{l:"France",v:867},{l:"Égypte",v:51}]},
{t:'geo',c:"Du plus grand désert de sel au plus petit",mes:"superficie",u:"km²",
 i:[{l:"Salar d'Uyuni",v:10582},{l:"Bonneville",v:260},{l:"Salar d'Atacama",v:3000},{l:"Chott el-Jérid",v:5000}]},
{t:'geo',c:"De la plus haute capitale à la plus basse",mes:"altitude de la ville",u:"m",
 i:[{l:"La Paz",v:3640},{l:"Quito",v:2850},{l:"Mexico",v:2240},{l:"Paris",v:35}]},
{t:'geo',c:"Du fuseau le plus en avance au plus en retard",mes:"décalage par rapport au temps universel",u:"h UTC",
 i:[{l:"Kiribati",v:14},{l:"Tokyo",v:9},{l:"Paris",v:1},{l:"Hawaï",v:-10}]},
{t:'geo',c:"Du plus grand nombre d'îles au plus petit",mes:"îles recensées dans le pays",u:"îles",
 i:[{l:"Suède",v:267570},{l:"Norvège",v:239057},{l:"Finlande",v:178947},{l:"Indonésie",v:17508}]},

/* ---------- espace ---------- */
{t:'espace',c:"De la plus grosse lune à la plus petite",mes:"diamètre du satellite",u:"km",
 i:[{l:"Ganymède",v:5268},{l:"Titan",v:5150},{l:"Lune",v:3475},{l:"Europe",v:3122}]},
{t:'espace',c:"De l'année la plus longue à la plus courte",mes:"durée d'un tour complet autour du Soleil",u:"jours terrestres",
 i:[{l:"Neptune",v:60190},{l:"Saturne",v:10759},{l:"Mars",v:687},{l:"Mercure",v:88}]},
{t:'espace',c:"Du plus de lunes au moins",mes:"satellites naturels connus",u:"lunes",
 i:[{l:"Saturne",v:146},{l:"Jupiter",v:95},{l:"Uranus",v:28},{l:"Mars",v:2}]},
{t:'espace',c:"De la plus forte gravité à la plus faible",mes:"gravité en surface",u:"× celle de la Terre",
 i:[{l:"Jupiter",v:2.53},{l:"Terre",v:1},{l:"Mars",v:0.38},{l:"Lune",v:0.17}]},
{t:'espace',c:"De l'étoile la plus brillante à la moins brillante",mes:"éclat apparent vu de la Terre, du plus vif au plus faible",u:"magnitude",rev:1,
 i:[{l:"Sirius",v:-1.46},{l:"Canopus",v:-0.74},{l:"Véga",v:0.03},{l:"Étoile Polaire",v:1.98}]},
{t:'espace',c:"De la plus grosse étoile à la plus petite",mes:"diamètre",u:"× le Soleil",
 i:[{l:"UY Scuti",v:1700},{l:"Bételgeuse",v:900},{l:"Aldébaran",v:44},{l:"Soleil",v:1}]},
{t:'espace',c:"Du plus loin au plus proche de nous",mes:"distance à la Terre",u:"années-lumière",
 i:[{l:"Galaxie d'Andromède",v:2500000},{l:"Nébuleuse d'Orion",v:1344},{l:"Étoile Polaire",v:433},{l:"Proxima du Centaure",v:4.2}]},
{t:'espace',c:"De la mission la plus longue à la plus courte",mes:"durée du séjour dans l'espace",u:"jours",
 i:[{l:"Valeri Poliakov",v:437},{l:"Scott Kelly",v:340},{l:"Thomas Pesquet, second vol",v:199},{l:"Apollo 11",v:8}]},
{t:'espace',c:"Du plus grand télescope au plus petit",mes:"diamètre du miroir principal",u:"m",
 i:[{l:"Extremely Large Telescope",v:39},{l:"Gran Telescopio Canarias",v:10.4},{l:"James-Webb",v:6.5},{l:"Hubble",v:2.4}]},
{t:'espace',c:"De la plus longue journée à la plus courte",mes:"durée d'une rotation sur soi-même",u:"heures terrestres",
 i:[{l:"Pluton",v:153},{l:"Terre",v:24},{l:"Uranus",v:17},{l:"Saturne",v:10.7}]},
{t:'espace',c:"Du plus ancien au plus récent",mes:"année de lancement",u:"",rev:1,
 i:[{l:"Voyager 1",v:1977},{l:"Hubble",v:1990},{l:"Curiosity",v:2011},{l:"James-Webb",v:2021}]},
{t:'espace',c:"Du plus chaud au plus froid",mes:"température",u:"°C",
 i:[{l:"Cœur du Soleil",v:15000000},{l:"Surface du Soleil",v:5500},{l:"Vénus",v:465},{l:"Pluton",v:-229}]},

/* ---------- sciences ---------- */
{t:'sci',c:"Du plus abondant au plus rare dans l'univers",mes:"part de la matière ordinaire",u:"% des atomes",
 i:[{l:"Hydrogène",v:92},{l:"Hélium",v:7.8},{l:"Oxygène",v:0.06},{l:"Carbone",v:0.03}]},
{t:'sci',c:"Du point de fusion le plus haut au plus bas",mes:"température à laquelle le métal fond",u:"°C",
 i:[{l:"Tungstène",v:3422},{l:"Fer",v:1538},{l:"Aluminium",v:660},{l:"Mercure",v:-39}]},
{t:'sci',c:"Du plus dur au plus tendre",mes:"dureté sur l'échelle de Mohs",u:"sur 10",
 i:[{l:"Diamant",v:10},{l:"Quartz",v:7},{l:"Cuivre",v:3},{l:"Talc",v:1}]},
{t:'sci',c:"De la plus longue demi-vie à la plus courte",mes:"temps au bout duquel la moitié s'est désintégrée",u:"ans",
 i:[{l:"Uranium 238",v:4470000000},{l:"Carbone 14",v:5730},{l:"Césium 137",v:30},{l:"Iode 131",v:0.022}]},
{t:'sci',c:"Du plus long au plus court",mes:"longueur d'onde du rayonnement",u:"nanomètres",
 i:[{l:"Onde radio",v:1000000000},{l:"Infrarouge",v:10000},{l:"Lumière rouge",v:700},{l:"Rayon X",v:0.1}]},
{t:'sci',c:"Du plus lourd au plus léger",mes:"masse de la particule",u:"× l'électron",
 i:[{l:"Neutron",v:1839},{l:"Proton",v:1836},{l:"Muon",v:207},{l:"Électron",v:1}]},
{t:'sci',c:"Du son le plus rapide au plus lent",mes:"vitesse du son dans le milieu",u:"m/s",
 i:[{l:"Acier",v:5960},{l:"Eau",v:1480},{l:"Air",v:343},{l:"Caoutchouc",v:60}]},
{t:'sci',c:"Du plus acide au plus basique",mes:"pH, du plus bas au plus haut",u:"pH",rev:1,
 i:[{l:"Acide de batterie",v:0.5},{l:"Jus de citron",v:2},{l:"Eau pure",v:7},{l:"Ammoniaque",v:11.5}]},
{t:'sci',c:"Du plus grand organe au plus petit",mes:"masse de l'organe chez l'adulte",u:"g",
 i:[{l:"Peau",v:10000},{l:"Foie",v:1500},{l:"Cerveau",v:1400},{l:"Cœur",v:300}]},
{t:'sci',c:"Du plus long os au plus court",mes:"longueur de l'os",u:"cm",
 i:[{l:"Fémur",v:48},{l:"Tibia",v:43},{l:"Humérus",v:36},{l:"Étrier de l'oreille",v:0.3}]},
{t:'sci',c:"De la plus grande consommation d'énergie à la plus petite",mes:"part de l'énergie du corps au repos",u:"% de l'énergie",
 i:[{l:"Cerveau",v:20},{l:"Foie",v:19},{l:"Muscles",v:18},{l:"Reins",v:8}]},
{t:'sci',c:"Du plus de cellules au moins",mes:"cellules dans le corps humain",u:"milliards de cellules",
 i:[{l:"Globules rouges",v:25000},{l:"Cellules de peau",v:1600},{l:"Neurones",v:86},{l:"Cellules du foie",v:240}]},
{t:'sci',c:"Du plus rapide au plus lent",mes:"vitesse de transmission dans le nerf",u:"m/s",
 i:[{l:"Nerf moteur",v:120},{l:"Nerf du toucher",v:76},{l:"Nerf de la douleur vive",v:20},{l:"Nerf de la douleur sourde",v:1}]},
{t:'sci',c:"Du plus grand volume d'eau au plus petit",mes:"part de l'eau de la planète",u:"% de l'eau terrestre",
 i:[{l:"Océans",v:96.5},{l:"Glaciers",v:1.74},{l:"Nappes souterraines",v:1.69},{l:"Lacs et rivières",v:0.013}]},
{t:'sci',c:"De la plus forte pression à la plus faible",mes:"pression subie",u:"atmosphères",
 i:[{l:"Centre de la Terre",v:3600000},{l:"Fosse des Mariannes",v:1100},{l:"Bouteille de champagne",v:6},{l:"Niveau de la mer",v:1}]},

/* ---------- histoire ---------- */
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'événement",u:"",rev:1,
 i:[{l:"Chute de Rome",v:476},{l:"Découverte de l'Amérique",v:1492},{l:"Révolution française",v:1789},{l:"Chute du mur de Berlin",v:1989}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la mort du personnage",u:"",rev:1,
 i:[{l:"Jules César",v:-44},{l:"Charlemagne",v:814},{l:"Léonard de Vinci",v:1519},{l:"Napoléon",v:1821}]},
{t:'histo',c:"Du plus vaste empire au plus petit",mes:"superficie à son apogée",u:"millions de km²",
 i:[{l:"Empire britannique",v:35.5},{l:"Empire mongol",v:24},{l:"Empire russe",v:22.8},{l:"Empire romain",v:5}]},
{t:'histo',c:"De la plus longue durée au plus courte",mes:"durée de l'empire ou du royaume",u:"ans",
 i:[{l:"Empire romain d'Orient",v:1058},{l:"Empire ottoman",v:623},{l:"Empire romain d'Occident",v:503},{l:"Empire mongol",v:162}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la première utilisation",u:"",rev:1,
 i:[{l:"Roue",v:-3500},{l:"Écriture",v:-3200},{l:"Papier",v:105},{l:"Poudre à canon",v:850}]},
{t:'histo',c:"De la plus meurtrière à la moins meurtrière",mes:"morts estimés",u:"millions de morts",
 i:[{l:"Seconde Guerre mondiale",v:70},{l:"Peste noire",v:50},{l:"Grippe espagnole",v:40},{l:"Première Guerre mondiale",v:20}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de fondation de la ville",u:"",rev:1,
 i:[{l:"Damas",v:-4000},{l:"Athènes",v:-1400},{l:"Rome",v:-753},{l:"New York",v:1624}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'invention",u:"",rev:1,
 i:[{l:"Boussole",v:1040},{l:"Lunettes",v:1286},{l:"Microscope",v:1590},{l:"Vaccin",v:1796}]},
{t:'histo',c:"De la plus grande armée à la plus petite",mes:"soldats engagés dans la bataille",u:"soldats",
 i:[{l:"Stalingrad",v:2200000},{l:"Waterloo",v:190000},{l:"Austerlitz",v:158000},{l:"Azincourt",v:30000}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de construction du monument",u:"",rev:1,
 i:[{l:"Stonehenge",v:-2500},{l:"Parthénon",v:-438},{l:"Notre-Dame de Paris",v:1345},{l:"Taj Mahal",v:1653}]},

/* ---------- technologie ---------- */
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de la première version",u:"",rev:1,
 i:[{l:"Windows",v:1985},{l:"Linux",v:1991},{l:"Android",v:2008},{l:"ChatGPT",v:2022}]},
{t:'techno',c:"Du plus rapide au plus lent",mes:"débit de la connexion",u:"mégabits / s",
 i:[{l:"Fibre optique",v:1000},{l:"4G",v:100},{l:"ADSL",v:20},{l:"Modem 56k",v:0.056}]},
{t:'techno',c:"Du plus de transistors au moins",mes:"transistors dans la puce",u:"millions de transistors",
 i:[{l:"Apple M2 Ultra",v:134000},{l:"Pentium 4",v:42},{l:"Intel 486",v:1.2},{l:"Intel 4004",v:0.0023}]},
{t:'techno',c:"Du plus cher au moins cher au lancement",mes:"prix de sortie converti en euros d'aujourd'hui",u:"€",
 i:[{l:"Apple Lisa",v:25000},{l:"Macintosh 1984",v:7000},{l:"iPhone 2007",v:750},{l:"Raspberry Pi",v:35}]},
{t:'techno',c:"Du plus lourd au plus léger",mes:"masse de l'appareil",u:"kg",
 i:[{l:"ENIAC",v:27000},{l:"Premier téléphone portable",v:1.1},{l:"Ordinateur portable actuel",v:1.4},{l:"Téléphone actuel",v:0.19}]},
{t:'techno',c:"Du plus grand nombre d'articles au plus petit",mes:"articles publiés dans cette langue",u:"millions d'articles",
 i:[{l:"Wikipédia en anglais",v:6.8},{l:"Wikipédia en allemand",v:2.9},{l:"Wikipédia en français",v:2.6},{l:"Wikipédia en italien",v:1.9}]},
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de création du service",u:"",rev:1,
 i:[{l:"Google",v:1998},{l:"Facebook",v:2004},{l:"WhatsApp",v:2009},{l:"TikTok",v:2016}]},
{t:'techno',c:"De la plus grande capacité à la plus petite",mes:"données que le support peut contenir",u:"gigaoctets",
 i:[{l:"Disque dur 4 To",v:4000},{l:"Blu-ray",v:25},{l:"DVD",v:4.7},{l:"CD",v:0.7}]},

/* ---------- cuisine ---------- */
{t:'cuisine',c:"Du plus consommé au moins consommé",mes:"production mondiale annuelle",u:"millions de tonnes",
 i:[{l:"Canne à sucre",v:1900},{l:"Maïs",v:1200},{l:"Blé",v:780},{l:"Pomme de terre",v:375}]},
{t:'cuisine',c:"Du plus fort au plus léger",mes:"degré d'alcool",u:"% vol.",
 i:[{l:"Absinthe",v:70},{l:"Whisky",v:40},{l:"Vin",v:12},{l:"Bière",v:5}]},
{t:'cuisine',c:"Du plus long affinage au plus court",mes:"durée d'affinage minimale",u:"mois",
 i:[{l:"Parmesan",v:24},{l:"Comté",v:12},{l:"Roquefort",v:3},{l:"Camembert",v:1}]},
{t:'cuisine',c:"Du plus de caféine au moins",mes:"caféine pour une tasse ou un verre",u:"mg",
 i:[{l:"Expresso double",v:130},{l:"Café filtre",v:95},{l:"Thé noir",v:47},{l:"Cola",v:34}]},
{t:'cuisine',c:"Du plus long temps de cuisson au plus court",mes:"durée de cuisson recommandée",u:"minutes",
 i:[{l:"Pot-au-feu",v:180},{l:"Riz complet",v:45},{l:"Pâtes",v:9},{l:"Œuf à la coque",v:3}]},
{t:'cuisine',c:"Du plus vieux au plus récent",mes:"année d'apparition du plat ou du produit",u:"",rev:1,
 i:[{l:"Pain",v:-8000},{l:"Fromage",v:-5500},{l:"Pizza margherita",v:1889},{l:"Nutella",v:1964}]},
{t:'cuisine',c:"Du plus de protéines au moins",mes:"protéines pour 100 grammes",u:"g / 100 g",
 i:[{l:"Parmesan",v:38},{l:"Bœuf",v:26},{l:"Lentilles cuites",v:9},{l:"Lait",v:3.4}]},
{t:'cuisine',c:"Du plus salé au moins salé",mes:"sel pour 100 grammes",u:"g / 100 g",
 i:[{l:"Sauce soja",v:16},{l:"Roquefort",v:3.5},{l:"Pain",v:1.2},{l:"Lait",v:0.05}]},

/* ---------- sport ---------- */
{t:'sport',c:"Du record le plus rapide au plus lent",mes:"vitesse moyenne du record du monde",u:"km/h",
 i:[{l:"100 m",v:37.6},{l:"400 m",v:32.5},{l:"1500 m",v:25.4},{l:"Marathon",v:20.9}]},
{t:'sport',c:"Du plus de titres au moins",mes:"Coupes du monde de football remportées",u:"titres",
 i:[{l:"Brésil",v:5},{l:"Allemagne",v:4},{l:"Argentine",v:3},{l:"France",v:2}]},
{t:'sport',c:"Du plus lourd au plus léger",mes:"masse du ballon ou de la balle",u:"g",
 i:[{l:"Ballon de basket",v:620},{l:"Ballon de football",v:430},{l:"Balle de tennis",v:58},{l:"Balle de golf",v:46}]},
{t:'sport',c:"Du plus ancien au plus récent",mes:"année d'entrée aux Jeux olympiques",u:"",rev:1,
 i:[{l:"Athlétisme",v:1896},{l:"Football",v:1900},{l:"Basket",v:1936},{l:"Escalade",v:2020}]},
{t:'sport',c:"De la plus longue épreuve à la plus courte",mes:"distance de l'épreuve",u:"km",
 i:[{l:"Tour de France",v:3400},{l:"Ironman",v:226},{l:"Marathon",v:42},{l:"10 000 m",v:10}]},
{t:'sport',c:"Du plus grand stade au plus petit",mes:"places assises",u:"places",
 i:[{l:"Rungrado, Pyongyang",v:114000},{l:"Camp Nou",v:99000},{l:"Stade de France",v:80000},{l:"Roland-Garros, court central",v:15000}]},
{t:'sport',c:"Du plus haut record au plus bas",mes:"hauteur ou longueur du record du monde",u:"m",
 i:[{l:"Saut en longueur",v:8.95},{l:"Saut à la perche",v:6.25},{l:"Triple saut, dernier bond",v:5.5},{l:"Saut en hauteur",v:2.45}]},

/* ---------- musique, art, pop, récits ---------- */
{t:'musique',c:"Du plus ancien au plus récent",mes:"année de naissance du compositeur",u:"",rev:1,
 i:[{l:"Bach",v:1685},{l:"Mozart",v:1756},{l:"Beethoven",v:1770},{l:"Debussy",v:1862}]},
{t:'musique',c:"De la symphonie la plus longue à la plus courte",mes:"durée d'exécution",u:"minutes",
 i:[{l:"Troisième de Mahler",v:100},{l:"Neuvième de Beethoven",v:70},{l:"Cinquième de Beethoven",v:33},{l:"Quarantième de Mozart",v:26}]},
{t:'musique',c:"Du plus de cordes au moins",mes:"cordes sur l'instrument",u:"cordes",
 i:[{l:"Piano",v:230},{l:"Harpe",v:47},{l:"Guitare",v:6},{l:"Violon",v:4}]},
{t:'musique',c:"Du plus grand orchestre au plus petit",mes:"musiciens dans la formation",u:"musiciens",
 i:[{l:"Orchestre symphonique",v:90},{l:"Orchestre de chambre",v:25},{l:"Quatuor",v:4},{l:"Duo",v:2}]},
{t:'art',c:"Du plus cher au moins cher",mes:"prix de la dernière vente aux enchères",u:"millions de dollars",
 i:[{l:"Salvator Mundi",v:450},{l:"Les Femmes d'Alger",v:179},{l:"Le Cri, version pastel",v:120},{l:"Nu couché de Modigliani",v:170}]},
{t:'art',c:"Du plus ancien au plus récent",mes:"année de réalisation",u:"",rev:1,
 i:[{l:"Grotte de Lascaux",v:-17000},{l:"Vénus de Milo",v:-100},{l:"La Joconde",v:1503},{l:"La Nuit étoilée",v:1889}]},
{t:'art',c:"Du musée le plus visité au moins visité",mes:"visiteurs par an",u:"millions de visiteurs",
 i:[{l:"Louvre",v:8.9},{l:"Musées du Vatican",v:6.8},{l:"British Museum",v:5.8},{l:"Musée d'Orsay",v:3.9}]},
{t:'pop',c:"Du plus rentable au moins rentable",mes:"recettes mondiales au cinéma",u:"milliards de dollars",
 i:[{l:"Avatar",v:2.92},{l:"Avengers: Endgame",v:2.79},{l:"Titanic",v:2.26},{l:"Star Wars, épisode VII",v:2.07}]},
{t:'pop',c:"Du plus ancien au plus récent",mes:"année de sortie du film",u:"",rev:1,
 i:[{l:"Le Magicien d'Oz",v:1939},{l:"Les Dents de la mer",v:1975},{l:"Jurassic Park",v:1993},{l:"Avatar",v:2009}]},
{t:'pop',c:"De la série la plus longue à la plus courte",mes:"épisodes diffusés",u:"épisodes",
 i:[{l:"Les Simpson",v:780},{l:"Friends",v:236},{l:"Game of Thrones",v:73},{l:"Chernobyl",v:5}]},
{t:'litt',c:"Du plus long au plus court",mes:"nombre de mots du roman",u:"milliers de mots",
 i:[{l:"À la recherche du temps perdu",v:1267},{l:"Guerre et Paix",v:587},{l:"Les Misérables",v:530},{l:"Le Petit Prince",v:16}]},
{t:'litt',c:"Du plus ancien au plus récent",mes:"année de parution",u:"",rev:1,
 i:[{l:"Le Comte de Monte-Cristo",v:1844},{l:"Vingt mille lieues sous les mers",v:1870},{l:"Le Petit Prince",v:1943},{l:"Harry Potter à l'école des sorciers",v:1997}]},
{t:'langue',c:"Du plus de mots au moins",mes:"entrées dans le dictionnaire de référence",u:"mots",
 i:[{l:"Anglais",v:171000},{l:"Allemand",v:135000},{l:"Français",v:60000},{l:"Espagnol",v:93000}]},
{t:'langue',c:"Du plus ancien au plus récent",mes:"année d'apparition de l'écriture",u:"",rev:1,
 i:[{l:"Cunéiforme",v:-3200},{l:"Hiéroglyphes",v:-3100},{l:"Alphabet grec",v:-800},{l:"Alphabet latin",v:-700}]},
];
