/* =========================================================
   NO WAY! — banque de « Classe-les »
   Le joueur remet quatre éléments dans le bon ordre.
   Structure : {t, c, mes, u, i:[{l, v}], rev}
     t   = thème
     c   = la consigne, qui doit se suffire à elle-même
     mes = ce qu'on compare exactement, affiché SOUS la consigne,
           avant de répondre. « Le plus d'eau » ne veut rien dire
           tant qu'on n'a pas dit « en part du poids » ou « en litres ».
     u   = l'unité, affichée avec les valeurs à la révélation
     i   = les quatre éléments, dans un ordre quelconque
     rev = 1 quand l'ordre attendu va du PLUS PETIT au plus grand
           (par défaut : du plus grand au plus petit)
   Les écarts sont choisis pour qu'au moins une paire soit
   contre-intuitive — sans quoi il n'y a rien à jouer.
   Chargé avant index.html ; expose la globale `CLASSEMENTS`.
   ========================================================= */
const CLASSEMENTS=[

/* ---------- animaux ---------- */
{t:'animaux',c:"Du plus rapide au plus lent",mes:"pointe de vitesse en course",u:"km/h",
 i:[{l:"Guépard",v:110},{l:"Cheval de course",v:70},{l:"Crocodile marin",v:17},{l:"Ours brun",v:48}]},
{t:'animaux',c:"Du plus lourd au plus léger",mes:"masse d'un adulte",u:"kg",
 i:[{l:"Baleine bleue",v:150000},{l:"Éléphant d'Afrique",v:6000},{l:"Girafe",v:1200},{l:"Ours polaire",v:500}]},
{t:'animaux',c:"De la plus longue vie à la plus courte",mes:"espérance de vie",u:"ans",
 i:[{l:"Tortue des Galápagos",v:150},{l:"Éléphant",v:70},{l:"Chat",v:15},{l:"Souris",v:2}]},
{t:'animaux',c:"Du plus de cœurs au moins de cœurs",mes:"nombre de cœurs dans le corps",u:"cœurs",
 i:[{l:"Ver de terre",v:5},{l:"Pieuvre",v:3},{l:"Humain",v:1},{l:"Éponge de mer",v:0}]},
{t:'animaux',c:"De la gestation la plus longue à la plus courte",mes:"durée de la grossesse",u:"jours",
 i:[{l:"Éléphant",v:645},{l:"Baleine bleue",v:340},{l:"Chien",v:63},{l:"Hamster",v:16}]},
{t:'animaux',c:"Du meilleur sauteur au moins bon",mes:"hauteur du saut, en multiples de sa propre taille",u:"× sa taille",
 i:[{l:"Puce",v:100},{l:"Sauterelle",v:20},{l:"Kangourou",v:2},{l:"Humain",v:1}]},
{t:'animaux',c:"Du cerveau le plus lourd au plus léger",mes:"masse du cerveau seul",u:"g",
 i:[{l:"Cachalot",v:7800},{l:"Éléphant",v:5000},{l:"Humain",v:1400},{l:"Chat",v:30}]},
{t:'animaux',c:"Du plus grand au plus petit",mes:"taille d'un adulte, du sol au sommet",u:"m",
 i:[{l:"Girafe",v:5.5},{l:"Éléphant d'Afrique",v:3.3},{l:"Ours polaire debout",v:2.6},{l:"Autruche",v:2.4}]},

/* ---------- géographie ---------- */
{t:'geo',c:"Du pays le plus peuplé au moins peuplé",mes:"nombre d'habitants",u:"millions d'habitants",
 i:[{l:"Inde",v:1430},{l:"États-Unis",v:340},{l:"Brésil",v:216},{l:"France",v:68}]},
{t:'geo',c:"Du pays le plus vaste au moins vaste",mes:"superficie totale",u:"millions de km²",
 i:[{l:"Russie",v:17.1},{l:"Canada",v:10},{l:"Brésil",v:8.5},{l:"Inde",v:3.3}]},
{t:'geo',c:"Du sommet le plus haut au moins haut",mes:"altitude au-dessus du niveau de la mer",u:"m",
 i:[{l:"Everest",v:8849},{l:"Kilimandjaro",v:5895},{l:"Mont Blanc",v:4806},{l:"Fuji",v:3776}]},
{t:'geo',c:"Du fleuve le plus long au plus court",mes:"longueur du cours d'eau",u:"km",
 i:[{l:"Nil",v:6650},{l:"Amazone",v:6400},{l:"Mississippi",v:3766},{l:"Danube",v:2850}]},
{t:'geo',c:"De la plus grande profondeur d'eau à la plus faible",mes:"point le plus profond sous la surface",u:"m",
 i:[{l:"Fosse des Mariannes",v:10935},{l:"Mer Méditerranée",v:5267},{l:"Lac Baïkal",v:1642},{l:"Mer Baltique",v:459}]},
{t:'geo',c:"De la ville la plus au nord à la plus au sud",mes:"latitude",u:"° nord",
 i:[{l:"Oslo",v:59.9},{l:"Paris",v:48.9},{l:"New York",v:40.7},{l:"Le Caire",v:30}]},
{t:'geo',c:"Du désert le plus vaste au plus petit",mes:"superficie",u:"millions de km²",
 i:[{l:"Antarctique",v:14},{l:"Sahara",v:9.2},{l:"Désert d'Arabie",v:2.3},{l:"Gobi",v:1.3}]},
{t:'geo',c:"Du pays au plus de fuseaux horaires au moins",mes:"fuseaux horaires, outre-mer compris",u:"fuseaux",
 i:[{l:"France",v:12},{l:"Russie",v:11},{l:"États-Unis",v:6},{l:"Brésil",v:4}]},
{t:'geo',c:"De l'île la plus vaste à la moins vaste",mes:"superficie de l'île",u:"km²",
 i:[{l:"Groenland",v:2166000},{l:"Madagascar",v:587000},{l:"Grande-Bretagne",v:209000},{l:"Islande",v:103000}]},

/* ---------- espace ---------- */
{t:'espace',c:"De la planète la plus grosse à la plus petite",mes:"diamètre à l'équateur",u:"km",
 i:[{l:"Jupiter",v:139820},{l:"Saturne",v:116460},{l:"Terre",v:12742},{l:"Mars",v:6779}]},
{t:'espace',c:"De la plus chaude à la plus froide",mes:"température moyenne au sol",u:"°C",
 i:[{l:"Vénus",v:465},{l:"Mercure, côté jour",v:430},{l:"Terre",v:15},{l:"Mars",v:-63}]},
{t:'espace',c:"Du plus loin du Soleil au plus proche",mes:"distance moyenne au Soleil",u:"millions de km",
 i:[{l:"Neptune",v:4500},{l:"Jupiter",v:778},{l:"Mars",v:228},{l:"Vénus",v:108}]},
{t:'espace',c:"Du tour sur soi-même le plus lent au plus rapide",mes:"durée d'une rotation de la planète sur elle-même",u:"heures terrestres",
 i:[{l:"Vénus",v:5832},{l:"Mercure",v:1408},{l:"Mars",v:24.6},{l:"Jupiter",v:9.9}]},
{t:'espace',c:"Du plus ancien au plus récent",mes:"année de l'événement",u:"",rev:1,
 i:[{l:"Spoutnik",v:1957},{l:"Premier homme dans l'espace",v:1961},{l:"Apollo 11",v:1969},{l:"Station spatiale internationale",v:1998}]},
{t:'espace',c:"Du plus massif au moins massif",mes:"masse, comparée à celle de la Terre",u:"× la Terre",
 i:[{l:"Soleil",v:333000},{l:"Jupiter",v:318},{l:"Neptune",v:17},{l:"Lune",v:0.012}]},

/* ---------- sciences ---------- */
{t:'sci',c:"Du plus chaud au plus froid",mes:"température",u:"°C",
 i:[{l:"Éclair",v:30000},{l:"Surface du Soleil",v:5500},{l:"Lave",v:1200},{l:"Four de cuisine",v:250}]},
{t:'sci',c:"Du plus rapide au plus lent",mes:"vitesse de déplacement",u:"km/h",
 i:[{l:"Lumière",v:1080000000},{l:"Son dans l'air",v:1235},{l:"Avion de ligne",v:900},{l:"Guépard",v:110}]},
{t:'sci',c:"Du plus dense au moins dense",mes:"masse d'un centimètre cube",u:"g/cm³",
 i:[{l:"Or",v:19.3},{l:"Fer",v:7.9},{l:"Eau",v:1},{l:"Liège",v:0.24}]},
{t:'sci',c:"De la cellule qui vit le plus longtemps à celle qui vit le moins",mes:"durée de vie d'une cellule avant renouvellement",u:"jours",
 i:[{l:"Globule rouge",v:120},{l:"Cellule de peau",v:35},{l:"Cellule d'estomac",v:4},{l:"Globule blanc",v:1}]},
{t:'sci',c:"Du plus petit au plus grand",mes:"taille de l'objet",u:"nanomètres",rev:1,
 i:[{l:"Atome",v:0.1},{l:"Molécule d'ADN, en largeur",v:2},{l:"Virus",v:100},{l:"Bactérie",v:2000}]},
{t:'sci',c:"Du plus riche en eau au moins riche",mes:"part d'eau dans le poids total, en pourcentage",u:"% du poids",
 i:[{l:"Méduse",v:97},{l:"Concombre",v:96},{l:"Nouveau-né",v:78},{l:"Adulte",v:60}]},
{t:'sci',c:"Du plus bruyant au moins bruyant",mes:"niveau sonore mesuré à courte distance",u:"décibels",
 i:[{l:"Décollage d'avion",v:140},{l:"Marteau-piqueur",v:110},{l:"Aspirateur",v:70},{l:"Conversation",v:60}]},

/* ---------- histoire ---------- */
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de construction",u:"",rev:1,
 i:[{l:"Pyramide de Khéops",v:-2560},{l:"Grande Muraille, premiers tronçons",v:-220},{l:"Colisée",v:80},{l:"Tour Eiffel",v:1889}]},
{t:'histo',c:"Du règne le plus long au plus court",mes:"durée passée sur le trône",u:"ans de règne",
 i:[{l:"Louis XIV",v:72},{l:"Élisabeth II",v:70},{l:"Victoria",v:63},{l:"Napoléon Iᵉʳ",v:10}]},
{t:'histo',c:"De la plus ancienne invention à la plus récente",mes:"année de l'invention",u:"",rev:1,
 i:[{l:"Imprimerie",v:1450},{l:"Machine à vapeur",v:1712},{l:"Téléphone",v:1876},{l:"Internet",v:1969}]},
{t:'histo',c:"De la guerre la plus longue à la plus courte",mes:"durée du conflit",u:"années",
 i:[{l:"Guerre de Cent Ans",v:116},{l:"Guerre de Trente Ans",v:30},{l:"Seconde Guerre mondiale",v:6},{l:"Guerre des Six Jours",v:0.02}]},
{t:'histo',c:"De la civilisation la plus ancienne à la plus récente",mes:"année où elle apparaît",u:"",rev:1,
 i:[{l:"Sumer",v:-4000},{l:"Égypte pharaonique",v:-3100},{l:"Rome",v:-753},{l:"Empire aztèque",v:1325}]},

/* ---------- techno ---------- */
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de la première mise en service",u:"",rev:1,
 i:[{l:"Premier courriel",v:1971},{l:"Premier site web",v:1991},{l:"Premier iPhone",v:2007},{l:"ChatGPT",v:2022}]},
{t:'techno',c:"De la plus grande capacité de mémoire à la plus petite",mes:"quantité de données stockables",u:"octets",
 i:[{l:"Téléphone courant",v:256000000000},{l:"Disquette",v:1440000},{l:"Ordinateur d'Apollo 11",v:4096},{l:"Carte perforée",v:80}]},
{t:'techno',c:"Du réseau social au plus d'utilisateurs au moins",mes:"utilisateurs actifs par mois",u:"millions d'utilisateurs",
 i:[{l:"Facebook",v:3000},{l:"Instagram",v:2000},{l:"TikTok",v:1500},{l:"X",v:550}]},

/* ---------- cuisine ---------- */
{t:'cuisine',c:"Du plus calorique au moins calorique",mes:"calories pour 100 grammes",u:"kcal / 100 g",
 i:[{l:"Huile d'olive",v:900},{l:"Chocolat noir",v:550},{l:"Pain",v:265},{l:"Pomme",v:52}]},
{t:'cuisine',c:"Du plus piquant au plus doux",mes:"force du piment sur l'échelle de Scoville",u:"unités Scoville",
 i:[{l:"Carolina Reaper",v:2200000},{l:"Piment habanero",v:350000},{l:"Piment de Cayenne",v:40000},{l:"Piment d'Espelette",v:4000}]},
{t:'cuisine',c:"Du plus cher au moins cher",mes:"prix au kilo",u:"€ / kg",
 i:[{l:"Safran",v:15000},{l:"Truffe blanche",v:4000},{l:"Caviar",v:2500},{l:"Vanille",v:500}]},
{t:'cuisine',c:"Du plus sucré au moins sucré",mes:"sucre pour 100 grammes",u:"g / 100 g",
 i:[{l:"Miel",v:82},{l:"Confiture",v:60},{l:"Soda",v:11},{l:"Lait",v:5}]},

/* ---------- sport ---------- */
{t:'sport',c:"De la balle la plus rapide à la plus lente",mes:"vitesse record jamais mesurée pour cette balle",u:"km/h",
 i:[{l:"Volant de badminton",v:493},{l:"Balle de golf",v:340},{l:"Balle de tennis",v:263},{l:"Ballon de football",v:210}]},
{t:'sport',c:"Du terrain le plus long au plus court",mes:"longueur du terrain",u:"m",
 i:[{l:"Football",v:105},{l:"Rugby",v:100},{l:"Basket",v:28},{l:"Tennis",v:24}]},
{t:'sport',c:"Du plus de joueurs au moins de joueurs",mes:"joueurs d'une équipe sur le terrain",u:"joueurs",
 i:[{l:"Rugby à XV",v:15},{l:"Football",v:11},{l:"Handball",v:7},{l:"Basket",v:5}]},

/* ---------- pop, art, musique ---------- */
{t:'pop',c:"Du film le plus long au plus court",mes:"durée de projection",u:"minutes",
 i:[{l:"Autant en emporte le vent",v:238},{l:"Titanic",v:194},{l:"Le Parrain",v:175},{l:"Le Roi Lion",v:88}]},
{t:'art',c:"Du tableau le plus large au moins large",mes:"largeur de la toile",u:"cm",
 i:[{l:"Les Noces de Cana",v:990},{l:"Le Radeau de la Méduse",v:716},{l:"La Nuit étoilée",v:92},{l:"La Joconde",v:53}]},
{t:'musique',c:"De l'instrument le plus grave au plus aigu",mes:"fréquence de la note la plus basse qu'il peut jouer",u:"Hz",rev:1,
 i:[{l:"Piccolo",v:587},{l:"Violon",v:196},{l:"Violoncelle",v:65},{l:"Contrebasse",v:41}]},
{t:'musique',c:"De l'album le plus vendu au moins vendu",mes:"exemplaires vendus dans le monde",u:"millions d'exemplaires",
 i:[{l:"Thriller",v:70},{l:"Back in Black",v:50},{l:"The Dark Side of the Moon",v:45},{l:"Rumours",v:40}]},

/* ---------- langue et récits ---------- */
{t:'langue',c:"De la langue au plus de locuteurs natifs au moins",mes:"personnes dont c'est la langue maternelle",u:"millions de locuteurs",
 i:[{l:"Mandarin",v:940},{l:"Espagnol",v:485},{l:"Anglais",v:380},{l:"Français",v:80}]},
{t:'langue',c:"De l'alphabet au plus de lettres au moins",mes:"lettres dans l'alphabet",u:"lettres",
 i:[{l:"Khmer",v:74},{l:"Russe",v:33},{l:"Français",v:26},{l:"Hawaïen",v:13}]},
{t:'litt',c:"Du livre le plus vendu au moins vendu",mes:"exemplaires vendus depuis la parution",u:"millions d'exemplaires",
 i:[{l:"Don Quichotte",v:500},{l:"Le Seigneur des anneaux",v:150},{l:"Le Petit Prince",v:140},{l:"Harry Potter à l'école des sorciers",v:120}]},
{t:'litt',c:"Du plus ancien au plus récent",mes:"année de parution",u:"",rev:1,
 i:[{l:"L'Odyssée",v:-750},{l:"Don Quichotte",v:1605},{l:"Les Misérables",v:1862},{l:"1984, le roman",v:1949}]},
/* ---------- animaux ---------- */
{t:'animaux',c:"Du plus rapide au plus lent à la nage",mes:"vitesse de pointe dans l'eau",u:"km/h",
 i:[{l:"Espadon",v:100},{l:"Dauphin",v:60},{l:"Requin blanc",v:40},{l:"Manchot papou",v:36}]},
{t:'animaux',c:"Du plus rapide au plus lent en vol",mes:"vitesse de pointe en vol horizontal",u:"km/h",
 i:[{l:"Martinet à gorge blanche",v:169},{l:"Canard colvert",v:105},{l:"Frégate",v:95},{l:"Colibri",v:54}]},
{t:'animaux',c:"Du plus grand au plus petit",mes:"envergure des ailes déployées",u:"m",
 i:[{l:"Albatros hurleur",v:3.5},{l:"Condor des Andes",v:3.2},{l:"Pélican",v:2.8},{l:"Aigle royal",v:2.2}]},
{t:'animaux',c:"Du plus lourd au plus léger à la naissance",mes:"poids du petit à la naissance",u:"kg",
 i:[{l:"Baleine bleue",v:2700},{l:"Éléphant",v:100},{l:"Humain",v:3.3},{l:"Kangourou",v:0.001}]},
{t:'animaux',c:"Du plus grand nombre d'œufs au plus petit",mes:"œufs pondus en une fois",u:"œufs",
 i:[{l:"Poisson-lune",v:300000000},{l:"Grenouille rousse",v:2000},{l:"Tortue marine",v:110},{l:"Manchot empereur",v:1}]},
{t:'animaux',c:"Du plus long sommeil au plus court",mes:"heures de sommeil par jour",u:"h / jour",
 i:[{l:"Koala",v:20},{l:"Chat",v:15},{l:"Humain",v:8},{l:"Girafe",v:2}]},
{t:'animaux',c:"De la plus longue migration à la plus courte",mes:"distance parcourue en un aller-retour annuel",u:"km",
 i:[{l:"Sterne arctique",v:70000},{l:"Baleine à bosse",v:16000},{l:"Papillon monarque",v:4800},{l:"Cigogne blanche",v:4000}]},
{t:'animaux',c:"De la plus grande longévité à la plus courte",mes:"âge du plus vieux spécimen connu",u:"ans",
 i:[{l:"Éponge des abysses",v:11000},{l:"Requin du Groenland",v:400},{l:"Tortue géante",v:190},{l:"Perroquet gris",v:80}]},
{t:'animaux',c:"Du plus venimeux au moins venimeux",mes:"dose mortelle pour un humain, du plus petit volume au plus grand",u:"mg de venin nécessaire",rev:1,
 i:[{l:"Méduse-boîte",v:0.04},{l:"Cobra royal",v:15},{l:"Vipère aspic",v:60},{l:"Abeille",v:500}]},
{t:'animaux',c:"Du plus gros cœur au plus petit",mes:"masse du cœur",u:"kg",
 i:[{l:"Baleine bleue",v:180},{l:"Éléphant",v:20},{l:"Cheval",v:4},{l:"Humain",v:0.3}]},
{t:'animaux',c:"Du battement de cœur le plus rapide au plus lent",mes:"battements par minute au repos",u:"battements / min",
 i:[{l:"Colibri",v:1200},{l:"Souris",v:600},{l:"Humain",v:70},{l:"Baleine bleue",v:8}]},
{t:'animaux',c:"De la plus grande morsure à la plus faible",mes:"force de la mâchoire",u:"kg de pression",
 i:[{l:"Crocodile marin",v:1700},{l:"Hippopotame",v:1300},{l:"Lion",v:290},{l:"Humain",v:75}]},
{t:'animaux',c:"Du plus gros œuf au plus petit",mes:"masse de l'œuf",u:"g",
 i:[{l:"Autruche",v:1400},{l:"Émeu",v:600},{l:"Poule",v:60},{l:"Colibri",v:0.5}]},
{t:'animaux',c:"Du plus profond plongeur au moins profond",mes:"profondeur maximale atteinte",u:"m",
 i:[{l:"Cachalot",v:2250},{l:"Éléphant de mer",v:1500},{l:"Manchot empereur",v:565},{l:"Tortue verte",v:110}]},
{t:'animaux',c:"Du plus d'espèces au moins d'espèces",mes:"espèces décrites dans le groupe",u:"espèces",
 i:[{l:"Coléoptères",v:400000},{l:"Poissons",v:34000},{l:"Oiseaux",v:11000},{l:"Mammifères",v:6400}]},
{t:'animaux',c:"Du plus grand territoire au plus petit",mes:"surface parcourue par un individu",u:"km²",
 i:[{l:"Ours polaire",v:250000},{l:"Loup gris",v:1000},{l:"Lion",v:200},{l:"Renard roux",v:5}]},
{t:'animaux',c:"Du meilleur odorat au moins bon",mes:"récepteurs olfactifs dans le nez",u:"millions de récepteurs",
 i:[{l:"Chien de sang",v:300},{l:"Chien courant",v:220},{l:"Chat",v:80},{l:"Humain",v:6}]},
{t:'animaux',c:"Du plus grand groupe au plus petit",mes:"individus dans une colonie ou un troupeau typique",u:"individus",
 i:[{l:"Fourmilière",v:500000},{l:"Colonie de chauves-souris",v:20000},{l:"Troupeau de gnous",v:1500},{l:"Meute de loups",v:8}]},
{t:'animaux',c:"De la plus longue langue à la plus courte",mes:"longueur de la langue déployée",u:"cm",
 i:[{l:"Baleine bleue",v:550},{l:"Girafe",v:50},{l:"Fourmilier",v:45},{l:"Caméléon",v:30}]},
{t:'animaux',c:"Du plus de chromosomes au moins",mes:"nombre de chromosomes par cellule",u:"chromosomes",
 i:[{l:"Fougère Ophioglossum",v:1260},{l:"Chien",v:78},{l:"Humain",v:46},{l:"Moustique",v:6}]},

/* ---------- géographie ---------- */
{t:'geo',c:"De la ville la plus peuplée à la moins peuplée",mes:"habitants de l'agglomération",u:"millions d'habitants",
 i:[{l:"Tokyo",v:37},{l:"Le Caire",v:22},{l:"Paris",v:11},{l:"Berlin",v:3.6}]},
{t:'geo',c:"Du pays le plus densément peuplé au moins",mes:"habitants au kilomètre carré",u:"hab. / km²",
 i:[{l:"Bangladesh",v:1265},{l:"Pays-Bas",v:520},{l:"France",v:119},{l:"Australie",v:3}]},
{t:'geo',c:"Du plus long littoral au plus court",mes:"longueur des côtes",u:"km",
 i:[{l:"Canada",v:202080},{l:"Indonésie",v:54716},{l:"Australie",v:25760},{l:"France",v:4853}]},
{t:'geo',c:"Du lac le plus vaste au plus petit",mes:"superficie du plan d'eau",u:"km²",
 i:[{l:"Mer Caspienne",v:371000},{l:"Lac Supérieur",v:82100},{l:"Lac Victoria",v:68870},{l:"Lac Baïkal",v:31722}]},
{t:'geo',c:"De la chute d'eau la plus haute à la plus basse",mes:"hauteur de chute",u:"m",
 i:[{l:"Salto Ángel",v:979},{l:"Chutes Tugela",v:948},{l:"Chutes Victoria",v:108},{l:"Chutes du Niagara",v:51}]},
{t:'geo',c:"Du pays au plus de voisins au moins",mes:"pays frontaliers",u:"voisins",
 i:[{l:"Chine",v:14},{l:"Brésil",v:10},{l:"Allemagne",v:9},{l:"France",v:8}]},
{t:'geo',c:"De la plus forte chaleur au plus grand froid",mes:"température record enregistrée",u:"°C",
 i:[{l:"Vallée de la Mort",v:56.7},{l:"Kebili, Tunisie",v:55},{l:"Séville",v:47},{l:"Vostok, Antarctique",v:-89}]},
{t:'geo',c:"Du plus vieux pays au plus jeune",mes:"année d'indépendance ou de fondation",u:"",rev:1,
 i:[{l:"Saint-Marin",v:301},{l:"France",v:843},{l:"États-Unis",v:1776},{l:"Soudan du Sud",v:2011}]},
{t:'geo',c:"De l'aéroport le plus fréquenté au moins",mes:"passagers par an",u:"millions de passagers",
 i:[{l:"Atlanta",v:104},{l:"Dubaï",v:87},{l:"Paris-Charles-de-Gaulle",v:67},{l:"Genève",v:16}]},
{t:'geo',c:"Du plus vaste océan au plus petit",mes:"superficie",u:"millions de km²",
 i:[{l:"Pacifique",v:165},{l:"Atlantique",v:106},{l:"Indien",v:70},{l:"Arctique",v:14}]},
{t:'geo',c:"Du plus grand nombre de langues au plus petit",mes:"langues vivantes parlées dans le pays",u:"langues",
 i:[{l:"Papouasie-Nouvelle-Guinée",v:840},{l:"Indonésie",v:710},{l:"Inde",v:450},{l:"France",v:25}]},
{t:'geo',c:"De la plus grande forêt à la plus petite",mes:"superficie boisée",u:"millions de km²",
 i:[{l:"Taïga russe",v:12},{l:"Amazonie",v:5.5},{l:"Bassin du Congo",v:3.4},{l:"Forêt de Bornéo",v:0.4}]},
{t:'geo',c:"Du volcan le plus haut au plus bas",mes:"altitude du sommet",u:"m",
 i:[{l:"Ojos del Salado",v:6893},{l:"Kilimandjaro",v:5895},{l:"Etna",v:3357},{l:"Stromboli",v:924}]},
{t:'geo',c:"Du pont le plus long au plus court",mes:"longueur totale de l'ouvrage",u:"km",
 i:[{l:"Grand pont Danyang-Kunshan",v:164},{l:"Pont de la baie de Hangzhou",v:36},{l:"Pont de l'Øresund",v:16},{l:"Golden Gate",v:2.7}]},
{t:'geo',c:"Du métro le plus long au plus court",mes:"longueur totale du réseau",u:"km",
 i:[{l:"Shanghai",v:831},{l:"Pékin",v:807},{l:"Londres",v:402},{l:"Paris",v:226}]},
{t:'geo',c:"Du pays le plus arrosé au plus sec",mes:"précipitations moyennes par an",u:"mm / an",
 i:[{l:"Colombie",v:3240},{l:"Indonésie",v:2700},{l:"France",v:867},{l:"Égypte",v:51}]},
{t:'geo',c:"Du plus grand désert de sel au plus petit",mes:"superficie",u:"km²",
 i:[{l:"Salar d'Uyuni",v:10582},{l:"Bonneville",v:260},{l:"Salar d'Atacama",v:3000},{l:"Chott el-Jérid",v:5000}]},
{t:'geo',c:"De la plus haute capitale à la plus basse",mes:"altitude de la ville",u:"m",
 i:[{l:"La Paz",v:3640},{l:"Quito",v:2850},{l:"Mexico",v:2240},{l:"Paris",v:35}]},
{t:'geo',c:"Du fuseau le plus en avance au plus en retard",mes:"décalage par rapport au temps universel",u:"h UTC",
 i:[{l:"Kiribati",v:14},{l:"Tokyo",v:9},{l:"Paris",v:1},{l:"Hawaï",v:-10}]},
{t:'geo',c:"Du plus grand nombre d'îles au plus petit",mes:"îles recensées dans le pays",u:"îles",
 i:[{l:"Suède",v:267570},{l:"Norvège",v:239057},{l:"Finlande",v:178947},{l:"Indonésie",v:17508}]},

/* ---------- espace ---------- */
{t:'espace',c:"De la plus grosse lune à la plus petite",mes:"diamètre du satellite",u:"km",
 i:[{l:"Ganymède",v:5268},{l:"Titan",v:5150},{l:"Lune",v:3475},{l:"Europe",v:3122}]},
{t:'espace',c:"De l'année la plus longue à la plus courte",mes:"durée d'un tour complet autour du Soleil",u:"jours terrestres",
 i:[{l:"Neptune",v:60190},{l:"Saturne",v:10759},{l:"Mars",v:687},{l:"Mercure",v:88}]},
{t:'espace',c:"Du plus de lunes au moins",mes:"satellites naturels connus",u:"lunes",
 i:[{l:"Saturne",v:146},{l:"Jupiter",v:95},{l:"Uranus",v:28},{l:"Mars",v:2}]},
{t:'espace',c:"De la plus forte gravité à la plus faible",mes:"gravité en surface",u:"× celle de la Terre",
 i:[{l:"Jupiter",v:2.53},{l:"Terre",v:1},{l:"Mars",v:0.38},{l:"Lune",v:0.17}]},
{t:'espace',c:"De l'étoile la plus brillante à la moins brillante",mes:"éclat apparent vu de la Terre, du plus vif au plus faible",u:"magnitude",rev:1,
 i:[{l:"Sirius",v:-1.46},{l:"Canopus",v:-0.74},{l:"Véga",v:0.03},{l:"Étoile Polaire",v:1.98}]},
{t:'espace',c:"De la plus grosse étoile à la plus petite",mes:"diamètre",u:"× le Soleil",
 i:[{l:"UY Scuti",v:1700},{l:"Bételgeuse",v:900},{l:"Aldébaran",v:44},{l:"Soleil",v:1}]},
{t:'espace',c:"Du plus loin au plus proche de nous",mes:"distance à la Terre",u:"années-lumière",
 i:[{l:"Galaxie d'Andromède",v:2500000},{l:"Nébuleuse d'Orion",v:1344},{l:"Étoile Polaire",v:433},{l:"Proxima du Centaure",v:4.2}]},
{t:'espace',c:"De la mission la plus longue à la plus courte",mes:"durée du séjour dans l'espace",u:"jours",
 i:[{l:"Valeri Poliakov",v:437},{l:"Scott Kelly",v:340},{l:"Thomas Pesquet, second vol",v:199},{l:"Apollo 11",v:8}]},
{t:'espace',c:"Du plus grand télescope au plus petit",mes:"diamètre du miroir principal",u:"m",
 i:[{l:"Extremely Large Telescope",v:39},{l:"Gran Telescopio Canarias",v:10.4},{l:"James-Webb",v:6.5},{l:"Hubble",v:2.4}]},
{t:'espace',c:"De la plus longue journée à la plus courte",mes:"durée d'une rotation sur soi-même",u:"heures terrestres",
 i:[{l:"Pluton",v:153},{l:"Terre",v:24},{l:"Uranus",v:17},{l:"Saturne",v:10.7}]},
{t:'espace',c:"Du plus ancien au plus récent",mes:"année de lancement",u:"",rev:1,
 i:[{l:"Voyager 1",v:1977},{l:"Hubble",v:1990},{l:"Curiosity",v:2011},{l:"James-Webb",v:2021}]},
{t:'espace',c:"Du plus chaud au plus froid",mes:"température",u:"°C",
 i:[{l:"Cœur du Soleil",v:15000000},{l:"Surface du Soleil",v:5500},{l:"Vénus",v:465},{l:"Pluton",v:-229}]},

/* ---------- sciences ---------- */
{t:'sci',c:"Du plus abondant au plus rare dans l'univers",mes:"part de la matière ordinaire",u:"% des atomes",
 i:[{l:"Hydrogène",v:92},{l:"Hélium",v:7.8},{l:"Oxygène",v:0.06},{l:"Carbone",v:0.03}]},
{t:'sci',c:"Du point de fusion le plus haut au plus bas",mes:"température à laquelle le métal fond",u:"°C",
 i:[{l:"Tungstène",v:3422},{l:"Fer",v:1538},{l:"Aluminium",v:660},{l:"Mercure",v:-39}]},
{t:'sci',c:"Du plus dur au plus tendre",mes:"dureté sur l'échelle de Mohs",u:"sur 10",
 i:[{l:"Diamant",v:10},{l:"Quartz",v:7},{l:"Cuivre",v:3},{l:"Talc",v:1}]},
{t:'sci',c:"De la plus longue demi-vie à la plus courte",mes:"temps au bout duquel la moitié s'est désintégrée",u:"ans",
 i:[{l:"Uranium 238",v:4470000000},{l:"Carbone 14",v:5730},{l:"Césium 137",v:30},{l:"Iode 131",v:0.022}]},
{t:'sci',c:"Du plus long au plus court",mes:"longueur d'onde du rayonnement",u:"nanomètres",
 i:[{l:"Onde radio",v:1000000000},{l:"Infrarouge",v:10000},{l:"Lumière rouge",v:700},{l:"Rayon X",v:0.1}]},
{t:'sci',c:"Du plus lourd au plus léger",mes:"masse de la particule",u:"× l'électron",
 i:[{l:"Neutron",v:1839},{l:"Proton",v:1836},{l:"Muon",v:207},{l:"Électron",v:1}]},
{t:'sci',c:"Du son le plus rapide au plus lent",mes:"vitesse du son dans le milieu",u:"m/s",
 i:[{l:"Acier",v:5960},{l:"Eau",v:1480},{l:"Air",v:343},{l:"Caoutchouc",v:60}]},
{t:'sci',c:"Du plus acide au plus basique",mes:"pH, du plus bas au plus haut",u:"pH",rev:1,
 i:[{l:"Acide de batterie",v:0.5},{l:"Jus de citron",v:2},{l:"Eau pure",v:7},{l:"Ammoniaque",v:11.5}]},
{t:'sci',c:"Du plus grand organe au plus petit",mes:"masse de l'organe chez l'adulte",u:"g",
 i:[{l:"Peau",v:10000},{l:"Foie",v:1500},{l:"Cerveau",v:1400},{l:"Cœur",v:300}]},
{t:'sci',c:"Du plus long os au plus court",mes:"longueur de l'os",u:"cm",
 i:[{l:"Fémur",v:48},{l:"Tibia",v:43},{l:"Humérus",v:36},{l:"Étrier de l'oreille",v:0.3}]},
{t:'sci',c:"De la plus grande consommation d'énergie à la plus petite",mes:"part de l'énergie du corps au repos",u:"% de l'énergie",
 i:[{l:"Cerveau",v:20},{l:"Foie",v:19},{l:"Muscles",v:18},{l:"Reins",v:8}]},
{t:'sci',c:"Du plus de cellules au moins",mes:"cellules dans le corps humain",u:"milliards de cellules",
 i:[{l:"Globules rouges",v:25000},{l:"Cellules de peau",v:1600},{l:"Neurones",v:86},{l:"Cellules du foie",v:240}]},
{t:'sci',c:"Du plus rapide au plus lent",mes:"vitesse de transmission dans le nerf",u:"m/s",
 i:[{l:"Nerf moteur",v:120},{l:"Nerf du toucher",v:76},{l:"Nerf de la douleur vive",v:20},{l:"Nerf de la douleur sourde",v:1}]},
{t:'sci',c:"Du plus grand volume d'eau au plus petit",mes:"part de l'eau de la planète",u:"% de l'eau terrestre",
 i:[{l:"Océans",v:96.5},{l:"Glaciers",v:1.74},{l:"Nappes souterraines",v:1.69},{l:"Lacs et rivières",v:0.013}]},
{t:'sci',c:"De la plus forte pression à la plus faible",mes:"pression subie",u:"atmosphères",
 i:[{l:"Centre de la Terre",v:3600000},{l:"Fosse des Mariannes",v:1100},{l:"Bouteille de champagne",v:6},{l:"Niveau de la mer",v:1}]},

/* ---------- histoire ---------- */
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'événement",u:"",rev:1,
 i:[{l:"Chute de Rome",v:476},{l:"Découverte de l'Amérique",v:1492},{l:"Révolution française",v:1789},{l:"Chute du mur de Berlin",v:1989}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la mort du personnage",u:"",rev:1,
 i:[{l:"Jules César",v:-44},{l:"Charlemagne",v:814},{l:"Léonard de Vinci",v:1519},{l:"Napoléon",v:1821}]},
{t:'histo',c:"Du plus vaste empire au plus petit",mes:"superficie à son apogée",u:"millions de km²",
 i:[{l:"Empire britannique",v:35.5},{l:"Empire mongol",v:24},{l:"Empire russe",v:22.8},{l:"Empire romain",v:5}]},
{t:'histo',c:"De la plus longue durée au plus courte",mes:"durée de l'empire ou du royaume",u:"ans",
 i:[{l:"Empire romain d'Orient",v:1058},{l:"Empire ottoman",v:623},{l:"Empire romain d'Occident",v:503},{l:"Empire mongol",v:162}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la première utilisation",u:"",rev:1,
 i:[{l:"Roue",v:-3500},{l:"Écriture",v:-3200},{l:"Papier",v:105},{l:"Poudre à canon",v:850}]},
{t:'histo',c:"De la plus meurtrière à la moins meurtrière",mes:"morts estimés",u:"millions de morts",
 i:[{l:"Seconde Guerre mondiale",v:70},{l:"Peste noire",v:50},{l:"Grippe espagnole",v:40},{l:"Première Guerre mondiale",v:20}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de fondation de la ville",u:"",rev:1,
 i:[{l:"Damas",v:-4000},{l:"Athènes",v:-1400},{l:"Rome",v:-753},{l:"New York",v:1624}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'invention",u:"",rev:1,
 i:[{l:"Boussole",v:1040},{l:"Lunettes",v:1286},{l:"Microscope",v:1590},{l:"Vaccin",v:1796}]},
{t:'histo',c:"De la plus grande armée à la plus petite",mes:"soldats engagés dans la bataille",u:"soldats",
 i:[{l:"Stalingrad",v:2200000},{l:"Waterloo",v:190000},{l:"Austerlitz",v:158000},{l:"Azincourt",v:30000}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de construction du monument",u:"",rev:1,
 i:[{l:"Stonehenge",v:-2500},{l:"Parthénon",v:-438},{l:"Notre-Dame de Paris",v:1345},{l:"Taj Mahal",v:1653}]},

/* ---------- technologie ---------- */
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de la première version",u:"",rev:1,
 i:[{l:"Windows",v:1985},{l:"Linux",v:1991},{l:"Android",v:2008},{l:"ChatGPT",v:2022}]},
{t:'techno',c:"Du plus rapide au plus lent",mes:"débit de la connexion",u:"mégabits / s",
 i:[{l:"Fibre optique",v:1000},{l:"4G",v:100},{l:"ADSL",v:20},{l:"Modem 56k",v:0.056}]},
{t:'techno',c:"Du plus de transistors au moins",mes:"transistors dans la puce",u:"millions de transistors",
 i:[{l:"Apple M2 Ultra",v:134000},{l:"Pentium 4",v:42},{l:"Intel 486",v:1.2},{l:"Intel 4004",v:0.0023}]},
{t:'techno',c:"Du plus cher au moins cher au lancement",mes:"prix de sortie converti en euros d'aujourd'hui",u:"€",
 i:[{l:"Apple Lisa",v:25000},{l:"Macintosh 1984",v:7000},{l:"iPhone 2007",v:750},{l:"Raspberry Pi",v:35}]},
{t:'techno',c:"Du plus lourd au plus léger",mes:"masse de l'appareil",u:"kg",
 i:[{l:"ENIAC",v:27000},{l:"Premier téléphone portable",v:1.1},{l:"Ordinateur portable actuel",v:1.4},{l:"Téléphone actuel",v:0.19}]},
{t:'techno',c:"Du plus grand nombre d'articles au plus petit",mes:"articles publiés dans cette langue",u:"millions d'articles",
 i:[{l:"Wikipédia en anglais",v:6.8},{l:"Wikipédia en allemand",v:2.9},{l:"Wikipédia en français",v:2.6},{l:"Wikipédia en italien",v:1.9}]},
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de création du service",u:"",rev:1,
 i:[{l:"Google",v:1998},{l:"Facebook",v:2004},{l:"WhatsApp",v:2009},{l:"TikTok",v:2016}]},
{t:'techno',c:"De la plus grande capacité à la plus petite",mes:"données que le support peut contenir",u:"gigaoctets",
 i:[{l:"Disque dur 4 To",v:4000},{l:"Blu-ray",v:25},{l:"DVD",v:4.7},{l:"CD",v:0.7}]},

/* ---------- cuisine ---------- */
{t:'cuisine',c:"Du plus consommé au moins consommé",mes:"production mondiale annuelle",u:"millions de tonnes",
 i:[{l:"Canne à sucre",v:1900},{l:"Maïs",v:1200},{l:"Blé",v:780},{l:"Pomme de terre",v:375}]},
{t:'cuisine',c:"Du plus fort au plus léger",mes:"degré d'alcool",u:"% vol.",
 i:[{l:"Absinthe",v:70},{l:"Whisky",v:40},{l:"Vin",v:12},{l:"Bière",v:5}]},
{t:'cuisine',c:"Du plus long affinage au plus court",mes:"durée d'affinage minimale",u:"mois",
 i:[{l:"Parmesan",v:24},{l:"Comté",v:12},{l:"Roquefort",v:3},{l:"Camembert",v:1}]},
{t:'cuisine',c:"Du plus de caféine au moins",mes:"caféine pour une tasse ou un verre",u:"mg",
 i:[{l:"Expresso double",v:130},{l:"Café filtre",v:95},{l:"Thé noir",v:47},{l:"Cola",v:34}]},
{t:'cuisine',c:"Du plus long temps de cuisson au plus court",mes:"durée de cuisson recommandée",u:"minutes",
 i:[{l:"Pot-au-feu",v:180},{l:"Riz complet",v:45},{l:"Pâtes",v:9},{l:"Œuf à la coque",v:3}]},
{t:'cuisine',c:"Du plus vieux au plus récent",mes:"année d'apparition du plat ou du produit",u:"",rev:1,
 i:[{l:"Pain",v:-8000},{l:"Fromage",v:-5500},{l:"Pizza margherita",v:1889},{l:"Nutella",v:1964}]},
{t:'cuisine',c:"Du plus de protéines au moins",mes:"protéines pour 100 grammes",u:"g / 100 g",
 i:[{l:"Parmesan",v:38},{l:"Bœuf",v:26},{l:"Lentilles cuites",v:9},{l:"Lait",v:3.4}]},
{t:'cuisine',c:"Du plus salé au moins salé",mes:"sel pour 100 grammes",u:"g / 100 g",
 i:[{l:"Sauce soja",v:16},{l:"Roquefort",v:3.5},{l:"Pain",v:1.2},{l:"Lait",v:0.05}]},

/* ---------- sport ---------- */
{t:'sport',c:"Du record le plus rapide au plus lent",mes:"vitesse moyenne du record du monde",u:"km/h",
 i:[{l:"100 m",v:37.6},{l:"400 m",v:32.5},{l:"1500 m",v:25.4},{l:"Marathon",v:20.9}]},
{t:'sport',c:"Du plus de titres au moins",mes:"Coupes du monde de football remportées",u:"titres",
 i:[{l:"Brésil",v:5},{l:"Allemagne",v:4},{l:"Argentine",v:3},{l:"France",v:2}]},
{t:'sport',c:"Du plus lourd au plus léger",mes:"masse du ballon ou de la balle",u:"g",
 i:[{l:"Ballon de basket",v:620},{l:"Ballon de football",v:430},{l:"Balle de tennis",v:58},{l:"Balle de golf",v:46}]},
{t:'sport',c:"Du plus ancien au plus récent",mes:"année d'entrée aux Jeux olympiques",u:"",rev:1,
 i:[{l:"Athlétisme",v:1896},{l:"Football",v:1900},{l:"Basket",v:1936},{l:"Escalade",v:2020}]},
{t:'sport',c:"De la plus longue épreuve à la plus courte",mes:"distance de l'épreuve",u:"km",
 i:[{l:"Tour de France",v:3400},{l:"Ironman",v:226},{l:"Marathon",v:42},{l:"10 000 m",v:10}]},
{t:'sport',c:"Du plus grand stade au plus petit",mes:"places assises",u:"places",
 i:[{l:"Rungrado, Pyongyang",v:114000},{l:"Camp Nou",v:99000},{l:"Stade de France",v:80000},{l:"Roland-Garros, court central",v:15000}]},
{t:'sport',c:"Du plus haut record au plus bas",mes:"hauteur ou longueur du record du monde",u:"m",
 i:[{l:"Saut en longueur",v:8.95},{l:"Saut à la perche",v:6.25},{l:"Triple saut, dernier bond",v:5.5},{l:"Saut en hauteur",v:2.45}]},

/* ---------- musique, art, pop, récits ---------- */
{t:'musique',c:"Du plus ancien au plus récent",mes:"année de naissance du compositeur",u:"",rev:1,
 i:[{l:"Bach",v:1685},{l:"Mozart",v:1756},{l:"Beethoven",v:1770},{l:"Debussy",v:1862}]},
{t:'musique',c:"De la symphonie la plus longue à la plus courte",mes:"durée d'exécution",u:"minutes",
 i:[{l:"Troisième de Mahler",v:100},{l:"Neuvième de Beethoven",v:70},{l:"Cinquième de Beethoven",v:33},{l:"Quarantième de Mozart",v:26}]},
{t:'musique',c:"Du plus de cordes au moins",mes:"cordes sur l'instrument",u:"cordes",
 i:[{l:"Piano",v:230},{l:"Harpe",v:47},{l:"Guitare",v:6},{l:"Violon",v:4}]},
{t:'musique',c:"Du plus grand orchestre au plus petit",mes:"musiciens dans la formation",u:"musiciens",
 i:[{l:"Orchestre symphonique",v:90},{l:"Orchestre de chambre",v:25},{l:"Quatuor",v:4},{l:"Duo",v:2}]},
{t:'art',c:"Du plus cher au moins cher",mes:"prix de la dernière vente aux enchères",u:"millions de dollars",
 i:[{l:"Salvator Mundi",v:450},{l:"Les Femmes d'Alger",v:179},{l:"Le Cri, version pastel",v:120},{l:"Nu couché de Modigliani",v:170}]},
{t:'art',c:"Du plus ancien au plus récent",mes:"année de réalisation",u:"",rev:1,
 i:[{l:"Grotte de Lascaux",v:-17000},{l:"Vénus de Milo",v:-100},{l:"La Joconde",v:1503},{l:"La Nuit étoilée",v:1889}]},
{t:'art',c:"Du musée le plus visité au moins visité",mes:"visiteurs par an",u:"millions de visiteurs",
 i:[{l:"Louvre",v:8.9},{l:"Musées du Vatican",v:6.8},{l:"British Museum",v:5.8},{l:"Musée d'Orsay",v:3.9}]},
{t:'pop',c:"Du plus rentable au moins rentable",mes:"recettes mondiales au cinéma",u:"milliards de dollars",
 i:[{l:"Avatar",v:2.92},{l:"Avengers: Endgame",v:2.79},{l:"Titanic",v:2.26},{l:"Star Wars, épisode VII",v:2.07}]},
{t:'pop',c:"Du plus ancien au plus récent",mes:"année de sortie du film",u:"",rev:1,
 i:[{l:"Le Magicien d'Oz",v:1939},{l:"Les Dents de la mer",v:1975},{l:"Jurassic Park",v:1993},{l:"Avatar",v:2009}]},
{t:'pop',c:"De la série la plus longue à la plus courte",mes:"épisodes diffusés",u:"épisodes",
 i:[{l:"Les Simpson",v:780},{l:"Friends",v:236},{l:"Game of Thrones",v:73},{l:"Chernobyl",v:5}]},
{t:'litt',c:"Du plus long au plus court",mes:"nombre de mots du roman",u:"milliers de mots",
 i:[{l:"À la recherche du temps perdu",v:1267},{l:"Guerre et Paix",v:587},{l:"Les Misérables",v:530},{l:"Le Petit Prince",v:16}]},
{t:'litt',c:"Du plus ancien au plus récent",mes:"année de parution",u:"",rev:1,
 i:[{l:"Le Comte de Monte-Cristo",v:1844},{l:"Vingt mille lieues sous les mers",v:1870},{l:"Le Petit Prince",v:1943},{l:"Harry Potter à l'école des sorciers",v:1997}]},
{t:'langue',c:"Du plus de mots au moins",mes:"entrées dans le dictionnaire de référence",u:"mots",
 i:[{l:"Anglais",v:171000},{l:"Allemand",v:135000},{l:"Français",v:60000},{l:"Espagnol",v:93000}]},
{t:'langue',c:"Du plus ancien au plus récent",mes:"année d'apparition de l'écriture",u:"",rev:1,
 i:[{l:"Cunéiforme",v:-3200},{l:"Hiéroglyphes",v:-3100},{l:"Alphabet grec",v:-800},{l:"Alphabet latin",v:-700}]},
/* ---------- vague 2 ---------- */
{t:'animaux',c:"Du plus grand troupeau au plus petit",mes:"individus dans le plus grand rassemblement observé",u:"individus",
 i:[{l:"Criquets pèlerins",v:50000000000},{l:"Sardines du Natal",v:1000000000},{l:"Bisons d'Amérique, XIXᵉ",v:4000000},{l:"Gnous du Serengeti",v:1300000}]},
{t:'animaux',c:"Du plus grand nombre de pattes au plus petit",mes:"pattes de l'animal adulte",u:"pattes",
 i:[{l:"Mille-pattes record",v:1306},{l:"Cloporte",v:14},{l:"Araignée",v:8},{l:"Insecte",v:6}]},
{t:'animaux',c:"De la plus grande portée à la plus petite",mes:"petits par portée en moyenne",u:"petits",
 i:[{l:"Tenrec",v:20},{l:"Truie",v:12},{l:"Chatte",v:5},{l:"Jument",v:1}]},
{t:'animaux',c:"Du plus vieux fossile au plus récent",mes:"apparition du groupe dans les fossiles",u:"millions d'années",
 i:[{l:"Méduse",v:600},{l:"Requin",v:420},{l:"Dinosaure",v:230},{l:"Humain moderne",v:0.3}]},
{t:'animaux',c:"Du plus grand appétit au plus petit",mes:"part de son poids mangée chaque jour",u:"% de son poids",
 i:[{l:"Musaraigne",v:200},{l:"Colibri",v:100},{l:"Panda",v:15},{l:"Humain",v:2}]},
{t:'animaux',c:"De la vue la plus perçante à la moins bonne",mes:"acuité visuelle comparée à la nôtre",u:"× l'œil humain",
 i:[{l:"Aigle",v:8},{l:"Faucon",v:5},{l:"Humain",v:1},{l:"Chien",v:0.4}]},
{t:'animaux',c:"Du plus grand crâne au plus petit",mes:"longueur du crâne",u:"cm",
 i:[{l:"Cachalot",v:500},{l:"Éléphant",v:120},{l:"Cheval",v:60},{l:"Humain",v:20}]},
{t:'animaux',c:"Du plus rapide au plus lent en piqué",mes:"vitesse maximale en piqué",u:"km/h",
 i:[{l:"Faucon pèlerin",v:389},{l:"Aigle royal",v:320},{l:"Martinet",v:170},{l:"Pigeon",v:100}]},
{t:'animaux',c:"De la plus grande toile à la plus petite",mes:"surface de la toile tissée",u:"m²",
 i:[{l:"Néphile de Darwin",v:2.8},{l:"Argiope",v:0.3},{l:"Épeire diadème",v:0.15},{l:"Araignée domestique",v:0.02}]},
{t:'animaux',c:"Du plus d'eau bue au moins",mes:"eau bue par jour",u:"litres / jour",
 i:[{l:"Éléphant",v:200},{l:"Vache",v:100},{l:"Cheval",v:40},{l:"Humain",v:2.5}]},
{t:'animaux',c:"Du plus grand nid au plus petit",mes:"diamètre du nid",u:"cm",
 i:[{l:"Pygargue à tête blanche",v:250},{l:"Cigogne",v:150},{l:"Merle",v:15},{l:"Colibri",v:4}]},
{t:'animaux',c:"Du plus grand plongeon en apnée au plus court",mes:"durée maximale sous l'eau",u:"minutes",
 i:[{l:"Baleine à bec de Cuvier",v:222},{l:"Cachalot",v:90},{l:"Tortue verte",v:45},{l:"Humain entraîné",v:11}]},
{t:'geo',c:"De la plus grande île artificielle à la plus petite",mes:"superficie gagnée sur la mer",u:"km²",
 i:[{l:"Flevopolder",v:970},{l:"Île de Kansai",v:10.7},{l:"Palm Jumeirah",v:5.6},{l:"Notre-Dame, île de la Cité",v:0.2}]},
{t:'geo',c:"Du tunnel le plus long au plus court",mes:"longueur du tunnel",u:"km",
 i:[{l:"Gothard, base",v:57},{l:"Seikan",v:53.9},{l:"Tunnel sous la Manche",v:50.5},{l:"Mont-Blanc",v:11.6}]},
{t:'geo',c:"Du plus grand port au plus petit",mes:"conteneurs traités par an",u:"millions de conteneurs",
 i:[{l:"Shanghai",v:47},{l:"Singapour",v:37},{l:"Rotterdam",v:14},{l:"Le Havre",v:3}]},
{t:'geo',c:"Du pays le plus riche au moins riche",mes:"richesse produite par habitant",u:"milliers de dollars / hab.",
 i:[{l:"Luxembourg",v:128},{l:"Suisse",v:99},{l:"États-Unis",v:80},{l:"France",v:44}]},
{t:'geo',c:"Du plus vieux parc national au plus récent",mes:"année de création",u:"",rev:1,
 i:[{l:"Yellowstone",v:1872},{l:"Kruger",v:1926},{l:"Serengeti",v:1951},{l:"Vanoise",v:1963}]},
{t:'geo',c:"De la plus grande cathédrale à la plus petite",mes:"surface au sol",u:"m²",
 i:[{l:"Saint-Pierre de Rome",v:15160},{l:"Cathédrale de Séville",v:11520},{l:"Cathédrale de Milan",v:11700},{l:"Notre-Dame de Paris",v:5500}]},
{t:'geo',c:"Du plus grand glacier au plus petit",mes:"longueur du glacier",u:"km",
 i:[{l:"Lambert, Antarctique",v:400},{l:"Hubbard, Alaska",v:122},{l:"Aletsch, Suisse",v:23},{l:"Mer de Glace",v:7}]},
{t:'geo',c:"Du plus grand séisme au plus faible",mes:"magnitude sur l'échelle de moment",u:"magnitude",
 i:[{l:"Valdivia 1960",v:9.5},{l:"Sumatra 2004",v:9.1},{l:"Tōhoku 2011",v:9},{l:"L'Aquila 2009",v:6.3}]},
{t:'geo',c:"De la plus grande éruption à la plus faible",mes:"volume de matière éjectée",u:"km³",
 i:[{l:"Toba, il y a 74 000 ans",v:2800},{l:"Tambora 1815",v:150},{l:"Krakatoa 1883",v:20},{l:"Saint Helens 1980",v:1}]},
{t:'geo',c:"Du pays le plus boisé au moins boisé",mes:"part du territoire couverte de forêt",u:"% du territoire",
 i:[{l:"Finlande",v:73},{l:"Suède",v:69},{l:"Brésil",v:59},{l:"France",v:31}]},
{t:'geo',c:"De la plus haute construction à la plus basse",mes:"hauteur totale",u:"m",
 i:[{l:"Burj Khalifa",v:828},{l:"Tokyo Skytree",v:634},{l:"Empire State Building",v:443},{l:"Tour Eiffel",v:330}]},
{t:'espace',c:"Du plus gros astéroïde au plus petit",mes:"diamètre moyen",u:"km",
 i:[{l:"Cérès",v:940},{l:"Vesta",v:525},{l:"Pallas",v:512},{l:"Éros",v:17}]},
{t:'espace',c:"De la plus longue comète à la plus courte",mes:"période de retour",u:"ans",
 i:[{l:"Hale-Bopp",v:2533},{l:"Halley",v:76},{l:"Tempel 1",v:5.5},{l:"Encke",v:3.3}]},
{t:'espace',c:"Du plus proche du Soleil au plus loin",mes:"distance moyenne au Soleil",u:"millions de km",rev:1,
 i:[{l:"Mercure",v:58},{l:"Terre",v:150},{l:"Ceinture d'astéroïdes",v:400},{l:"Uranus",v:2870}]},
{t:'espace',c:"De la plus grande vitesse à la plus faible",mes:"vitesse nécessaire pour s'arracher à l'astre",u:"km/s",
 i:[{l:"Soleil",v:618},{l:"Jupiter",v:59.5},{l:"Terre",v:11.2},{l:"Lune",v:2.4}]},
{t:'espace',c:"Du plus ancien au plus récent",mes:"année de la découverte",u:"",rev:1,
 i:[{l:"Lunes de Jupiter",v:1610},{l:"Uranus",v:1781},{l:"Neptune",v:1846},{l:"Pluton",v:1930}]},
{t:'espace',c:"Du plus grand cratère au plus petit",mes:"diamètre du cratère",u:"km",
 i:[{l:"Bassin Pôle Sud-Aitken, Lune",v:2500},{l:"Chicxulub, Terre",v:180},{l:"Vredefort, Terre",v:300},{l:"Meteor Crater, Arizona",v:1.2}]},
{t:'sci',c:"Du plus grand nombre d'atomes au plus petit",mes:"atomes dans un gramme de matière",u:"× 10²¹ atomes",
 i:[{l:"Hydrogène",v:600},{l:"Carbone",v:50},{l:"Fer",v:11},{l:"Or",v:3}]},
{t:'sci',c:"Du meilleur conducteur au moins bon",mes:"conductivité électrique",u:"% de celle de l'argent",
 i:[{l:"Argent",v:100},{l:"Cuivre",v:97},{l:"Aluminium",v:61},{l:"Fer",v:17}]},
{t:'sci',c:"Du plus court au plus long",mes:"durée du phénomène",u:"secondes",rev:1,
 i:[{l:"Éclair",v:0.0002},{l:"Battement de cils",v:0.15},{l:"Battement de cœur",v:0.9},{l:"Respiration",v:4}]},
{t:'sci',c:"De la plus haute énergie à la plus basse",mes:"énergie du rayonnement",u:"électronvolts",
 i:[{l:"Rayon gamma",v:1000000},{l:"Rayon X",v:1000},{l:"Ultraviolet",v:10},{l:"Lumière visible",v:2}]},
{t:'sci',c:"Du plus lourd au plus léger",mes:"masse atomique",u:"unités",
 i:[{l:"Uranium",v:238},{l:"Fer",v:56},{l:"Carbone",v:12},{l:"Hydrogène",v:1}]},
{t:'sci',c:"Du plus grand nombre de neurones au plus petit",mes:"neurones dans le cerveau",u:"milliards de neurones",
 i:[{l:"Éléphant",v:257},{l:"Humain",v:86},{l:"Chien",v:2.2},{l:"Souris",v:0.07}]},
{t:'sci',c:"De la plus longue molécule à la plus courte",mes:"longueur dépliée",u:"m",
 i:[{l:"ADN d'une cellule humaine",v:2},{l:"Chromosome 1",v:0.085},{l:"Gène moyen",v:0.00002},{l:"Protéine",v:0.00000001}]},
{t:'sci',c:"Du plus explosif au moins explosif",mes:"énergie dégagée par kilo",u:"mégajoules / kg",
 i:[{l:"Uranium 235",v:83000000},{l:"Essence",v:47},{l:"TNT",v:4.6},{l:"Poudre noire",v:3}]},
{t:'sci',c:"Du plus grand grossissement au plus petit",mes:"grossissement de l'instrument",u:"×",
 i:[{l:"Microscope électronique",v:10000000},{l:"Microscope optique",v:1500},{l:"Télescope amateur",v:200},{l:"Loupe",v:10}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la première apparition",u:"",rev:1,
 i:[{l:"Monnaie frappée",v:-600},{l:"Papier-monnaie",v:1023},{l:"Chèque",v:1659},{l:"Carte bancaire",v:1950}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de fondation de l'université",u:"",rev:1,
 i:[{l:"Bologne",v:1088},{l:"Oxford",v:1096},{l:"Sorbonne",v:1257},{l:"Harvard",v:1636}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'exploration",u:"",rev:1,
 i:[{l:"Tour du monde de Magellan",v:1519},{l:"Pôle Sud par Amundsen",v:1911},{l:"Everest par Hillary",v:1953},{l:"Fosse des Mariannes",v:1960}]},
{t:'histo',c:"De la plus longue occupation à la plus courte",mes:"durée de la domination sur le territoire",u:"ans",
 i:[{l:"Rome en Gaule",v:500},{l:"Ottomans dans les Balkans",v:480},{l:"Espagne en Amérique",v:300},{l:"Britanniques en Inde",v:190}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la première épidémie décrite",u:"",rev:1,
 i:[{l:"Peste de Justinien",v:541},{l:"Peste noire",v:1347},{l:"Choléra, première pandémie",v:1817},{l:"Grippe espagnole",v:1918}]},
{t:'histo',c:"De la plus grande flotte à la plus petite",mes:"navires engagés",u:"navires",
 i:[{l:"Débarquement de Normandie",v:6939},{l:"Invincible Armada",v:130},{l:"Trafalgar",v:60},{l:"Voyage de Colomb",v:3}]},
{t:'techno',c:"Du plus grand nombre de lignes de code au plus petit",mes:"lignes de code du logiciel",u:"millions de lignes",
 i:[{l:"Google, tout le code",v:2000},{l:"Windows 10",v:50},{l:"Noyau Linux",v:30},{l:"Navette spatiale",v:0.4}]},
{t:'techno',c:"Du plus puissant au moins puissant",mes:"calculs par seconde",u:"milliards d'opérations / s",
 i:[{l:"Superordinateur Frontier",v:1100000000},{l:"Console de jeu récente",v:10000},{l:"Téléphone",v:1000},{l:"Ordinateur d'Apollo",v:0.0000855}]},
{t:'techno',c:"Du plus ancien au plus récent",mes:"année de commercialisation",u:"",rev:1,
 i:[{l:"Cassette audio",v:1963},{l:"Disquette",v:1971},{l:"CD",v:1982},{l:"Clé USB",v:2000}]},
{t:'techno',c:"De la plus grande autonomie à la plus faible",mes:"autonomie annoncée",u:"km",
 i:[{l:"Voiture diesel",v:1200},{l:"Voiture électrique récente",v:500},{l:"Trottinette électrique",v:40},{l:"Vélo électrique",v:80}]},
{t:'cuisine',c:"Du plus gros producteur au plus petit",mes:"production annuelle de vin",u:"millions d'hectolitres",
 i:[{l:"Italie",v:50},{l:"France",v:46},{l:"Espagne",v:35},{l:"États-Unis",v:22}]},
{t:'cuisine',c:"Du plus consommé au moins consommé",mes:"consommation par habitant et par an",u:"kg / hab. / an",
 i:[{l:"Riz en Asie du Sud-Est",v:150},{l:"Pain en France",v:58},{l:"Fromage en France",v:26},{l:"Chocolat en Suisse",v:11}]},
{t:'cuisine',c:"Du plus long au plus court",mes:"durée de conservation à température ambiante",u:"jours",
 i:[{l:"Miel",v:36500},{l:"Riz sec",v:1800},{l:"Pomme",v:30},{l:"Pain frais",v:3}]},
{t:'cuisine',c:"Du plus riche en fer au moins riche",mes:"fer pour 100 grammes",u:"mg / 100 g",
 i:[{l:"Boudin noir",v:23},{l:"Lentilles",v:3.3},{l:"Épinards",v:2.7},{l:"Bœuf",v:2.6}]},
{t:'sport',c:"Du plus grand nombre de spectateurs au plus petit",mes:"audience télévisée mondiale",u:"millions de spectateurs",
 i:[{l:"Finale de Coupe du monde",v:1500},{l:"Cérémonie olympique",v:900},{l:"Super Bowl",v:115},{l:"Finale de Roland-Garros",v:20}]},
{t:'sport',c:"De la plus longue partie à la plus courte",mes:"durée du match le plus long jamais joué",u:"heures",
 i:[{l:"Tennis, Isner-Mahut",v:11.1},{l:"Échecs, partie la plus longue",v:20},{l:"Cricket, test match",v:45},{l:"Football, prolongations",v:2.5}]},
{t:'sport',c:"Du plus grand écart au plus petit",mes:"points marqués par le vainqueur",u:"points",
 i:[{l:"Basket, record NBA d'une équipe",v:186},{l:"Rugby, record de test-match",v:145},{l:"Handball, match courant",v:30},{l:"Football, record de Ligue 1",v:12}]},
{t:'pop',c:"De la plus longue franchise à la plus courte",mes:"films sortis dans la série",u:"films",
 i:[{l:"James Bond",v:25},{l:"Star Wars",v:12},{l:"Harry Potter",v:8},{l:"Le Seigneur des anneaux",v:3}]},
{t:'pop',c:"Du plus grand nombre d'Oscars au plus petit",mes:"statuettes remportées par le film",u:"Oscars",
 i:[{l:"Ben-Hur",v:11},{l:"Le Patient anglais",v:9},{l:"La La Land",v:6},{l:"Parasite",v:4}]},
{t:'pop',c:"Du plus vieux studio au plus récent",mes:"année de fondation",u:"",rev:1,
 i:[{l:"Gaumont",v:1895},{l:"Universal",v:1912},{l:"Warner Bros",v:1923},{l:"Pixar",v:1986}]},
{t:'musique',c:"Du plus grand nombre de touches au plus petit",mes:"touches sur l'instrument",u:"touches",
 i:[{l:"Piano de concert",v:88},{l:"Accordéon",v:41},{l:"Mélodica",v:32},{l:"Kalimba",v:17}]},
{t:'musique',c:"De la plus grande gamme à la plus petite",mes:"notes différentes dans la gamme",u:"notes",
 i:[{l:"Gamme chromatique",v:12},{l:"Gamme majeure",v:7},{l:"Gamme pentatonique",v:5},{l:"Triton",v:3}]},
{t:'art',c:"Du plus grand musée au plus petit",mes:"surface d'exposition",u:"m²",
 i:[{l:"Louvre",v:72735},{l:"Ermitage",v:66842},{l:"Metropolitan",v:58820},{l:"Musée d'Orsay",v:16000}]},
{t:'art',c:"Du plus ancien au plus récent",mes:"année de naissance du peintre",u:"",rev:1,
 i:[{l:"Léonard de Vinci",v:1452},{l:"Rembrandt",v:1606},{l:"Monet",v:1840},{l:"Picasso",v:1881}]},
{t:'litt',c:"Du plus ancien prix au plus récent",mes:"année de création du prix",u:"",rev:1,
 i:[{l:"Prix Goncourt",v:1903},{l:"Prix Nobel de littérature",v:1901},{l:"Prix Renaudot",v:1926},{l:"Prix Booker",v:1969}]},
{t:'litt',c:"Du plus traduit au moins traduit",mes:"langues dans lesquelles l'œuvre existe",u:"langues",
 i:[{l:"Bible",v:3400},{l:"Le Petit Prince",v:500},{l:"Pinocchio",v:300},{l:"Harry Potter",v:80}]},
{t:'langue',c:"Du plus long mot au plus court",mes:"lettres du mot le plus long du dictionnaire",u:"lettres",
 i:[{l:"Allemand",v:63},{l:"Français",v:25},{l:"Anglais",v:29},{l:"Espagnol",v:23}]},
{t:'langue',c:"Du plus de pays au moins",mes:"pays où la langue est officielle",u:"pays",
 i:[{l:"Anglais",v:59},{l:"Français",v:29},{l:"Arabe",v:25},{l:"Espagnol",v:21}]},
/* ---------- vague 3 ---------- */
{t:'animaux',c:"Du plus grand bec au plus petit",mes:"longueur du bec",u:"cm",
 i:[{l:"Pélican australien",v:47},{l:"Toucan toco",v:20},{l:"Colibri porte-épée",v:11},{l:"Moineau",v:1.2}]},
{t:'animaux',c:"De la plus longue corne au plus courte",mes:"longueur de la corne ou défense",u:"cm",
 i:[{l:"Défense d'éléphant",v:350},{l:"Corne de narval",v:270},{l:"Corne de rhinocéros",v:150},{l:"Bois de cerf",v:110}]},
{t:'animaux',c:"Du plus grand nombre d'yeux au plus petit",mes:"yeux de l'animal",u:"yeux",
 i:[{l:"Méduse-boîte",v:24},{l:"Araignée sauteuse",v:8},{l:"Abeille",v:5},{l:"Humain",v:2}]},
{t:'animaux',c:"Du plus lourd insecte au plus léger",mes:"masse de l'insecte adulte",u:"g",
 i:[{l:"Weta géant",v:70},{l:"Scarabée Goliath",v:50},{l:"Hanneton",v:1},{l:"Moustique",v:0.0025}]},
{t:'animaux',c:"De la plus grande colonie au plus petite",mes:"individus dans la colonie de fourmis",u:"millions d'individus",
 i:[{l:"Supercolonie argentine",v:1000},{l:"Fourmi légionnaire",v:20},{l:"Fourmi coupeuse",v:8},{l:"Fourmi noire de jardin",v:0.015}]},
{t:'animaux',c:"Du plus grand nombre d'espèces menacées au plus petit",mes:"espèces classées en danger dans le groupe",u:"espèces",
 i:[{l:"Amphibiens",v:2400},{l:"Poissons",v:2000},{l:"Oiseaux",v:1400},{l:"Mammifères",v:1300}]},
{t:'animaux',c:"Du plus grand pas au plus petit",mes:"longueur d'une foulée",u:"m",
 i:[{l:"Girafe",v:4.5},{l:"Cheval au galop",v:4},{l:"Autruche",v:3.5},{l:"Humain qui court",v:1.5}]},
{t:'animaux',c:"De la plus grande queue à la plus petite",mes:"longueur de la queue",u:"cm",
 i:[{l:"Paon, roue déployée",v:150},{l:"Kangourou",v:110},{l:"Écureuil",v:25},{l:"Lapin",v:7}]},
{t:'animaux',c:"Du plus grand carnivore terrestre au plus petit",mes:"masse du mâle adulte",u:"kg",
 i:[{l:"Ours kodiak",v:680},{l:"Tigre de Sibérie",v:300},{l:"Lion",v:190},{l:"Loup gris",v:45}]},
{t:'animaux',c:"De la plus grande empreinte à la plus petite",mes:"longueur de l'empreinte de patte",u:"cm",
 i:[{l:"Éléphant",v:50},{l:"Ours brun",v:25},{l:"Loup",v:11},{l:"Chat",v:4}]},
{t:'geo',c:"De la plus grande place à la plus petite",mes:"superficie de la place",u:"m²",
 i:[{l:"Place Tian'anmen",v:440000},{l:"Place Rouge",v:73000},{l:"Place de la Concorde",v:86400},{l:"Place Saint-Marc",v:12000}]},
{t:'geo',c:"Du plus grand marché au plus petit",mes:"visiteurs par jour",u:"visiteurs / jour",
 i:[{l:"Grand Bazar d'Istanbul",v:400000},{l:"Marché de Tsukiji",v:60000},{l:"Marché de Rungis",v:26000},{l:"Marché d'Aligre",v:8000}]},
{t:'geo',c:"De la plus longue muraille à la plus courte",mes:"longueur du mur",u:"km",
 i:[{l:"Grande Muraille de Chine",v:21196},{l:"Mur de sable, Sahara",v:2700},{l:"Mur d'Hadrien",v:117},{l:"Mur de Berlin",v:155}]},
{t:'geo',c:"De la plus grande baie à la plus petite",mes:"superficie",u:"km²",
 i:[{l:"Baie du Bengale",v:2172000},{l:"Baie d'Hudson",v:1230000},{l:"Golfe du Mexique",v:1550000},{l:"Baie de Somme",v:70}]},
{t:'geo',c:"Du pays au plus de sites classés au moins",mes:"sites inscrits au patrimoine mondial",u:"sites",
 i:[{l:"Italie",v:60},{l:"Chine",v:59},{l:"Allemagne",v:54},{l:"France",v:53}]},
{t:'geo',c:"De la plus grande cascade souterraine à la plus petite",mes:"profondeur du gouffre",u:"m",
 i:[{l:"Gouffre Veryovkina",v:2212},{l:"Gouffre Krubera",v:2199},{l:"Gouffre Berger",v:1271},{l:"Gouffre de Padirac",v:103}]},
{t:'geo',c:"Du pays le plus visité au moins visité",mes:"touristes étrangers par an",u:"millions de touristes",
 i:[{l:"France",v:100},{l:"Espagne",v:85},{l:"États-Unis",v:66},{l:"Italie",v:57}]},
{t:'geo',c:"De la plus grande centrale au plus petite",mes:"puissance installée",u:"gigawatts",
 i:[{l:"Barrage des Trois-Gorges",v:22.5},{l:"Itaipu",v:14},{l:"Centrale de Gravelines",v:5.7},{l:"Parc éolien de Fécamp",v:0.5}]},
{t:'espace',c:"Du plus grand volcan au plus petit",mes:"hauteur du volcan",u:"km",
 i:[{l:"Olympus Mons, Mars",v:22},{l:"Rheasilvia, Vesta",v:22.5},{l:"Mauna Kea, Terre",v:10},{l:"Etna, Terre",v:3.4}]},
{t:'espace',c:"Du plus grand anneau au plus petit",mes:"diamètre du système d'anneaux",u:"km",
 i:[{l:"Saturne",v:480000},{l:"Uranus",v:100000},{l:"Jupiter",v:250000},{l:"Neptune",v:63000}]},
{t:'espace',c:"Du plus vieux au plus jeune",mes:"âge de l'objet",u:"milliards d'années",
 i:[{l:"Univers",v:13.8},{l:"Voie lactée",v:13.6},{l:"Soleil",v:4.6},{l:"Terre",v:4.5}]},
{t:'espace',c:"De la plus grande sonde à la plus petite",mes:"masse au lancement",u:"kg",
 i:[{l:"Cassini",v:5712},{l:"Curiosity",v:899},{l:"Voyager 1",v:722},{l:"Philae",v:100}]},
{t:'espace',c:"Du plus loin voyagé au moins loin",mes:"distance parcourue depuis la Terre",u:"milliards de km",
 i:[{l:"Voyager 1",v:24},{l:"Voyager 2",v:20},{l:"Pioneer 10",v:19},{l:"New Horizons",v:8.5}]},
{t:'sci',c:"Du plus grand nombre d'isotopes au plus petit",mes:"isotopes connus de l'élément",u:"isotopes",
 i:[{l:"Césium",v:40},{l:"Fer",v:28},{l:"Carbone",v:15},{l:"Hydrogène",v:7}]},
{t:'sci',c:"De la plus forte tension à la plus faible",mes:"tension électrique",u:"volts",
 i:[{l:"Éclair",v:100000000},{l:"Ligne à haute tension",v:400000},{l:"Prise domestique",v:230},{l:"Pile AA",v:1.5}]},
{t:'sci',c:"Du plus grand télescope naturel au plus petit",mes:"diamètre de la pupille ou de l'ouverture",u:"mm",
 i:[{l:"Œil de calmar géant",v:250},{l:"Œil d'autruche",v:50},{l:"Œil humain de nuit",v:8},{l:"Œil de mouche",v:0.8}]},
{t:'sci',c:"De la plus grande vitesse de chute à la plus faible",mes:"vitesse limite de chute dans l'air",u:"km/h",
 i:[{l:"Parachutiste en piqué",v:530},{l:"Parachutiste à plat",v:195},{l:"Goutte de pluie",v:32},{l:"Flocon de neige",v:5}]},
{t:'sci',c:"Du plus grand nombre de dents au plus petit",mes:"dents de lait ou définitives",u:"dents",
 i:[{l:"Dauphin",v:250},{l:"Chien",v:42},{l:"Humain adulte",v:32},{l:"Humain enfant",v:20}]},
{t:'sci',c:"De la plus grande capacité pulmonaire à la plus faible",mes:"volume d'air des poumons",u:"litres",
 i:[{l:"Baleine bleue",v:5000},{l:"Cheval",v:55},{l:"Humain athlète",v:7},{l:"Humain moyen",v:6}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la première représentation",u:"",rev:1,
 i:[{l:"Théâtre grec",v:-534},{l:"Commedia dell'arte",v:1545},{l:"Le Cid",v:1637},{l:"En attendant Godot",v:1953}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de la déclaration ou du traité",u:"",rev:1,
 i:[{l:"Magna Carta",v:1215},{l:"Traité de Westphalie",v:1648},{l:"Déclaration des droits de l'homme",v:1789},{l:"Traité de Rome",v:1957}]},
{t:'histo',c:"De la plus grande bibliothèque antique à la plus petite",mes:"rouleaux conservés, estimation",u:"rouleaux",
 i:[{l:"Alexandrie",v:400000},{l:"Pergame",v:200000},{l:"Villa des Papyrus",v:1800},{l:"Bibliothèque d'Assurbanipal",v:30000}]},
{t:'histo',c:"Du plus ancien au plus récent",mes:"année de l'abolition de l'esclavage",u:"",rev:1,
 i:[{l:"Royaume-Uni",v:1833},{l:"France, seconde abolition",v:1848},{l:"États-Unis",v:1865},{l:"Brésil",v:1888}]},
{t:'histo',c:"De la plus longue dynastie à la plus courte",mes:"durée du règne de la famille",u:"ans",
 i:[{l:"Dynastie japonaise",v:1700},{l:"Capétiens",v:800},{l:"Habsbourg",v:640},{l:"Romanov",v:304}]},
{t:'techno',c:"Du plus grand nombre d'utilisateurs au plus petit",mes:"utilisateurs du système d'exploitation",u:"% du marché",
 i:[{l:"Android",v:44},{l:"Windows",v:28},{l:"iOS",v:18},{l:"macOS",v:6}]},
{t:'techno',c:"Du plus ancien langage au plus récent",mes:"année de création du langage",u:"",rev:1,
 i:[{l:"Fortran",v:1957},{l:"C",v:1972},{l:"Python",v:1991},{l:"Rust",v:2010}]},
{t:'techno',c:"De la plus grande consommation à la plus faible",mes:"électricité consommée par an",u:"térawattheures",
 i:[{l:"Bitcoin",v:120},{l:"Centres de données de Google",v:24},{l:"Ville de Paris",v:11},{l:"Tour Eiffel",v:0.007}]},
{t:'techno',c:"Du plus rapide au plus lent",mes:"temps de charge d'une batterie complète",u:"minutes",rev:1,
 i:[{l:"Trottinette",v:180},{l:"Téléphone en charge rapide",v:35},{l:"Voiture sur superchargeur",v:25},{l:"Écouteurs sans fil",v:60}]},
{t:'cuisine',c:"Du plus grand nombre de variétés au plus petit",mes:"variétés recensées",u:"variétés",
 i:[{l:"Pomme",v:7500},{l:"Raisin",v:5000},{l:"Pomme de terre",v:4000},{l:"Banane",v:1000}]},
{t:'cuisine',c:"Du plus long à préparer au plus court",mes:"temps de préparation traditionnel",u:"heures",
 i:[{l:"Jambon de Parme",v:8760},{l:"Pain au levain",v:24},{l:"Bœuf bourguignon",v:3},{l:"Omelette",v:0.1}]},
{t:'cuisine',c:"Du plus riche en vitamine C au moins riche",mes:"vitamine C pour 100 grammes",u:"mg / 100 g",
 i:[{l:"Cassis",v:200},{l:"Kiwi",v:93},{l:"Orange",v:53},{l:"Pomme",v:5}]},
{t:'cuisine',c:"Du plus vieux vin au plus jeune",mes:"année de la bouteille la plus ancienne connue",u:"",rev:1,
 i:[{l:"Vin de Spire",v:325},{l:"Tokaji le plus ancien",v:1606},{l:"Château d'Yquem 1811",v:1811},{l:"Romanée-Conti 1945",v:1945}]},
{t:'sport',c:"Du plus grand nombre de participants au plus petit",mes:"athlètes engagés",u:"athlètes",
 i:[{l:"Jeux olympiques d'été",v:11000},{l:"Marathon de New York",v:50000},{l:"Tour de France",v:176},{l:"Finale de Coupe du monde",v:22}]},
{t:'sport',c:"Du plus lourd au plus léger",mes:"masse de l'équipement porté",u:"kg",
 i:[{l:"Plongeur en scaphandre",v:90},{l:"Joueur de football américain",v:9},{l:"Boxeur, gants",v:0.5},{l:"Coureur, chaussures",v:0.4}]},
{t:'sport',c:"De la plus haute vitesse au plus basse",mes:"vitesse atteinte dans la discipline",u:"km/h",
 i:[{l:"Ski de vitesse",v:255},{l:"Descente à ski",v:160},{l:"Cyclisme en descente",v:130},{l:"Course à pied",v:45}]},
{t:'pop',c:"Du plus grand nombre de vues au plus petit",mes:"vues cumulées de la vidéo",u:"milliards de vues",
 i:[{l:"Baby Shark",v:14},{l:"Despacito",v:8.4},{l:"Shape of You",v:6.3},{l:"Gangnam Style",v:5.1}]},
{t:'pop',c:"Du personnage le plus ancien au plus récent",mes:"année de création du personnage",u:"",rev:1,
 i:[{l:"Sherlock Holmes",v:1887},{l:"Mickey Mouse",v:1928},{l:"Superman",v:1938},{l:"Astérix",v:1959}]},
{t:'pop',c:"Du jeu vidéo le plus vendu au moins vendu",mes:"exemplaires vendus",u:"millions d'exemplaires",
 i:[{l:"Minecraft",v:300},{l:"Grand Theft Auto V",v:195},{l:"Tetris",v:100},{l:"Wii Sports",v:82}]},
{t:'musique',c:"Du plus long au plus court",mes:"durée du morceau",u:"minutes",
 i:[{l:"Bohemian Rhapsody",v:5.9},{l:"Stairway to Heaven",v:8},{l:"Imagine",v:3.1},{l:"Happy Birthday",v:0.4}]},
{t:'musique',c:"Du plus ancien instrument au plus récent",mes:"année d'apparition",u:"",rev:1,
 i:[{l:"Flûte en os",v:-40000},{l:"Harpe",v:-3000},{l:"Piano",v:1700},{l:"Synthétiseur",v:1964}]},
{t:'art',c:"De la plus grande statue à la plus petite",mes:"hauteur de la statue seule",u:"m",
 i:[{l:"Statue de l'Unité, Inde",v:182},{l:"Statue de la Liberté",v:46},{l:"Christ Rédempteur",v:30},{l:"David de Michel-Ange",v:5.2}]},
{t:'art',c:"Du plus long chantier au plus court",mes:"durée de construction",u:"ans",
 i:[{l:"Sagrada Família",v:143},{l:"Cathédrale de Cologne",v:632},{l:"Notre-Dame de Paris",v:182},{l:"Tour Eiffel",v:2}]},
{t:'litt',c:"Du plus grand nombre de personnages au plus petit",mes:"personnages nommés dans l'œuvre",u:"personnages",
 i:[{l:"Guerre et Paix",v:559},{l:"Le Seigneur des anneaux",v:400},{l:"Les Misérables",v:200},{l:"Le Vieil Homme et la Mer",v:3}]},
{t:'litt',c:"Du plus ancien au plus récent",mes:"année de naissance de l'auteur",u:"",rev:1,
 i:[{l:"Molière",v:1622},{l:"Victor Hugo",v:1802},{l:"Marcel Proust",v:1871},{l:"Albert Camus",v:1913}]},
{t:'langue',c:"Du plus grand nombre de caractères au plus petit",mes:"caractères du système d'écriture",u:"caractères",
 i:[{l:"Chinois, dictionnaire complet",v:50000},{l:"Chinois courant",v:3000},{l:"Japonais, kanji usuels",v:2136},{l:"Alphabet latin",v:26}]},
{t:'langue',c:"Du plus de temps verbaux au moins",mes:"temps et modes conjugués",u:"formes",
 i:[{l:"Turc",v:35},{l:"Français",v:21},{l:"Espagnol",v:17},{l:"Anglais",v:12}]},
];
